### ISSUE TITLE
Embedding Specific file from Gist containing multiple files

### ISSUE THREAD

**Issue by sachinsu** [carbon-app/carbon#1000]
**Describe the bug**
Does Carbon support embedding a specific file from Gist containing multiple files?

**To Reproduce**
  * Gist at https://gist.github.com/sachinsu/b2d914a563b49d4dd50a4143166f27ec has multiple files 
  * When trying to embed specific file (Cardwriter.cs) in Carbon App like https://carbon.now.sh/embed/b2d914a563b49d4dd50a4143166f27ec#file-cardwriter-cs. It still shows the first file (i.e. Card.cs) from Gist. 

Am i missing something?

<details>
  <summary>Code Snippet (If Applicable)</summary>
  <pre>
  <iframe src=" https://carbon.now.sh/embed/b2d914a563b49d4dd50a4143166f27ec#file-cardwriter-cs "></iframe>
  </pre>
</details>

**Comment by mfix22** [comment]
@sachinsu you are not missing anything! Currently, when using the GitHub Gist, we only show the first file.

I see that you are using the `#` hash location to try and specify the file name. Is this how you would expect to specify which file to show?

**Comment by sachinsu** [comment]
@mfix22 , Github uses `#` to link multiple files within same Gist so i just used it to give an example. It need not be `#` hash location and can be either in the form of Query parameter or Path itself.

**Comment by mfix22** [comment]
Thanks for the idea, @sachinsu. You can now select which file you want using the `filename` query param. 

Example Gist: https://gist.github.com/mfix22/4ee50f1c107be7e59e613724fc8ad949
File 1: https://carbon.now.sh/embed/4ee50f1c107be7e59e613724fc8ad949?filename=global.js
File 2: https://carbon.now.sh/embed/4ee50f1c107be7e59e613724fc8ad949?filename=local.js

**Comment by sachinsu** [comment]
Thank you @mfix22
