### ISSUE TITLE
Accessible sharing

### ISSUE THREAD

**Issue by TheSonOfThomp** [carbon-app/carbon#1002]
**Motivation**
Sharing an image of code can make it hard for everyone, particularly the visually impaired, to read the code. Additionally, people reading the code can't copy/paste it into their codebase.

**Suggested solution**
Recommended solution is to add a share feature which links to a read-only version of the code snippet. This way people following the link can view & copy the code without sharing the original editor link.
Additionally, the social preview images (e.g. `<meta name="twitter:image">`) should be the original image of the code.

**Comment by TheSonOfThomp** [comment]
I realize that I can import a Gist, and this functionality would essentially be a Gist competitor. I'll leave it to the maintainers to decide whether this is something to support

**Comment by mfix22** [comment]
@TheSonOfThomp the feature you are suggesting already exists, and there are also multiple other accessible ways to share a Carbon snippet:

1. Login into Carbon and create a "Saved snippet". Here is an example: https://carbon.now.sh/Si3J3gIXaTHTPjpB0kF8

This has multiple benefits: 
  * Pasting the Carbon URL into places like Twitter or Slack will automatically unfurl the image
  * These images will automatically include the correct, readable text in the description. 
  * You can update the snippet later, and then everywhere you shared the link will get automatically updated

2. You can also embed a Carbon snippet in your website using https://carbon.now.sh/embed. You can copy the iFrame or the embed URL using "Copy Menu". This will work for embedding Carbon on blogging platforms like Medium.com. 
<img width="935" alt="Screenshot 2020-05-13 18 43 50" src="https://user-images.githubusercontent.com/8397708/81883307-b6306e80-9549-11ea-8d82-a05ecb6f6306.png">

This allows users to not only read the text, but a "copy text" button is included automatically to make it even easier. 

3. Finally, if you use the "Tweet" button in Carbon, the correct `alt` text will be applied to your image automatically. This is the least a11y friendly, but the `alt` text is included, and we recommend also including a link to the source code (options 1 and 2 do this automatically)

**Comment by TheSonOfThomp** [comment]
Thanks. I knew about 2 & 3 but not 1. That definitely is what I was suggesting.

**Comment by mfix22** [comment]
Great, thanks! We should really add it to our README…
