### ISSUE TITLE
Microsoft Windows 10 style?

### ISSUE THREAD

**Issue by AnthonyMastrean** [carbon-app/carbon#1003]
I cannot create and share beautiful images of my source code with pseudo Microsoft Windows 10 style window chrome 😀 

The important elements seem to be the minimize line, the maximize box, and the close x.

**Screenshots**

Windows Explorer

![image](https://user-images.githubusercontent.com/217842/81850984-c5ea8b80-9526-11ea-8494-da34745d34a9.png)

MS Edge (Chromium)

![image](https://user-images.githubusercontent.com/217842/81851161-06e2a000-9527-11ea-84b3-0f51103e0fcb.png)

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: Windows 10
- Browser [e.g. chrome, safari]: MS Edge (Chromium)

**Comment by AnthonyMastrean** [comment]
Ah! I searched the issues, but not the pull requests. Will watch the linked PR!

**Comment by mfix22** [comment]
@AnthonyMastrean no worries! That PR has been open for a long time. I am going to try and investigate options tomorrow. 

Windows has been tricky, because we want to support it in a way that speaks to the Carbon brand, more than it does to Windows itself.
