### ISSUE TITLE
Carbon spinner

### ISSUE THREAD

**Issue by mfix22** [carbon-app/carbon#1004]
It would be awesome if Carbon got a new spinner to replace the generic one here: 
<img width="946" alt="Screenshot 2020-05-14 19 31 13" src="https://user-images.githubusercontent.com/8397708/82005154-82bd1500-9619-11ea-9142-355881fa1ae6.png">

As well as the `…`'s used in Button loading states.

**Comment by manishsundriyal** [comment]
I don't design, but I have a few ideas.

1. Something like a typing editor/terminal animation.
2. Classic old progress bar style loading animation.
3. An animation that would type carbon creatively.

@mfix22 if you already have some ideas, then let me know. I am interested to start my contribution journey with it.

**Comment by mfix22** [comment]
@manishsundriyal I would like something is: 
* Simple
* Reusable
* Scalable — i.e. can be used at many sizes (at the page level, within a button, etc.)
* Looping — if something loads quickly, I don't want to have to wait for an animation to finish to remove the loading indicator. 

Also just FYI @manishsundriyal, even if you don't end up designing the spinner, having conversations just like this one is useful to the project!

**Comment by manishsundriyal** [comment]
If that is the case, then I think we should use a simple _(not a fan of fancy stuff_) spinner.
Something like these https://getbootstrap.com/docs/4.4/components/spinners/
_(I know that we are not using bootstrap, it's just for spinner visuals)_

**Comment by mfix22** [comment]
Yes! I like those 👍 Gotta find one that is both simple, but has a touch of uniqueness, and ideally fits within the current Carbon aesthetic.

**Comment by albseb511** [comment]
@mfix22 

I made a PR thinking of a how atoms and electrons work

https://github.com/carbon-app/carbon/pull/1020

**Comment by mfix22** [comment]
@albseb511 thanks for sharing! Note to contributors: I want to finalize on a design within this thread before opening another PR. 

This only goes for this issue, since it mostly requires new designs. PRs totally welcome otherwise!  I just don't want people to do too much extra work.

**Comment by albseb511** [comment]
Makes sense
