### ISSUE TITLE
Why is the CS101 textbook listed in the README?

### ISSUE THREAD

**Issue by jlengrand** [carbon-app/carbon#1009]
Hey there, 

This question is not about Carbon, but it's README :). I was reading through it, and more specifically the list of community plugins for it.

There is [listed a textbook](https://github.com/carbon-app/carbon#textbooks) with a single link to a purchase link.
The author does not seem to be part of the core team, is this some kind of affiliate or did someone maybe slip this line as part of a larger Merge? 

I'd like to understand because all of the other plugins do make sense :).

**Comment by jlengrand** [comment]
Checking further using Git blame I see [this line was added by the main author of Carbon](https://github.com/carbon-app/carbon/commit/922446c6be4684818840f1aa2b97d847adb0ce1f) so I don't believe this is a mistake?

**Comment by mfix22** [comment]
The textbook featured and sited Carbon throughout. 

At the scale Carbon is at now, I can see this being distracting from what the README is trying to accomplish. 

I am going to remove it, because you are right, I have neglected to reexamine this list. Out of curiosity though, what concerns do you have in particular?

**Comment by jlengrand** [comment]
No concerns! I simply didn't read the book and it really wasn't obvious for me why it was listed. If it cites Carbon in the book, I do think it should be there! 

I'm happy to propose a PR if that helps! .

Thanks for the quick answer @mfix22 :). Have a great weekend

**Comment by mfix22** [comment]
I have tried to clarify and consolidate the sections better. 

You too @jlengrand! 🙂

**Comment by jlengrand** [comment]
Looks much clearer! Quick fix as well :). Thanks!

And thanks for this tool, it really is convenient when creating presentations!

**Comment by mfix22** [comment]
Thanks @jlengrand 🙏
