### ISSUE TITLE
Specifying fm (font-family) in GET does nothing

### ISSUE THREAD

**Issue by jeengbe** [carbon-app/carbon#1013]
Specifying the Font Family as a GET Parameter does nothing, whereas importing a config does change it. 

**Steps**
1. Open following URL: [https://carbon.now.sh/?fm=serif](https://carbon.now.sh/?fm=serif)

**Expected behaviour**
1. The editor's font family should change to `serif`

**Info**
- Windows 10 Home
- Google Chrome 81.0.4044.138:

**Notes**
Importing config.json found below does correctly set the font family.
Serif was chosen because it is easily distinguishable from the normal font.
<details>
  <summary>config.json</summary>
  <pre>{"fontFamily":"serif"}</pre>
</details>

**Comment by mfix22** [comment]
Carbon only supports a number of font families, which you have to specify by the name shown in the Font Family menu, like this https://carbon.now.sh/?fm=IBM%20Plex%20Mono (`IBM Plex Mono`)

Here are the [current available options](https://github.com/carbon-app/carbon/blob/master/lib/constants.js#L3-L17): 
* Anonymous Pro
* Droid Sans Mono
* Fantasque Sans Mono
* Fira Code
* Hack
* IBM Plex Mono
* Inconsolata
* Iosevka
* JetBrains Mono
* Monoid
* Source Code Pro
* Space Mono
* Ubuntu Mono

**Comment by jeengbe** [comment]
Why does it then work by specifying it in the file?
