### ISSUE TITLE
1 px border problem

### ISSUE THREAD

**Issue by XinwenCheng** [carbon-app/carbon#1017]
![carbon](https://user-images.githubusercontent.com/795334/82432858-36635080-9ac3-11ea-9598-c4d5b8909896.png)

Zoom in this screenshot, and you can see there's 1 px border around this picture, my window setting is following without paddings, so I think this border is an issue, please help to check, thanks in advance!

![image](https://user-images.githubusercontent.com/795334/82433080-83dfbd80-9ac3-11ea-9020-55587fe607ba.png)

**Comment by mfix22** [comment]
That is actually intentional @XinwenCheng. See the explanation here: https://github.com/carbon-app/carbon/blob/master/components/Carbon.js#L356

If you have other suggestions for how to handle this, please submit a PR.

**Comment by XinwenCheng** [comment]
Hi @mfix22, could you set _save for Twitter_ as an option?

**Comment by mfix22** [comment]
It should only be including the 1px border when clicking the Tweet button. Is that not currently happening?

**Comment by XinwenCheng** [comment]
@mfix22 , I didn't use Twitter function, I just use PNG to export.

![image](https://user-images.githubusercontent.com/795334/82633918-089b1a80-9c2f-11ea-8391-80c89240efdf.png)

**Comment by mfix22** [comment]
I am not sure I see the 1px border you are noticing, and I can't recreate the issue locally. I just created this image right now off `master`: 
![carbon (4)](https://user-images.githubusercontent.com/8397708/82634023-9c2e0600-9bb1-11ea-8ff3-06b47c806cbd.png)

Are you noticing the border issue here too?

**Comment by XinwenCheng** [comment]
Hi @mfix22, thanks for your response!

Please check,
![image](https://user-images.githubusercontent.com/795334/82634618-bf4bca80-9c30-11ea-9742-9d2312b5d0b9.png)

I exported the default image, and zoom it in to 1000%, please check the top of this image. I set both vertical and horizontal padding to minimum.
![carbon](https://user-images.githubusercontent.com/795334/82634524-76941180-9c30-11ea-8877-03f7e5fa3b8a.png)

**Comment by mfix22** [comment]
@XinwenCheng which browser and Operating system are you using?

**Comment by XinwenCheng** [comment]
OSX ```10.14.6```
Firefox ```76.0.1 (64-bit)```
GIMP ```2.8.22```

**Comment by mfix22** [comment]
@XinwenCheng just deployed a version of Carbon that removes the transparent row, which may have been throwing off the width/height calculation. 

Can you give it a try and see if that fixed your issue?

**Comment by mfix22** [comment]
Closing this as fixed. @XinwenCheng if you are still facing this issue, let me know and I will reopen.

**Comment by XinwenCheng** [comment]
![image](https://user-images.githubusercontent.com/795334/82850871-911c0280-9f30-11ea-88b9-98497fa111fb.png)

Hi @mfix22 , thanks for your improvement, but as you can see, left (and also right) still has translucent border.

**Comment by mfix22** [comment]
I just created 3 Carbon images on `master` w/ various settings, and I can't seem to recreate the 1px left and right borders
![carbon(3)](https://user-images.githubusercontent.com/8397708/82852021-7a38ca00-9eb6-11ea-932f-b3f467bf080e.png)
![carbon(2)](https://user-images.githubusercontent.com/8397708/82852023-7b69f700-9eb6-11ea-9ce2-0c2c916665d7.png)
![carbon(1)](https://user-images.githubusercontent.com/8397708/82852026-7c9b2400-9eb6-11ea-91ec-a3aa8e4bef71.png)

@XinwenCheng can you send me a link to a Carbon snippet that recreates the issue, with the exact code and settings?

**Comment by XinwenCheng** [comment]
@mfix22 , I just create this image on [https://carbon.now.sh/](https://carbon.now.sh/) with following setings.

![image](https://user-images.githubusercontent.com/795334/82856305-35597580-9f40-11ea-8d65-042feb46ca16.png)

![image](https://user-images.githubusercontent.com/795334/82856317-3e4a4700-9f40-11ea-8023-ff4edf7bd2f3.png)

![image](https://user-images.githubusercontent.com/795334/82856330-473b1880-9f40-11ea-9a7c-400a748f28c6.png)

**Comment by mfix22** [comment]
I was thinking more like a Carbon link, like this: https://carbon.now.sh/?bg=rgba(171%2C184%2C195%2C0)&t=seti&wt=sharp&l=auto&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=0px&ph=0px&ln=true&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false

Using these^ settings, I created this image, which does not the border problem. 
![carbon](https://user-images.githubusercontent.com/8397708/82980898-759c1080-9f9f-11ea-84a7-fc121e6dea90.png)

**Comment by XinwenCheng** [comment]
@mfix22 , no, it doesn't have this border any more. What should I do for the next step, bookmark this url?

**Comment by mfix22** [comment]
@XinwenCheng no need to bookmark it — I didn't do anything special 🙂 

All I did was remove the padding, and adjust the window theme.

**Comment by reyadussalahin** [comment]
I'm facing the 1px border issue. Please take a look.

I'm providing you the url: https://carbon.now.sh/SEY0cEbGlDZZ2VAf5jkA
