### ISSUE TITLE
Snippet Embed Feature Requests (iframe)

### ISSUE THREAD

**Issue by GraphicOwls** [carbon-app/carbon#1025]
It would really nice if we had settings options to turn off line wrapping for iframe embeds as well as auto height to be the height of the content (code), instead of a fixed width.

This would be nice for blogs articles & write ups etc.

**Comment by mfix22** [comment]
@GraphicOwls have you tried disabled "Auto-adjust width" in the Settings? You can just the `?wa=` query param to adjust this setting in your iFrame URL

**Comment by mfix22** [comment]
As for the width of your iFrame, I believe that is controlled in user-land. You can set the width of the iFrame yourself like:
```html
<iframe src="<carbon url goes here>" width="800" height="200"></iframe>
```

 Can you say more what you mean?

**Comment by mfix22** [comment]
@GraphicOwls going to close mark this to be closed, but feel free to chime in if I haven't answered your question.

**Comment by GraphicOwls** [comment]
I was talking about height and you're talking about width. It didn't answer my question.

**Comment by GraphicOwls** [comment]
Here is a video to make it easier and quicker: 
http://cloud.graphicowls.com/hFjZ2TV

**Comment by GraphicOwls** [comment]
> @GraphicOwls have you tried disabled "Auto-adjust width" in the Settings? You can just the `?wa=` query param to adjust this setting in your iFrame URL

I am not sure what you mean here either..

**Comment by mfix22** [comment]
@GraphicOwls I just had a chance to watch the screen recording. Are you asking that the Copy iFrame button set the height according to the height of the container? If so, I'd be happy to accept a PR to do that — right now these values are hard coded (https://github.com/carbon-app/carbon/blob/main/components/CopyMenu.js#L14). 

The reason it is hard coded as `473px` right now is to make it obvious that developers need to adjust this value themselves, but I would be happy to adjust them according to Carbon container size at time of copy. 


That said, if you are asking for a dynamic height capability, `iframe`s are not capable of that — they must be provided a static height property (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe).

**Comment by GraphicOwls** [comment]
@mfix22 Yes that's exactly right! Would be awesome if it could set the height according to the height of the container at the time of copy. Thanks a lot! :)

**Comment by GraphicOwls** [comment]
@mfix22 By the way Im still a noob with Javascript. Not too comfortable on doing that yet lol.

**Comment by mfix22** [comment]
No worries! Thanks for clarifying, @GraphicOwls. I opened a PR already that does exactly what you are describing (#1041), but wanted to be 100% before merging. 🙂

**Comment by GraphicOwls** [comment]
Any updates to this?

**Comment by mfix22** [comment]
It's done!
