### ISSUE TITLE
Support for HCL

### ISSUE THREAD

**Issue by dannyleesmith** [carbon-app/carbon#1026]
**Describe the bug**
Feature request to have HCL supported as a language option for things like Terraform snippets

**To Reproduce**
N/A

**Expected behavior**
Highlighting for HCL examples such as:

```HCL
terraform {
  required_version = "0.12.25"

  backend "s3" {
    acl     = "private"
    encrypt = true
    key     = "terraform.tfstate"
  }
}
```

**Screenshots**
N/A

**Info (please complete the following information):**
N/A

**Comment by mfix22** [comment]
@dannyleesmith do you know if there is a CodeMirror mode for Terraform/HCL?

**Comment by dannyleesmith** [comment]
@mfix22 wasn't aware of the term but I think if it was it would appear at this link and it does not: https://codemirror.net/mode/

**Comment by mfix22** [comment]
Please reopen this if anyones finds an HCL/Terraform mode for CodeMirror
