### ISSUE TITLE
Spelling mistake in the ReadMe

### ISSUE THREAD

**Issue by ankitshaw** [carbon-app/carbon#1027]
**Describe the bug**
There is a small spelling mistake in the readme file.

**To Reproduce**

1. Go to readme.md
2. Navigate to https://github.com/carbon-app/carbon#create-a-saved-snippet
3. See error in point 2 its written : Edit as you normally woud — your snippet will get saved automatically

**Expected behavior**
It should be would and not woud.
Expected "Edit as you normally would — your snippet will get saved automatically"

**Screenshots**
![image](https://user-images.githubusercontent.com/25771394/84430110-ce79d300-ac46-11ea-90ff-1e93bce84351.png)

**Comment by ankitshaw** [comment]
I would like to fix this!

**Comment by mfix22** [comment]
@ankitshaw thank you for posting this! In the future, if you see issues such as this, feel free to just open a PR to fix it directly 🙂
