### ISSUE TITLE
Dollar sign for lines in bash

### ISSUE THREAD

**Issue by b3u** [carbon-app/carbon#1028]
### Expected Behavior
Include option to display dollar sign ($) before lines, when language is bash.
Ideally, this would be the same color as the line numbers.

### Actual Behavior
No option available

<details>
  <summary>Browser: </summary>
  
Chrome 83
</details>

**Comment by mfix22** [comment]
@b3u thank you for submitting this issue. I know if may currently be toilsome to add, but it is possible to add the appropriate `$` to the snippet. My worry is that if we were to add this, then others would not want it, requiring a setting. 

We do not want to add language specific settings, especially for things that are physically possible with the current tool.

Marking this feature as won't fix, which will allow a week for reconsideration.

**Comment by b3u** [comment]
> I know if may currently be toilsome to add, but it is possible to add the appropriate $ to the snippet. My worry is that if we were to add this, then others would not want it, requiring a setting.

@mfix22 I understand your desire for simplicity. My only concern is that the dollar sign should not change the syntax highlighting. (Ideally, it might be a different color altogether [to indicate that it isn't a main part of the text])

See the image below, in which the syntax highlighting changes based on the presence of the dollar sign. (**Language**: Bash; **Theme**: Seti)
![code snippet](https://user-images.githubusercontent.com/39805353/84661157-efad1e80-aee7-11ea-8da0-a9b8bfce809c.png)

**Comment by mfix22** [comment]
Oh! I see what you mean. @b3u this is actually mostly out of our control, as it is determined by the CodeMirror mode itself (https://codemirror.net/mode/shell/)

On top of that, `$ ` isn't actually valid Bash, and not everyone uses `$ ` as their prompt, so I don't think CodeMirror would want to change this either. 

All that said, as a work around you can customize the individual pieces of text to your liking, like so: 
![carbon](https://user-images.githubusercontent.com/8397708/84728528-4e08ea00-af46-11ea-9820-5b6f015b2734.png)
