### ISSUE TITLE
Editor doesn't let go of cursor when resizing width

### ISSUE THREAD

**Issue by b3u** [carbon-app/carbon#1034]
**Describe the bug**
When resizing the code container, it's impossible to set a specific width.

**To Reproduce**

0. Go to https://carbon.now.sh
1. Click on right edge of code container.
2. Move cursor to one side
3. Although code container resizes, there's no way to set it at a particular width.

**Expected behavior**

**Screenshots**
![GIF](https://user-images.githubusercontent.com/39805353/84788502-315bc900-afbd-11ea-9900-27aeee39afc1.gif)

**Info (please complete the following information):**
- OS [e.g. macOS, Linux, Windows, iOS]: Linux
- Browser [e.g. chrome, safari]: Chrome 83 (also tested in Firefox 77)

**Comment by mfix22** [comment]
@b3u I have a feeling this is just because your pointer went offscreen. If you drag the window normally, staying within the window, does that work for you?

**Comment by mfix22** [comment]
I believe 6e1b115 will have fixed any issues you noticed.
