### ISSUE TITLE
Allow me to provide a custom window title

### ISSUE THREAD

**Issue by dotMorten** [carbon-app/carbon#1035]
When using the Windows-style layout, it looks like there's an extra line-feed above the code.

That got me thinking that it would actually be a really nice/useful feature to be able to "title" the code by providing a custom window title.

### Expected Behavior
Example:
![image](https://user-images.githubusercontent.com/1378165/84808113-138e6400-afbd-11ea-94be-83d9ac65afd6.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/1378165/84807999-e5108900-afbc-11ea-9fdf-9bfb980fab70.png)

### Alternative
It could also be allowed to extend the code up into the title bar to remove the extra top-padding:
![image](https://user-images.githubusercontent.com/1378165/84808335-69fba280-afbd-11ea-8da3-a8f07b24f389.png)

**Comment by mfix22** [comment]
You can add a window title by clicking at the top-center of the window, like so: 
![Kapture 2020-06-16 at 19 18 02](https://user-images.githubusercontent.com/8397708/84847502-29744700-b006-11ea-8991-9836fac9a10a.gif)

**Comment by dotMorten** [comment]
Oh totally missed that! I clicked in the left side!

**Comment by mfix22** [comment]
No worries! We don't talk about the feature much, because it isn't _core_ to Carbon, but it is there.
