### ISSUE TITLE
IBM Plex Mono font is missing

### ISSUE THREAD

**Issue by prtmshk** [carbon-app/carbon#1044]
**Describe the bug**
Code renders in the browser default monospace font when IBM Plex Mono is selected.

**To Reproduce**
Paste code.
⚙️ ➔ Editor ➔ Font ➔ IBM Plex Mono

**Expected behavior**
The code font should change to IBM Plex Mono.

**Screenshots**
<img width="1440" alt="Screenshot 2020-06-27 at 23 24 02" src="https://user-images.githubusercontent.com/29314504/85928833-b7d1ae00-b8cd-11ea-8715-d58f3f7f5ea5.png">

**Info**

- OS [e.g. macOS, Linux, Windows, iOS]: macOS 10.15.4
- Browser [e.g. Chrome, Safari, Firefox]: Safari, Safari Technical Preview

**Comment by mfix22** [comment]
Looks like this might be a bug in the Safari.

**Comment by prtmshk** [comment]
This issue isn’t occurring in other browsers? I don’t have any others so I can’t check.

**Comment by mfix22** [comment]
@prtmshk yup! On Chrome and Firefox, this is working fine 👍

**Comment by seagalputra** [comment]
Hi,
It seems IBM plex mono not loaded correctly from fonts.gstatic.com.

When I try opened up in Chrome browser. All the fonts were loaded correctly.

<img width="234" alt="Screen Shot 2020-08-12 at 11 22 45" src="https://user-images.githubusercontent.com/15377132/89975005-d24dc400-dc8e-11ea-82f8-b468ea91aa09.png">

But, when I opened the site in Safari. The IBM plex mono font is missing.

<img width="281" alt="Screen Shot 2020-08-12 at 11 25 31" src="https://user-images.githubusercontent.com/15377132/89975094-0a550700-dc8f-11ea-8d78-53f289653f9b.png">

**Comment by prtmshk** [comment]
Is the missing quotes here the issue?
https://github.com/carbon-app/carbon/blob/e1bdefcbb397a9887e80ea316e6e90b802af6e78/components/style/Font.js#L82

**Comment by seagalputra** [comment]
@prtmshk I've tried to add the quotes, change `@font-face` with `@import` from Google Fonts and it still won't loaded. I think it's the safari issue.

I'm using Safari Version 13.1.2 (15609.3.5.1.3) with macOs Catalina 10.15.6

**Comment by mfix22** [comment]
> @prtmshk I've tried to add the quotes, change `@font-face` with `@import` from Google Fonts and it still won't loaded. I think it's the safari issue.
> 
> I'm using Safari Version 13.1.2 (15609.3.5.1.3) with macOs Catalina 10.15.6

@seagalputra that's what I thought too. If you do have time to investigate more, that would be much appreciated. Maybe it is just that we need to configure the `@font-face` differently for Safari vs. Chrome.

Closing out this issue would be huge! Get us down to 20 issues! 💪

**Comment by seagalputra** [comment]
@mfix22 yes, when i tried to import IBM Plex mono fonts manually with `.ttf` font and surprisingly it works in Safari (and Google Chrome too).

<img width="800" alt="Screen Shot 2020-08-13 at 10 07 04" src="https://user-images.githubusercontent.com/15377132/90089879-c1638800-dd4c-11ea-84eb-410c3e6f6af8.png">

I think there's problem with font rendering in `.woff` and `.woff2` format. This is how I import the fonts
```css
@font-face {
    font-family: 'IBM Plex Mono';
    src: url('/static/fonts/IBMPlexMono-MediumItalic.ttf');
}
```
