### ISSUE TITLE
HTML Theme is not working properly

### ISSUE THREAD

**Issue by amirmeimari** [carbon-app/carbon#1047]
HTML formatting is not working. 

![image](https://user-images.githubusercontent.com/34706947/86320258-b72d7480-bc4b-11ea-90f8-1b8a8c73925e.png)

### Expected Behavior
Just wanted to add an HTML and CSS element together in a screenshot.

PS: It would be awesome if I could show the result of my HTML and CSS combination somewhere in the screenshot.

### Info

OS: Windows 10

Browser: Google chrome v 83.0.4103.116

**Comment by mfix22** [comment]
@amirmeimari please post a link to a Carbon snippet, or at least the code of your example so I can recreate the issue.

**Comment by amirmeimari** [comment]
@mfix22 sure

https://carbon.now.sh/?bg=rgba(55%2C140%2C206%2C1)&t=night-owl&wt=none&l=htmlmixed&ds=true&dsyoff=38px&dsblur=82px&wc=true&wa=true&pv=56px&ph=74px&ln=false&fl=1&fm=dm&fs=18px&lh=150%25&si=false&es=2x&wm=false&code=%253C!--%2520Adjacent%2520sibling%2520combinator%2520--%253E%250A%250A%253Cstyle%253E%250A%2520%2520li%253Afirst-of-type%2520%252B%2520li%2520%257B%250A%2520%2520%2520%2520color%253A%2520red%253B%250A%2520%2520%257D%250A%253C%252Fstyle%253E%250A%250A%253Cul%253E%250A%2520%2520%253Cli%253EOne%253C%252Fli%253E%2520%253C!--%2520This%2520line%2520is%2520selected%2520in%2520style%2520--%253E%250A%2520%2520%253Cli%253ETwo!%253C%252Fli%253E%2520%253C!--%2520Color%2520of%2520this%2520line%2520will%2520get%2520chnaged%2520---%253E%250A%2520%2520%253Cli%253EThree%253C%252Fli%253E%250A%253C%252Ful%253E
