### ISSUE TITLE
If we add a name to a snippet, it should be the suggestion filename when downloading

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [carbon-app/carbon#1050]
### Expected Behavior
that the downloaded file name is the same as the snippet name

### Info

Please complete the following information:

OS [e.g. macOS, Linux, Windows, iOS]: macOS

Browser [e.g. Chrome, Safari, Firefox]: Chrome

**Comment by mfix22** [comment]
This is a great idea! I would be happy to accept a PR that implements this, otherwise I will try to get to this during my next dev cycle 👍
