### ISSUE TITLE
GitHub login is failing

### ISSUE THREAD

**Issue by mrCodeslinger** [carbon-app/carbon#1058]
### Expected Behavior

If applicable, add screenshots to help explain your problem, or include Carbon links that recreate
your issue.
I can't log in to my account any more and i have a lot of code snippets there.
### Info

Please complete the following information:

OS [e.g. macOS, Linux, Windows, iOS]:
macOS

Browser [e.g. Chrome, Safari, Firefox]:
Chrome

**Comment by mfix22** [comment]
@mrCodeslinger were you by chance using Incognito mode? This is a known issue with Firebase login (https://github.com/firebase/firebase-js-sdk/issues/3004) that we can't currently fix at the moment. 

There is a workaround, however, which is outlined in this comment: https://github.com/firebase/firebase-js-sdk/issues/3004#issuecomment-647007598

> If you change the Chrome browser cookie settings from the default value of "Block third-party cookies in Incognito" to "Allow all cookies", Google authentication then succeeds in Chrome incognito:
![image](https://user-images.githubusercontent.com/8397708/88873669-037bbe00-d1d2-11ea-9b9b-c68fc4f9d2ac.png)

Obviously that is not ideal, so we will look for alternatives as well.

**Comment by mfix22** [comment]
There is also a known intermittent Firebase error, which is found here: https://github.com/firebase/firebase-js-sdk/issues/1926

(You don't need to worry about that, just posting for posterity)

**Comment by mfix22** [comment]
Closing as solved w/ recent Firebase upgrade — will reopen if we notice the same, or similar issue.
