### ISSUE TITLE
Snippet saved overlaps user menu

### ISSUE THREAD

**Issue by qw-in** [carbon-app/carbon#1062]
**Describe the bug**
Snippet saved notification displays over the user menu

**To Reproduce**

1. Be logged in
2. Save a snippet
3. Click username to trigger dropdown

**Expected behavior**

User menu is still accessible

**Screenshots**
![snippet-saved](https://user-images.githubusercontent.com/19194187/89092885-715aed80-d36a-11ea-93ce-01b753580c50.png)

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: Linux
- Browser [e.g. Chrome, Safari, Firefox]: Chrome (1080p)

**Comment by mfix22** [comment]
@qw-in do you have any suggestions for where we should render the toast message instead? If we render if right below the closed menu, and the user opens the menu, what should happen to the toast? Should it shift down? Should the login menu cover the notification? 🙂

**Comment by qw-in** [comment]
@mfix22 I think as a user of the UI my first instinct is similar to yours - shift down. However, I think having the toast disappear completely while the dropdown is open would be completely valid too

I will admit the lazy developer part of my brain was eyeing up the bottom right corner too for a while :sweat_smile:

**Comment by mfix22** [comment]
> I will admit the lazy developer part of my brain was eyeing up the bottom right corner too for a while 😅

I am right there with you 🤣 

I do like how Vercel does it https://vercel.com/design/toast…I'm going to definitely consider moving it to the bottom right.
