### ISSUE TITLE
Add custom theme sharing(import) option

### ISSUE THREAD

**Issue by DevT0ny** [carbon-app/carbon#1063]
I have created custom theme but I don't see any sharing or importing option.
As web developer, I saw your app uses local storage for storing theme but I don't want to tell anyone to execute this code in console to get  theme or something like that.
So I believe its easy to implement but before implementing the import feature please make sure it is not vulnerable to the XSS attack since local storage is vulnerable to XSS attack.

**Comment by mfix22** [comment]
@Ajith-stark sorry about the late response — I realized I looked into this issue locally and never got back to you here. 

I will follow up soon with a fix or other suggestions 👍

**Comment by mfix22** [comment]
Great suggestion by @Spielboerg  in #1105

> Unfortunately, the option "Export config" in the settings does not include the custom themes. Maybe an "export/import themes" option would be a simple and fast quick fix?

**Comment by mfix22** [comment]
This should have been fixed with dd9b43fcaef82ec2860dfcb6a378a126b9275a21. Please suggest further improvements in a new issue thread 🙂
