### ISSUE TITLE
Math symbols are missing in medium.com format

### ISSUE THREAD

**Issue by sniafas** [carbon-app/carbon#1067]
Math symbols are missing in Medium.com format in Python language

![On Medium](https://user-images.githubusercontent.com/4542013/89635973-837be500-d8b0-11ea-99d8-e64b82adf1a9.png)

### Expected Behavior

![On Carbon](https://user-images.githubusercontent.com/4542013/89636013-9b536900-d8b0-11ea-979d-b5e83fd670cd.png)

### Info

Please complete the following information:

OS [e.g. macOS, Linux, Windows, iOS]:
Linux
Browser [e.g. Chrome, Safari, Firefox]:
Chrome

**Comment by mfix22** [comment]
@sniafas could you please include the actual code snippet that you were using? That will make it a lot easier for me to investigate the issue.

**Comment by sniafas** [comment]
Yes, sure, the next two lines
```
y1 = w*x + b
return ((y-y_hat)**2).sum() / len(y)
```
