### ISSUE TITLE
No F# support?

### ISSUE THREAD

**Issue by pheuter** [carbon-app/carbon#1072]
## https://dotnet.microsoft.com/languages/fsharp

![image](https://user-images.githubusercontent.com/92698/89955273-a71c9380-dc00-11ea-89b9-995c989d37fb.png)

**Comment by mfix22** [comment]
https://carbon.now.sh/?l=ocaml

<img width="943" alt="Screen Shot 2020-08-11 at 6 56 24 PM" src="https://user-images.githubusercontent.com/8397708/89966606-6888d800-dc04-11ea-9bc5-ef11d3208bce.png">
