### ISSUE TITLE
PNG Export character encoding

### ISSUE THREAD

**Issue by qw-in** [carbon-app/carbon#1082]
Wanted to follow up on what I have been looking into. This is a follow up of the discussion in #1069 

I started out out trying to write some tests for the export in cypress but ran into a couple of issues:
1. Without modifying the app code, I could not figure out how pause execution of the code where the bug is present. After modifying the encoding and generating an image, the encoding changes are reverted immediatly
1. Cypress does not handle file downloads particularly well for this use case [right now](https://github.com/cypress-io/cypress/issues/949)

This lead me to try out using the `open` feature in carbon. The idea was load a specific snippet, open it, and compare the resulting image using something like [`cypress-image-snapshot`](https://www.npmjs.com/package/cypress-image-snapshot). Unfortunatly cypress does not seem to be able to load `blob:` urls. If anyone knows a way around this please let me know!

Now I am looking into potentially fixing the encoding issues at the source - which would mean carbon could avoid having to deal with encoding at all. I have verified that this does in fact appear to be an issue in `dom-to-image` ([see this sandbox](https://codesandbox.io/s/dom-to-image-encoding-z4p9k)). Unfortunatly [`dom-to-image`](https://www.npmjs.com/package/dom-to-image) was last updated in 2017 and does not appear to be actively maintained.

I found [a fork](https://www.npmjs.com/package/dom-to-image-more) that is active but unfortunatly in my testing it does not appear to be a drop in replacement. See the differences in the images below

### dom-to-image
![dom-to-image](https://user-images.githubusercontent.com/19194187/90208063-bf291a00-dd9c-11ea-832d-ce07a8f77d8d.png)

### dom-to-image-more
![dom-to-image-more](https://user-images.githubusercontent.com/19194187/90208074-c3553780-dd9c-11ea-9f8c-383a10182f38.png)

It appears to be either a font or sizing issue. My concern would be that switching would also potentially uncover other variances that may be a pain to track down.

For now I am going to look into how difficult patching the original character encoding issues in `dom-to-image` would be. Suggestions appreciated!

**Comment by qw-in** [comment]
This (https://github.com/tsayen/dom-to-image/pull/346) one line change seems to completely fix the issue and should remove the need to have special encoding handling for PNGs from carbon completely. The change did not break and of the `dom-to-image` tests

**Comment by mfix22** [comment]
@qw-in I thought about the integration testing more after I mindlessly said it would be great to include some, and you are totally right — it is basically impossible to test this functionality with Cypress. Please don't worry about testing this portion, and sorry for all the work you have put into it so far!

Amazing work with tsayen/dom-to-image#346, although I am not convinced a new version will get released. A couple options come to mind. 
1. Can we just copy paste a local fork under [`lib/`](https://github.com/carbon-app/carbon/tree/main/lib)? That would work for me.
2. Otherwise, let's use [`patch-package`](https://www.npmjs.com/package/patch-package) to make the change.

If you don't get around to this, I can try and pick this up later, though I really do appreciate your help 🙏

**Comment by qw-in** [comment]
@mfix22 Yeah I don't expect it to get merged but figured I would open it for reference. Although the `dom-to-image-more` pr did get merged (https://github.com/1904labs/dom-to-image-more/pull/23) :tada:

I think at least short term a local version makes perfect sense! I was wondering about forking and releasing a scoped npm package (`@carbon/dom-to-image` has a nice ring :smile:) but lib and patch-package are both great options!

I think you should make the call since you are the one who will likely have to maintain it - but happy to open a PR for whichever route!

**Comment by mfix22** [comment]
Rad, congrats 🎉 

I prefer a local copy of regular `dom-to-image` for now 👍 Really appreciate your help here.

**Comment by qw-in** [comment]
I saw the branch you made, looks perfect! I've got a busy couple days but I'll take a crack at it later this week. Want to take a second shot at some sort of automated regression testing. Have a couple ideas I'd like to try out

**Comment by mfix22** [comment]
Very cool. Closing this issue with #1083, but please open a new one if you have other ideas to discuss. 

Might be cool for Carbon to publish our `dom-to-image` w/ the fix you made, and maybe we can even incorporate the improvements made in https://www.npmjs.com/package/retina-dom-to-image
