### ISSUE TITLE
Embeds Suddenly Stopped Working

### ISSUE THREAD

**Issue by kevinrodriguez-io** [carbon-app/carbon#1087]
**Describe the bug**
I created some snippets to embed in a medium blogpost a couple of days ago, now, my readers report a lot of 404's.

**To Reproduce**
Create snippet
Copy generated link
Embed
(?)

(Taken from the README.md):

- Login using the "Sign in/Sign up" button
- Edit as you normally would — your snippet will get saved automatically
- Copy the URL from your browser window and share away!

**Expected behavior**
Embedded snippets should be working fine

**Screenshots**
<img width="363" alt="Screen Shot 2020-08-24 at 17 38 26" src="https://user-images.githubusercontent.com/6248571/91106747-ac320780-e630-11ea-875d-2c06f950d0d4.png">
<img width="965" alt="Screen Shot 2020-08-24 at 17 38 32" src="https://user-images.githubusercontent.com/6248571/91106749-acca9e00-e630-11ea-8bbf-c73192d514ea.png">

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]:
macOS
- Browser [e.g. Chrome, Safari, Firefox]:
Brave
- Carbon URL [e.g. carbon.now.sh?bg=pink]:
https://carbon.now.sh/M5wcF5Qkf1nemlN71jtc

<details>
  <summary>Code snippet</summary>
  <pre>
    I can't even access it
  </pre>
</details>

**Comment by mfix22** [comment]
This issue should be resolved now. Sorry for the inconvenience.

**Comment by kevinrodriguez-io** [comment]
@mfix22 Thanks!
