### ISSUE TITLE
Option to make it look like a vim editor

### ISSUE THREAD

**Issue by itstommi** [carbon-app/carbon#1089]

**Comment by mfix22** [comment]
Hey @itstommi — which features in particular? Do you mean the cursor? Or also the bottom text? Can you share a screenshot so I am certain of which features you are interested in?

**Comment by Aslemammad** [comment]
I think we can implement the vim editor there. I can check if I can make PR for this?

**Comment by itstommi** [comment]
Nvm sorry I just wanted to be able to have the tildes but I realized I could just manually type them out and change the colors 🤦‍♂️

**Comment by Aslemammad** [comment]
But I think the vim option is a good thing.

**Comment by itstommi** [comment]
> But I think the vim option is a good thing.

I mean if you want to, go for it

**Comment by Aslemammad** [comment]
I'm working on vim, emacs, and sublime keymaps, Thanks for the permission.

**Comment by Aslemammad** [comment]
#1091
