### ISSUE TITLE
Anonymous functions

### ISSUE THREAD

**Issue by Aslemammad** [carbon-app/carbon#1090]
In dev mode React returns: "Anonymous arrow functions cause Fast Refresh to not preserve local component state", It's a not so potential warning but I want to send PR to Make all anonymous functions to Named arrow functions. Can I take its PR?

**Comment by Aslemammad** [comment]
I can make the code better in other places of the source if you like.

**Comment by mfix22** [comment]
> In dev mode React returns: "Anonymous arrow functions cause Fast Refresh to not preserve local component state", It's a not so potential warning but I want to send PR to Make all anonymous functions to Named arrow functions. Can I take its PR?

@Aslemammad please do! But please make the limited amount of changes required to fix the error message.

**Comment by Aslemammad** [comment]
OOh, Yes, Thanks for your permission.

**Comment by mfix22** [comment]
@Aslemammad feel free to work on fixing this, but no need to keep this issue open, as it is not actually a _bug_ in Carbon.
