### ISSUE TITLE
Keymaps

### ISSUE THREAD

**Issue by Aslemammad** [carbon-app/carbon#1092]
**Is your feature request related to a problem? Please describe.**
Adding support for Vim, Emacs, Sublime (ordinary) keymaps to Carbon.

**Pull Request.**
#1091

**Comment by Aslemammad** [comment]
If people were interested in this feature, we'll work on it more, please see this website and tell us your opinion. https://carbon-1nyaaf788.vercel.app/

**Comment by mfix22** [comment]
Like I mentioned in #1091, we do not want to support multiple keymaps. Potentially, we might be interested in supporting a VIM mode, but this can probably be handled by a browser/operating system instead of Carbon.
