### ISSUE TITLE
AutoHotkey

### ISSUE THREAD

**Issue by Lateralus138** [carbon-app/carbon#1093]
I know people hate it, but is there any possibility of adding **AutoHotkey** to the list?

Probably not, but I have to try :D

**Comment by Aslemammad** [comment]
I think I love it, but what you mean exactly, give us some examples.

**Comment by mfix22** [comment]
> AutoHotkey

I am not sure what AutoHotkey is — can you tell me more? In particular, what are you trying to solve?

**Comment by Lateralus138** [comment]
Nevermind; I was looking through the list of code the Carbon app supports and I didn't see AHK listed, but it seems to work on the 'Auto' setting so there's there was no need for me to post this. Sorry for wasting your time. 

For those who asked what AutoHotkey is it is a powerful Windows high level scripting language used for all sorts of things, but specifically used for automation with the added enhancement of better controls over hotkeys and full access to the win32 api via DllCalls.

Here's a simple preview of what I wanted to do and now realize I can do it;
## Part of an AutoHotkey class:
![Carbon Preview](https://raw.githubusercontent.com/Lateralus138/Lateralus138.github.io/master/images/carbon.png)  

Sorry for opening this issue.
