### ISSUE TITLE
Carbon and CodeSnap?

### ISSUE THREAD

**Issue by ldhan0715** [carbon-app/carbon#1094]
Hi, I was just wandering GitHub, and I found out a similar application (actually extension) with Carbon.
It's name is [CodeSnap](https://github.com/kufii/CodeSnap), and it is almost same as Carbon! The style, OS X style window controls, and etc. Although idea can overlap, but how can the design and features can be so similar?

I don't mean to make such trouble but just wondering...

**Comment by mfix22** [comment]
I have never seen CodeSnap before! Might have been inspired by Carbon, I am not sure. Very neat though 🙂
