### ISSUE TITLE
Ability to specify random background image with vscode plugin

### ISSUE THREAD

**Issue by yashbhutwala** [carbon-app/carbon#1098]
I love this app and I love the VSCode plugin for it.  However, I would like the generated image to automatically select a random background image.  Is is possible to add that feature?

**Comment by mfix22** [comment]
Hey @yashbhutwala, thanks for the kind words! 🖤 

There are lots of other tools to generate a random color, which can then be passed in to Carbon like so: https://carbon.now.sh/?bg=rebeccapurple. VSCode can generate this color for you.

Hope that helps!

**Comment by mfix22** [comment]
Another option would be to use Unsplash backgrounds, which are indeed random 🙂

**Comment by yashbhutwala** [comment]
@mfix22 how can I get vscode plugin to automatically select a random Unsplash background for me?  I don't think that's possible right now, and would be a nice to have.

**Comment by mfix22** [comment]
https://marketplace.visualstudio.com/items?itemName=jrebocho.vscode-random

https://coolors.co/

🙂
