### ISSUE TITLE
I want this feature in my website

### ISSUE THREAD

**Issue by maneeshsandra** [carbon-app/carbon#1100]
i have a website for a collection of programs and all i want is i want to show my code on my website in carbon view is that possible to include carbon in my website and display data from my database in this template

**Comment by mfix22** [comment]
Yup! You can use Carbon embeds to render a carbon snippet on your website. 

carbon.now.sh/embed

<img width="982" alt="Screen Shot 2020-09-16 at 8 12 43 PM" src="https://user-images.githubusercontent.com/8397708/93407953-43613800-f848-11ea-8aa6-ff2eecc38bc2.png">
