### ISSUE TITLE
Support for image highlighting

### ISSUE THREAD

**Issue by asm0dey** [carbon-app/carbon#1104]
**Describe the solution you'd like**
Some libraries, for example highlightjs and prismjs allow to highlight lines. I would like to have similar option. Possibly in export or in editor settings.

**Additional context**
Sometimes I use code in presentation. But explaining code without code highlighting is hardly possible.

**Comment by mfix22** [comment]
Hi @asm0dey this is currently supported! If you turn on "Line numbers" in the Settings menu (or by visiting https://carbon.now.sh/) you can highlight lines by clicking. You can also Shift-Click to select a group of lines

![carbon (2)](https://user-images.githubusercontent.com/8397708/94998541-4ad25200-0567-11eb-96b1-404f579f073d.png)

**Comment by asm0dey** [comment]
Thanks, that works (but quite not obvious that they can disable line numbering afterwards)!

**Comment by mfix22** [comment]
Yup! That's a great point. If you have suggestions for adding a better way to toggle line highlights, I am all ears 👂

**Comment by asm0dey** [comment]
I believe there is a way: one additional field in editor settings, which describes lines should be highlighted. For example in syntax 1-3,5,7. Where comma separates groups and groups are ranges or single lines.

**Comment by mfix22** [comment]
@asm0dey I'd be happy to accept a PR that implements that.

**Comment by asm0dey** [comment]
Currently, I have no any idea on how to implement it, but I believe it's worth creating issue :)

**Comment by mfix22** [comment]
Thanks @asm0dey ! I'll consider looking into it.
