### ISSUE TITLE
Suggestion - Export formatted code for applications such as Word

### ISSUE THREAD

**Issue by MillennialDIYer** [carbon-app/carbon#1106]
Hi there,

Just found the site and found it interesting. The aesthetics are great. That said, images of codes aren't something I find myself needing all that often. Rather, formatted code (especially language-specific color-coding and numbered list formatting) is something I use all the time. Especially for pasting into Word documents.

Currently, for that purpose I use [PlanetB Syntax Highlighter](http://www.planetb.ca/syntax-highlight-word), though it isn't always the most elegant solution. You might want to consider whether it would be a worthy and/or feasible idea to add an equivalent export option - namely, being able to paste raw text code in your window, and export out formatted text for pasting into applications like Word. It would be awesome to have one solution for both exporting as an image as well as copy-able text.

In any case, kudos for the service. It's bookmarked and I'll definitely check it out in further detail later.

**Comment by mfix22** [comment]
@MillennialDIYer  Thanks for the kind words! 🖤 

We have an open issue to export Carbon snippets as RTF (https://github.com/carbon-app/carbon/issues/1042), which would be renderable in word, so going to close this to track over there.

That said, I would suggest just using a Carbon PNG, and dropping that in your Word document. I have seen other authors write entire books this way 🙂 

Cheers!

**Comment by MillennialDIYer** [comment]
Thanks for the response, @mfix22!

The RTF snippets sounds good, looking forward to test that out once it's done. Regarding PNG, that on the other hand wouldn't be of any use in my typical use scenario, as copying and pasting the code for later reference or reuse is the utility.

Anyway, have a good one.

**Comment by mfix22** [comment]
You too @MillennialDIYer !
