### ISSUE TITLE
# character replaced by %23 when exporting PNG

### ISSUE THREAD

**Issue by theoctober19th** [carbon-app/carbon#1115]
**Describe the bug**
The `#` character in the code is changed to `%23` while exporting PNG. 

**To Reproduce**
Write any code that has # in the syntax. Export the code to a PNG. The `#` character appears as `%23`.

**Expected behavior**
`#` character should be seen as `#` character in the exported PNG.

**Screenshots**
<img width="959" alt="Screen Shot 2020-10-04 at 08 58 02" src="https://user-images.githubusercontent.com/25663267/95006069-bbd54080-061f-11eb-8d50-afb4c639a914.png">
<img width="787" alt="Screen Shot 2020-10-04 at 08 58 20" src="https://user-images.githubusercontent.com/25663267/95006072-c2fc4e80-061f-11eb-98dc-1f098545055e.png">

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: macOS
- Browser [e.g. Chrome, Safari, Firefox]: Chrome
- Carbon URL [e.g. carbon.now.sh?bg=pink]: https://carbon.now.sh/?bg=rgba(171%2C184%2C195%2C0)&t=a11y-dark&wt=none&l=python&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=print(%2522hello%2522)%2520%2523prints%2520hello

<details>
  <summary>Code snippet</summary>
  <pre>
  
  </pre>
</details>

**Comment by mfix22** [comment]
@theoctober19th sorry about the inconvenience!
