### ISSUE TITLE
Rounded Edges on Image Background

### ISSUE THREAD

**Issue by JulianWebb** [carbon-app/carbon#1119]
**Is your feature request related to a problem? Please describe.**
Having sharp edges on the image contrasts against the rounded edges of the "IDE"

**Describe the solution you'd like**
An option to give rounded edges to the image along the background would be nice.

**Describe alternatives you've considered**
I know I can use an image editor such as GIMP to add rounded edges myself, but it would be nice if external applications weren't needed.

**Additional context**
Like this: 
![image 1](https://user-images.githubusercontent.com/471907/96950048-403c1600-149e-11eb-8b74-4fe1592e0b2d.png)
Instead of this: 
![image](https://user-images.githubusercontent.com/471907/96950079-58ac3080-149e-11eb-81fd-00ff4f88c1dc.png)

**Comment by mfix22** [comment]
Hi @JulianWebb, this is something we want to avoid adding to Carbon, since it can be easily adjusted in other software. 

If other folks write in suggesting the same, we will reconsider. 

Just to help you out a bit though, try entering this in your browser's console:
```js
document.querySelector('.export-container').style.borderRadius = "8px"
```
🙂
