### ISSUE TITLE
Update to support Optional chaining (?.) for Javascript

### ISSUE THREAD

**Issue by khoin** [carbon-app/carbon#1128]
Hi there,

ECMA-262 includes optional chaining which breaks the highlight syntax of the lines following its usage:

![image](https://user-images.githubusercontent.com/4620399/97863201-76a63c00-1cbb-11eb-86a4-08275a10f051.png)

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by mfix22** [comment]
Would you do me a favor and file this with CodeMirror? This should be handled by their parser.

**Comment by khoin** [comment]
@mfix22 Code Mirror maintainer says it's been fixed several releases ago.

**Comment by mfix22** [comment]
Cool — should be working now: https://carbon.now.sh/?bg=rgba%28171%2C+184%2C+195%2C+1%29&t=monokai&wt=none&l=javascript&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=window%253F.test
