### ISSUE TITLE
Specify Width and Height dimensions in pixels. 

### ISSUE THREAD

**Issue by ShynnSup** [carbon-app/carbon#1129]
Hello, it would be really great if you could add the feature to specify dimensions in pixels. I want to make a 1080 x 1080 PNG picture but I can't with the current features. Thank you!

**Comment by t-mangoe** [comment]
Hi. I worked on this issue, and tried editing codes.
I added the size setting item("custom"), and made it enable to set width and height values.
How about this? If you like, please comment.
(I'm sorry for my poor English...)

![スクリーンショット 2021-04-24 14 06 10](https://user-images.githubusercontent.com/22494246/115953953-484a4080-a529-11eb-9190-a1ce6c2359f2.png)

**Comment by mfix22** [comment]
You can already set the width of the screenshot by dragging the corner of the editor. The height is set by the height of the code itself, plus the padding. 

<img width="991" alt="Screen Shot 2021-05-22 at 2 38 37 PM" src="https://user-images.githubusercontent.com/8397708/119241474-6e083c80-bb0b-11eb-92a4-1d4629689561.png">


Setting the height explicitly doesn't align with this model for displaying the text.

**Comment by t-mangoe** [comment]
Oh, I did't know the feature. I got it.
