### ISSUE TITLE
[Request] Keyboard Shortcuts - Extend and customize

### ISSUE THREAD

**Issue by dst27** [carbon-app/carbon#1143]
**Is your feature request related to a problem? Please describe.**
I frequently use Carbon to paste code snippets and copy the image to my Clipboard to paste into documents. With the current shortcuts, it's not only not possible to copy the Carbon generated image to clipboard, but even the existing shortcuts do not work well on Windows platform where Winkey + E is an OS default shortcut to open the File Explorer (⇧ ⌘ E triggers a PNG export on OSX).

**Describe the solution you'd like**
I want Carbon to support extended and customizable shortcuts, so we can set and customize shortcuts for tasks like copying the Carbon generated PNG to clipboard so that they also work on Windows systems.

**Comment by mfix22** [comment]
@dst27 this should be easy to do! Which shortcuts would you like to be available? Can you share which actions you do repeatedly, and what shortcuts you would like to trigger them? 

Feel free to submit your own PR for this, too. Otherwise I will try and get to it when I find some time.

**Comment by dst27** [comment]
> @dst27 this should be easy to do! Which shortcuts would you like to be available? Can you share which actions you do repeatedly, and what shortcuts you would like to trigger them?
> 
> Feel free to submit your own PR for this, too. Otherwise I will try and get to it when I find some time.

Thank you for your considerate response!
I use Copy to Clipboard and Download as SVG options the most apart from Download as PNG.
I think `ctrl + alt + c` and `ctrl + alt + s` shortcuts for these might be a good fit, though it would be extra sweet if we could customize them in the config menu!

**Comment by mfix22** [comment]
> Also to reemphasize, the current Download as PNG shortcut doesn't work on Windows systems because it conflicts with a default system shortcut so that needs to be changed/changeable as well.

I did not know this! Thanks for bringing this to my attention. What does command do on Windows currently?

**Comment by mfix22** [comment]
@dst27 what would you want the shortcut for "Export as PNG" to be? I was trying to avoid <kbd>P</kbd> because of its association with "Print"

**Comment by dst27** [comment]
> @dst27 what would you want the shortcut for "Export as PNG" to be? I was trying to avoid P because of its association with "Print"

@mfix22 I think `ctrl + alt + s` would be nice for exporting as PNG.
Thanks for working on this!

**Comment by mfix22** [comment]
I'm going to try it with `preventDefault` and see if that works. If we run into issues, I'll reopen this.
