### ISSUE TITLE
[Request] Add size options similar to Export to Copy to Clipboard

### ISSUE THREAD

**Issue by dst27** [carbon-app/carbon#1144]
**Is your feature request related to a problem? Please describe.**
I primarily use carbon to generate code snippet images for text documents, so I prefer Copy to Clipboard to Exporting the image. While Copy to Clipboard works well, it's missing the 2X and 4X size options available with the Export option.

**Describe the solution you'd like**
I would like Carbon to honor the size preferences set in the Export menu or alternatively have a separate Copy to Clipboard size preference if required.

**Comment by mfix22** [comment]
@dst27 if you pick 2x or 4x in the export window, those settings will be honors when clicking "Copy image"

For what it is worth, 2x is the default, so if you want to use that, it will work out of the box. 

Hope that helps!
