### ISSUE TITLE
[Request] Be able to set a certain aspect ratio to the picture

### ISSUE THREAD

**Issue by made-indrayana** [carbon-app/carbon#1147]
**Is your feature request related to a problem? Please describe.**
This is a feature request because I think this is very useful for people wanting to post code snippets as a part of their social media content.

**Describe the solution you'd like**
An aspect ratio chooser with some presets (e.g. Square, 16:9) or manual input

**Comment by mfix22** [comment]
Hey @made-indrayana, this is a feature we still support, though it is mostly hidden at this point. You can download your image as a square one by setting `?si=true`, like so: https://carbon.now.sh/?si=true

If you want to adjust the aspect ratio further, try dragging the edge of the editor window. 

Hope that helps!

![carbon (2)](https://user-images.githubusercontent.com/8397708/102673340-99e05a00-4148-11eb-9a77-e3846bf9e85f.png)

**Comment by haschdl** [comment]
hello @mfix22 and @made-indrayana I wasn't able to get it to work with `si=true` - do I append that after I pasted my code and make the other adjustments?
https://carbon.now.sh/?si=true => browsing from this link does not load the editor as a 1:1 aspect ratio, so I'm under the impression this is no longer working

**Comment by made-indrayana** [comment]
> hello @mfix22 and @made-indrayana I wasn't able to get it to work with `si=true` - do I append that after I pasted my code and make the other adjustments?
> https://carbon.now.sh/?si=true => browsing from this link does not load the editor as a 1:1 aspect ratio, so I'm under the impression this is no longer working

This is working when you export the image but yes, the editor doesn't really _show_ you what it looks like.
