### ISSUE TITLE
Issuing with copy to clipboard in FireFox

### ISSUE THREAD

**Issue by WhyNotHugo** [carbon-app/carbon#1148]
I'd love to be able to copy the image to clipboard.

Right now, the "copy to clipboard" option only allows copying an embed code -- which is generally now very useful (e.g.: I can't paste this in 99% of the places).

Would it be possible for "copy to clipboard" to actually copy the image?

I think the app is great in _generataing_ images, but being unable to _copy_ it just seems like a huge miss.

**Comment by AryanBeezadhur** [comment]
What do you mean?

You can definitely copy an image to the clipboard:

![image](https://user-images.githubusercontent.com/34424160/102646941-d3bb5b80-415c-11eb-8f75-48650596a13e.png)

### Result:

![image](https://user-images.githubusercontent.com/34424160/102646962-dae26980-415c-11eb-97a7-a750e50deca5.png)

**Comment by WhyNotHugo** [comment]
That option is not visible for me o.O

![image](https://user-images.githubusercontent.com/730811/102651010-a9b96780-4163-11eb-840b-6b9dcdf988a4.png)

Are we looking at the same website? https://carbon.now.sh/

**Comment by mfix22** [comment]
@WhyNotHugo which browser and operating system are you using? It only is available if your Browser supports copying an image to the clipboard.

**Comment by AryanBeezadhur** [comment]
@WhyNotHugo yes I am using the same site

Try clearing the cache and doing a hard reload by right-clicking the reload button when DevTools are open:

![image](https://user-images.githubusercontent.com/34424160/102696180-52c79700-4224-11eb-9bec-9bc9f0d78a92.png)

**Comment by mfix22** [comment]
@WhyNotHugo which browser are you using? 
![image](https://user-images.githubusercontent.com/8397708/102922029-386b0480-4442-11eb-98ec-d82322ecf3e2.png)

**Comment by WhyNotHugo** [comment]
> Try clearing the cache and doing a hard reload by right-clicking the reload button when DevTools are open:

Right clicking has something completely different on Firefox. I did clear cache and reload though, with no change.

I'm on Firefox 84.0.1.

Here's the output of the debug console:

![image](https://user-images.githubusercontent.com/730811/103152272-6623b680-477e-11eb-9b19-59df45f3fedd.png)

**Comment by AryanBeezadhur** [comment]
As @mfix22 [pointed out](https://github.com/carbon-app/carbon/issues/1148#issuecomment-748375675):

> @WhyNotHugo which browser and operating system are you using? **It only is available if your Browser supports copying an image to the clipboard.**

---

It seems like copying images to the clipboard is not yet supported in Firefox.

**Comment by WhyNotHugo** [comment]
I've never had issues copying image to clipboard on Firefox.

> From version 57 onward, you can copy images to the clipboard using the clipboard.setImageData() API.

Source: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

This version was release 19th April 2017.

**Comment by mfix22** [comment]
Ahh, I see. FireFox has a custom API for copying image data: 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard/setImageData

```js
browser.clipboard.setImageData(imageData, imageType)
```

If anyone wants to add implement this, that would be much appreciated! Otherwise I will try and get to this soon.

**Comment by WhyNotHugo** [comment]
Oops. Actually, that particular API is for extensions, not websites. :sweat: 

However, the [clipboard api page](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) does link to this article which explains how to copy images: https://web.dev/async-clipboard/

**Comment by mfix22** [comment]
> As of this writing, Firefox only supports text; and image support is limited to PNGs in some browsers. If you're interested in using the API, consult a browser support table before proceeding.

https://web.dev/async-clipboard/#write()

**Comment by mfix22** [comment]
Going to close this as unfixable, but please reopen if FireFox eventually supports copying an image to the clipboard from the browser.

**Comment by artemtech** [comment]
according to Firefox documentation, you need to enable `dom.events.asyncClipboard.clipboardItem` config in `about:config` [1]. 
In my firefox, it was set false, after changing that config to `true` and refresh carbon.now.sh, copy image to clipboard menu shown

cc @WhyNotHugo  @mfix22 


[1] https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem/ClipboardItem#browser_compatibility
![pict](https://user-images.githubusercontent.com/22854966/148551899-02646825-8d4f-406a-aa3f-d1c82843d3f9.png)

**Comment by noyyyy** [comment]
> according to Firefox documentation, you need to enable `dom.events.asyncClipboard.clipboardItem` config in `about:config` [1]. In my firefox, it was set false, after changing that config to `true` and refresh carbon.now.sh, copy image to clipboard menu shown
> 
> Firefox Developer Edition 95.0b12 (64-bit) Arch Linux KDE Plasma Wayland
> 
> cc @WhyNotHugo @mfix22
> 
> [1] https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem/ClipboardItem#browser_compatibility ![pict](https://user-images.githubusercontent.com/22854966/148551899-02646825-8d4f-406a-aa3f-d1c82843d3f9.png)
> 
> edit2: after changing `dom.events.asyncClipboard.clipboardItem` to true, yes we can get the menu shown. BUT, image data not copied into clipboard after clicking it. Got this error message from firefox console `DOMException: Clipboard write was blocked due to lack of user activation`
> 
> edit3: restarting firefox solved issue in edit2

@artemtech It works for me. Thank you very much!
