### ISSUE TITLE
Nice loophole with Dracula Pro theme

### ISSUE THREAD

**Issue by ThatAnonymousG** [carbon-app/carbon#1149]
**Describe the bug**
When you write the code in some other theme and change the theme to Dracula Pro the text will remain unchanged which essentially allows you to use a paid theme for free because I can even export using this bug.

**To Reproduce**

1. Go to [https://carbon.now.sh](https://carbon.now.sh)
2. Write your code.
3. Use the Dracula Pro theme and try to export.

**What to expect**
I don't know if this is intentional but I think the text should revert back to the default one for the Dracula Pro theme and you should not be able to export it either.

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: Windows
- Browser [e.g. Chrome, Safari, Firefox]: Chrome
- Carbon URL [e.g. carbon.now.sh?bg=pink]: carbon.now.sh

**Comment by mfix22** [comment]
It's not a paid theme — you can use it on Carbon for free 🙂 The "Purchase" button is if you want to buy the theme for your own editor, locally.
