### ISSUE TITLE
Edit Padding

### ISSUE THREAD

**Issue by Mr-Flamingo** [carbon-app/carbon#1151]
![Screenshot_20201229-155344](https://user-images.githubusercontent.com/47935976/103288851-8194f880-49ee-11eb-94e2-d22a3a50fb77.jpg)

 I think it will be better if there is lsss padding around the coding area

**Comment by mfix22** [comment]
You can adjust the padding in the settings:

<img width="1013" alt="Screen Shot 2021-01-12 at 7 24 30 PM" src="https://user-images.githubusercontent.com/8397708/104402747-d5820000-550b-11eb-98d1-3dbe353b481f.png">
