### ISSUE TITLE
when we take a photo of long code it comed up very weird on word soucm,net please fix it and let us make it smaller etc

### ISSUE THREAD

**Issue by fisforfaheem** [carbon-app/carbon#1154]
![image](https://user-images.githubusercontent.com/35878088/103480690-7f200d80-4df7-11eb-89dd-751e54364775.png)
![image](https://user-images.githubusercontent.com/35878088/103480694-88a97580-4df7-11eb-8ac9-63c60b927d8c.png)

**Comment by mfix22** [comment]
Not sure what you mean by this question. Please clarify, and I will reopen.
