### ISSUE TITLE
Why do you need access to the email addresses in my githib account in order to download carbon.sh?

### ISSUE THREAD

**Issue by ReddyKilowatt** [carbon-app/carbon#1156]

**Comment by mfix22** [comment]
Responded in email thread, by copying here for posterity:

> That is just the default permissions used by Firebase to create an account using GitHub credentials. The email is used to associate you with your account.

**Comment by ReddyKilowatt** [comment]
Why do you need to use firebase? No other github projects that I've
downloaded do this

**Comment by mfix22** [comment]
You don't need to have an account to use Carbon. You only need to create a log in if you want to save snippets for later. 

Carbon only support GitHub authentication at the moment.
