### ISSUE TITLE
Carbon does not generate medium link

### ISSUE THREAD

**Issue by GDokmetas** [carbon-app/carbon#1157]
I am using carbon but it does not generate medium link and only does "https://carbon.now.sh/" URL.

**Comment by mfix22** [comment]
If you update any setting, or the code, and then click "Copy Medium.com", it will work 

<img width="951" alt="Screen Shot 2021-01-12 at 7 23 27 PM" src="https://user-images.githubusercontent.com/8397708/104402689-b71c0480-550b-11eb-94a6-46114afdf278.png">
