### ISSUE TITLE
Tweet button not working on Safari

### ISSUE THREAD

**Issue by 11rchitwood** [carbon-app/carbon#1163]
**Describe the bug**
When I click the "Tweet" button on Safari, nothing happens.

**To Reproduce**

1. Go to https://carbon.now.sh on Safari Version 14.0.2 (16610.3.7.1.9)
2. Click on "Tweet" using the default code
3. Nothing happens

**Expected behavior**
Expected tweet dialog to open.

**Info (please complete the following information):**

- OS: macOS
- Browser: Safari
- Carbon URL: https://carbon.now.sh

**Comment by mfix22** [comment]
@11rchitwood Safari unfortunately has made an update to block pop ups like this by default. If you click the button in the location bar to allow popups, it will be resolved for you.

**Comment by 11rchitwood** [comment]
Thanks for the tip!
