### ISSUE TITLE
Autofill language from gist file extension

### ISSUE THREAD

**Issue by 11rchitwood** [carbon-app/carbon#1164]
When I append a gist id to the url, it would nice if the gists file extension was used to autofill the language from the gists file extension.

**Comment by mfix22** [comment]
Hey @11rchitwood that is how the current application works, for all supported languages. 

Is there a specific gist that wasn't working for you? Please post it here so I can test out the behavior.

**Comment by 11rchitwood** [comment]
https://gist.github.com/11rchitwood/009026aedfa31e2fe72a3eb711a498e3

Here it is. Expected R language, but it was left blanks on macOS 11, Safari 14.

**Comment by 11rchitwood** [comment]
Might also be nice to populate alt text or tweet text from the gist text? Just a thought.

**Comment by mfix22** [comment]
Since that file is named `.R`, GitHub treats it as the "Rebol" language (http://www.rebol.com/)

> Might also be nice to populate alt text or tweet text from the gist text? Just a thought.

This is how Carbon currently works. The Twitter Alt text is automatically populated with the code, no matter where it is imported from.
