### ISSUE TITLE
Colorized Scheme code

### ISSUE THREAD

**Issue by JekoTronik** [carbon-app/carbon#1165]
**Is your feature request related to a problem? Please describe.**
I like to code in Guile Scheme programming language. Actually, the best option to share code snippets with Carbon app is to select Lisp. It is enough for simple code snippets.

I would be so glad to see my Scheme code colorized like when I use highlightjs.

**Comment by mfix22** [comment]
Hey @JekoTronik, feel free to use the "Lisp" theme for Scheme code. You can find that option in the Language dropdown.

Example: https://carbon.now.sh/?l=commonlisp
