### ISSUE TITLE
Auto Converting of Symbol >=

### ISSUE THREAD

**Issue by andymcdgeo** [carbon-app/carbon#1167]
**Describe the bug**
When creating snippets in Python that use '>=', it is automatically converted to a > with the underline in line with the symbol as seen in the screenshot below. To work around this, I have to introduce a space between the > and = signs, which is incorrect syntax in Python.

![image](https://user-images.githubusercontent.com/36664410/105828692-5684d100-5fbb-11eb-9018-4432ca90660b.png)

**To Reproduce**

1. Select the language as Python
2. Type: >= 
3. See that it automatically converts to the symbol seen in the screenshot.

**Expected behavior**
The text should not auto convert and be left as >=, which is the correct syntax in Python

**Screenshots**

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: Windows 10
- Browser [e.g. Chrome, Safari, Firefox]: Chrome
- Carbon URL [e.g. carbon.now.sh?bg=pink]:  https://carbon.now.sh/?bg=rgba%28255%2C255%2C255%2C0%29&t=material&wt=boxy&l=python&ds=true&dsyoff=13px&dsblur=21px&wc=true&wa=false&pv=43px&ph=44px&ln=false&fl=1&fm=Fira+Code&fs=14px&lh=152%25&si=false&es=2x&wm=false&code=grade%2520%253D%252073%250A%250Aif%2520grade%2520%253E%253D%252090%253A%250A%2520%2520print%28%27Your%2520Grade%253A%2520A%27%29%250Aelif%2520grade%2520%253E%2520%253D%252080%253A%250A%2520%2520print%28%27Your%2520Grade%253A%2520B%27%29%250Aelif%2520grade%2520%253E%2520%253D%252070%253A%250A%2520%2520print%28%27Your%2520Grade%253A%2520C%27%29%250Aelse%253A%250A%2520%2520print%28%27Fail%27%29%250A%2520%2520

<details>
  <summary>Code snippet</summary>
  <pre>
    grade = 73

    if grade >= 90:
        print('Your Grade: A')
  </pre>
</details>

**Comment by mfix22** [comment]
@andymcdgeo this just a part of the Font you are using. The symbol is called a ligature (if you were curious), and is very much intentional. 

If you don't want this behavior, you can change the font in the settings.
