### ISSUE TITLE
Add languages support for website "carbon.now.sh"

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [carbon-app/carbon#1179]
**Is your feature request related to a problem? Please describe.**
Some people like to use their native language on websites so I suggest adding support for languages on the site.

I would like to do the Arabic translation since I am a native speaker if this suggestion is accepted.

Translators:

- [ ] Arabic translation: [Yazeed AlKhalaf](https://github.com/YazeedAlKhalaf)

If you want to do a language mention me in this issue and will add your name.

So our goals:

1. Decide which method of translation to use
2. Do the translation, people say they want to do it and we mention their names above.

**Comment by mfix22** [comment]
Hey @YazeedAlKhalaf,
While that would be super cool, the core maintainer team does not have the bandwidth to support a feature like this long term. If we grow the contributor team, and have a straightforward solution for making translations, I would be open to reconsider. 

Sorry if this is a disappointment for you.
