### ISSUE TITLE
What version of Fira Code in Carbon?

### ISSUE THREAD

**Issue by vtmx** [carbon-app/carbon#1181]
The current version of carbon is the same as the current version of FiraCode?
I checked the recent FiraCode docs, and saw the number zero current is a slash not a dot.
 
<img src="https://raw.githubusercontent.com/tonsky/FiraCode/master/extras/stylistic_sets.png">
<img src="https://i.imgur.com/Hq0QH53.png">

**Comment by adghayes** [comment]
It looks like the current version is 1.204, which is from 2016. Also the CDN for the font is deprecated. Made a quick PR to update to the latest version.
