### ISSUE TITLE
Auto-adjust width is apparently broken

### ISSUE THREAD

**Issue by Edudjr** [carbon-app/carbon#1183]
**Describe the bug**
Once you disable **auto-adjust width**, It never goes back again. If you try to enable again, it seems like it's worked, however if you update the page, auto-adjust is turned off again.

**To Reproduce**

1. Login with github
2. Create code snippet
3. Disable auto-adjust width
4. Enable auto-adjust width again
5. Reload page or open link in another tab

**Expected behavior**
It should keep the configuration (should keep auto-adjust width turned on)

**Screenshots**
When editing on Carbon page (looks fine):
[
<img width="977" alt="Screenshot 2021-03-04 at 13 35 15" src="https://user-images.githubusercontent.com/6642478/109965043-b83d0700-7cee-11eb-92ef-9740691e7839.png">
](url)

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: MacOS
- Browser [e.g. Chrome, Safari, Firefox]: Opera, Chrome

**Comment by adghayes** [comment]
it looks like this is not confined to the auto-adjust setting, I've replicated it with the Drop Shadow setting as well. It appears that any time a setting is changed back to a default setting, it is omitted from the snippet update request (firebase?). Line of code here:   

https://github.com/carbon-app/carbon/blob/decf263b79af24f6763972987cf2373567ad376e/lib/api.js#L138

Fixing it seems like it would be as simple as removing the `omitBy`. @mfix22 why did you want to reduce the payload size? Maybe I can set something up where it only omits unchanged fields.

**Comment by mfix22** [comment]
Great call @Edudjr! Thanks for submitting this; this is indeed a bug. Let's remove this `omitBy` implementation, and I will make those adjustments on the DB side instead. 

cc @adghayes
