### ISSUE TITLE
few bugs about color

### ISSUE THREAD

**Issue by liesauer** [carbon-app/carbon#1187]
1. have a preset transparent color would be great, we don't need to change `A` value to `0` everytime.
2. color value can not selete all, so if i have a specify hex code or rgba value, i need to delete every single alphabet and then type the value i need.
![image](https://user-images.githubusercontent.com/8676741/110065371-ee8b8c80-7da9-11eb-86a7-985b4330cd9c.png)
3. after changing everything to `0`(transparent), rgb slider doesn't work any more(rgb slider is draggable, the `rgb` value doesn't get update, background has no effect), transparency slider doesn't work any more(transparency slider is clickable, but not draggable, the `a` value doesn't get update, it always be `100`, background has effect)

**Comment by mfix22** [comment]
> have a preset transparent color would be great, we don't need to change A value to 0 everytime.

You can just click the far left of the transparency slider 🙂 

> color value can not selete all, so if i have a specify hex code or rgba value, i need to delete every single alphabet and then type the value i need.

It actually is selectable, but the styles were broken making it seem like it isn't. I will fix this in a PR quick.

> after changing everything to 0(transparent), rgb slider doesn't work any more(rgb slider is draggable, the rgb value doesn't get update, background has no effect), transparency slider doesn't work any more(transparency slider is clickable, but not draggable, the a value doesn't get update, it always be 100, background has effect)

Good call 👍 This looks like an issue with `react-color` (https://github.com/casesandberg/react-color/issues/750, https://github.com/casesandberg/react-color/issues/523) — looks like there might be a work around. Will take a look.
