### ISSUE TITLE
Sign up attempt with 2FA results in firebase error message.

### ISSUE THREAD

**Issue by cod3g3nki** [carbon-app/carbon#1189]
**Describe the bug**

**Sign up** for [Carbon](https://carbon.now.sh/), using a GitHub account and **Google authenticator** as the 2FA option, fails with an error message.

**To Reproduce**

Try to sign up with a two factor authentication method. 

1. Go to 'https://carbon.now.sh/'
2. Click on 'Sign in/up', enter password & OTP (Google auth code)
3. See error: "Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared".

**Expected behavior**
A successful sign up & subsequent sign in.

**Screenshots**
![Screenshot_20210306-001008.jpg](https://user-images.githubusercontent.com/6880680/110164450-35fa3300-7e13-11eb-883b-112f44fdac2f.jpg)

**Info (please complete the following information):**

- OS: Android 10
- Browser: Google Chrome
- Carbon URL: https://carbon.now.sh/

A google search for the error takes to: [firebase / firebase-js-sdk #4256](https://github.com/firebase/firebase-js-sdk/issues/4256).

**Comment by mfix22** [comment]
Hey @cod3g3nki were you trying to log in via an incognito window? Right now there is a Firebase bug preventing login in Incognito browsers.

**Comment by mfix22** [comment]
(Could be a duplicate of https://github.com/carbon-app/carbon/issues/1058)

**Comment by cod3g3nki** [comment]
No, I'm not using incognito mode. Now that you mentioned, I just tried to sign up again with different settings for cookies. Nothing changed. 

![Screenshot_20210307-091728__01.jpg](https://user-images.githubusercontent.com/6880680/110228948-3388fd80-7f27-11eb-9df6-cebf0643f7c1.jpg)

![Screenshot_20210307-091617__01.jpg](https://user-images.githubusercontent.com/6880680/110228955-3b48a200-7f27-11eb-89df-1e211b50dcc0.jpg)

![Screenshot_20210307-091703__01.jpg](https://user-images.githubusercontent.com/6880680/110228957-3edc2900-7f27-11eb-9af2-2ba11fdbfbdc.jpg)

Neither error message not behavior changes.

![Screenshot_20210307-092741.jpg](https://user-images.githubusercontent.com/6880680/110228971-692de680-7f27-11eb-9e95-1788ea6e0dba.jpg)

**Comment by cod3g3nki** [comment]
After further testing, I've found that this bug appears only in Google Chrome and its variants. An attempt to achieve the same via Firefox browser ended up in a successful sign up & subsequent sign in.
