### ISSUE TITLE
Cannot select text in exported SVG

### ISSUE THREAD

**Issue by darahak** [carbon-app/carbon#1198]
**Describe the bug**

I cannot select the text in the SVG exported by Carbon.

**To Reproduce**

1. Write some code in the editor
2. Click on the `Export` dropdown button
3. Select `Download SVG`
4. Open exported SVG in a browser
5. Try to use text selection

**Expected behavior**

I expected to be able to use text selection in the exported SVG. It was one of the advantages compared to exporting to PNG.

Is that intentional?

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: Windows
- Browser [e.g. Chrome, Safari, Firefox]: Chrome, Firefox
- Carbon URL [e.g. carbon.now.sh?bg=pink]: None

**Comment by mfix22** [comment]
This is expected behavior! Sorry if that is not what you want to hear 😞

**Comment by DarkArc** [comment]
@mfix22 is there any reason this couldn't be made an option?

I was looking to share some code in an email, but I still want people to be able to copy and paste text for their reply. Granted there may be issues for plain text email users still...

**Comment by bunnykek** [comment]
Hello, I was also interested in the text selection feature. As the dev said that he has intentionally disabled it so I thought to fix it on my own.
I have made a python script. Just dump all the carbon-generated SVG files in the same folder containing this py file and run it.
A new folder named `modifiedSVG` will be created containing all the SVG with text-selection enabled ; )

```
#py script against carbon.now.sh generated svg files
#to enable text selection
import os
files = os.listdir()
try:
    os.makedirs('modifiedSVG')
except:
    print('directory already created')
for file in files:
    if file.endswith(".svg") and os.path.isfile(file):
        with open(file, "r") as f:
            svgData = f.read()
            svgModified = svgData.replace(
                "user-select: none", "user-select: auto")
            with open(os.path.join("modifiedSVG", file), "w+") as f2:
                f2.write(svgModified)
                print("Modified " + file)
```
