### ISSUE TITLE
Closing Brackets Completion

### ISSUE THREAD

**Issue by danBamikiya** [carbon-app/carbon#1205]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I have to close my brackets (I'm used to VSCode bracket completion).

**Describe the solution you'd like**
I'll like a closing bracket auto completion

I'll like to contribute that feature.

**Comment by mfix22** [comment]
@danBamikiya I think this is a great idea!

**Comment by danBamikiya** [comment]
Just remembered this! I'll work on it now. From what I've observed, I'll be modifying Editor.js and util.js right?

**Comment by mfix22** [comment]
I think i just got it working already, actually. Thanks for the great idea! Feel free to add yourself as a contributor under the "idea" category 💡
