### ISSUE TITLE
Typescript: function return type causes errors in syntax highlighting

### ISSUE THREAD

**Issue by alessandro-calo** [carbon-app/carbon#1206]
**Describe the bug**
In Typescript, adding the return type of a function causes some syntax highlighting errors in the following lines

**To Reproduce**

1. Go to https://carbon.now.sh
2. Paste the following TS code:
```typescript
myFunction() {
    console.log(`${foo}`);
    const bar;
}

myFunction(): void {
    console.log(`${foo}`);
    const a;
}

now everything until the next back-tick is a string
```

3. See the error. Notice that it's not simply about the string: the second `console.log` is highlighted differently as well (i.e. in Monokai, the first line has `console.` white and `log` green. The second one has `console.` green and `log` white.

**Expected behavior**
the second `console.log` statement should be highlighted exactly like the first one.

**Screenshots**
![Example](https://user-images.githubusercontent.com/55374095/114550586-a8580180-9c62-11eb-9ea9-33a7851c8e80.png)

**Info (please complete the following information):**

- OS: macOS
- Browser: Safari
- Carbon URL: [link](https://carbon.now.sh/?bg=rgba%28171%2C+184%2C+195%2C+1%29&t=monokai&wt=none&l=application%2Ftypescript&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=myFunction%28%29%2520%257B%250A%2509console.log%28%2560%2524%257Bfoo%257D%2560%29%253B%250A%2509const%2520bar%253B%250A%257D%250A%250AmyFunction%28%29%253A%2520void%2520%257B%250A%2509console.log%28%2560%2524%257Bfoo%257D%2560%29%253B%250A%2520%2520%2520%2520const%2520a%253B%250A%257D%250A%250Anow%2520everything%2520until%2520the%2520next%2520back-tick%2520is%2520a%2520string )

<details>
  <summary>Code snippet</summary>
  <pre>
  
  </pre>
</details>

**Comment by haru0017** [comment]
Hi,
The above error is true, but I  think it's a non-issue. This is because when you write a function, you probably write something like the following.
```
function myFunction(): void {
	console.log(`${foo}`);
}
```
If you want to write a method instead of a function, you can write the class as shown below to get proper syntax highlighting.
```
class Foo {
  myFunction(): void {
    console.log(`${foo}`);
    const a;
}
```
Using highlight.js in carbon, but highlight.js does syntax highlighting correctly in your code. I couldn't find the cause of the error in my little look at carbon's code, but as I said above, I think it's practically a non-issue.

**Comment by mfix22** [comment]
Unfortunately, if this is an issue, it is due to an upstream issue with this Codemirror theme. I would suggest following up there if this is a pressing concern.

**Comment by alessandro-calo** [comment]
@haru0017 you're exactly right – what I did was copy a method without including the surrounding class. 
@mfix22 yes, I confirmed that the same also happens in Codemirror, so indeed no issue here with Carbon. I will follow up there. Thanks!
