### ISSUE TITLE
How to disable the shortcut Ctrl+Shift+T to start carbon?

### ISSUE THREAD

**Issue by FabianBartl** [carbon-app/carbon#1214]
The shortcut Ctrl+Shift+T is actually meant to open the last closed tab, but when I install carbon as a browser app, it seems that this shortcut is set to open carbon. How can I prevent this without having to uninstall carbon?

- OS: Windows 10
- Browser: Microsoft Edge Beta

**Comment by mfix22** [comment]
Hey @FabianBartl, we don't actually use/set/edit that shortcut, so I am assuming this is an issue with your operating system/browser configurations. 

All shortcuts that Carbon uses can be found here: https://carbon.now.sh/about
