### ISSUE TITLE
Syntax highlighting support for Godot's GDScript language.

### ISSUE THREAD

**Issue by lukehollenback** [carbon-app/carbon#1215]
I just recently tried to use Carbon to create an image of some [GDScript](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html) code. Unfortunately, the syntax highlighting wasn't quite right. It would be awesome to add GDScript as a supported language.

FWIW, I also tried Codye, but unfortunately found that it also does not support GDScript.

**Comment by lukehollenback** [comment]
There appears to exist a [GDScript add-on](https://github.com/highlightjs/highlightjs-gdscript) for `highlight.js`.

**Comment by mfix22** [comment]
@lukehollenback sorry, but we are no longer adding new language support, except for in extenuating circumstances. Hopefully custom themes will work for you. 

If we hear about GDScript more, I will reconsider adding it.

**Comment by hiulit** [comment]
I want GDScript support too :D

**Comment by mfix22** [comment]
Does the Python syntax work for you?

**Comment by hiulit** [comment]
@mfix22 No, it doesn't. GDScript is quite different to Python, actually

**Comment by dsaltares** [comment]
Would love to see support for GDScript. 
Godot Engine is rapidly increasing in popularity. Github, for example, has `.gitignore` presets for Godot/GDScript projects.

**Comment by mfix22** [comment]
> Would love to see support for GDScript. Godot Engine is rapidly increasing in popularity. Github, for example, has `.gitignore` presets for Godot/GDScript projects.

Hey @dsaltares, is there a CodeMirror language mode for GDScript?
