### ISSUE TITLE
alt-text support in html img

### ISSUE THREAD

**Issue by selahaddinh** [carbon-app/carbon#1220]
**Is your feature request related to a problem? Please describe.**
An accessibility feature

**Describe the solution you'd like**
The given code can be written as plain text in the alt-text field

**Describe alternatives you've considered**
It is the only alternative I considered.

**Additional context**
check @katef 's Twitter for more on this... Kate is awesome.

**Comment by mfix22** [comment]
Hey @selahaddinh — we actually do support automatic alt text for platforms like Twitter. If you are embedding a Carbon image yourself, it is your responsibility to include the alt text yourself. This process is outlined under carbon.now.sh/about.
