### ISSUE TITLE
is there a React Component for carbon

### ISSUE THREAD

**Issue by anc95** [carbon-app/carbon#1222]
**Describe the solution you'd like**
When I write document by mdx, and I am lovely to add some pictures created by carbon. but if there will provide a React Component to create Carbon style, will bring great convenience.  Maybe it can be used as bellow
```mdx
import CardBon from 'react-carbon';

<Carbon lng='js' theme={...}>
console.log('I love carbon.now.sh')
</CarBon>
```

**Comment by trangcongthanh** [comment]
I think prismjs/highlightjs will work better with MDX. And IMHO, if you embed code as an image, your mobile user will not happy.

**Comment by mfix22** [comment]
Hey @anc95, unfortunately no, this is not something we want to support. Carbon relies on Codemirror, which is a library you can use very similiarly to how you describe above. 

Check out [react-codemirror2](https://github.com/scniro/react-codemirror2) — should be perfect for your use case 👍
