### ISSUE TITLE
When there in an onClick in the code snippet it won't publish on Medium

### ISSUE THREAD

**Issue by wendydek** [carbon-app/carbon#1226]
**Describe the bug**
If you add an onClick in a code snippet in Carbon and you copy the Medium url the url won't work.

**To Reproduce**

1. Go to https://carbon.now.sh/
2. Create a javascript (react) code snippet that contains an onClick
3. Copy the medium.com link
4. Paste it in medium
5. The link won't parse

**Expected behavior**
The link should parse in medium

**Screenshots**
![Schermafbeelding 2021-06-10 om 09 40 30](https://user-images.githubusercontent.com/6807650/121484893-eefe7980-c9cf-11eb-82ac-3983324719e9.png)

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: macOS
- Browser [e.g. Chrome, Safari, Firefox]: Chrome
- Carbon URL [e.g. carbon.now.sh?bg=pink]: 

<details>
  <summary>Code snippet</summary>
  <pre>
  </pre>
</details>

**Comment by mfix22** [comment]
@wendydek — please share a Carbon URL that recreates this issue, as specified in the issue template.

If you comment above with a link that recreates it, I will reopen this issue. Thanks.
