### ISSUE TITLE
The hex-code and the color chosen in the color field don't change to the color of a different element [Operator/Number/Variable etc] when selected. [In a custom theme]

### ISSUE THREAD

**Issue by Tb-4-4** [carbon-app/carbon#1227]
**Describe the bug**
I was trying to set a custom theme, and while trying to copy the hex code of the color I've set for 'Definition' to make it 'Keyword's' color as well, the color and the hex code shown didn't match the actual color the element had. That was because I had clicked on 'Background' before and all the hex codes and colors shown was that of the background-color.

[I don't know if _element_ is the right terminology here]

**To Reproduce**

1. Go to https://carbon.now.sh/
2. Click on the drop-down menu that has 'Seti' selected, and click on 'Create +'
3. Click through all the elements that you can choose a color for, you'll be able to see that the color & the hex-code shown don't match the actual color that's been set for the specific element. 

**Expected behavior**
I expected it to show the correct hex code and the color on the color field

**Screenshots**

![poiuytrewq](https://user-images.githubusercontent.com/68370357/121798573-c59a5380-cc44-11eb-99d8-6746bda8129d.gif)

[The weird streaks/discoloration in the color field is a processing issue from my end]

**Info (please complete the following information):**

- Windows
- Chrome
- https://carbon.now.sh/?bg=rgba%28171%2C+184%2C+195%2C+1%29&t=theme%3A381a9q8396x&wt=none&l=auto&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=false&pv=56px&ph=56px&ln=false&fl=1&fm=Poppins-SemiBold&fs=14px&lh=188%25&si=false&es=2x&wm=false&code=

**Comment by mfix22** [comment]
Thanks @Tb-4-4 for this excellent bug report! Just pushed up the fix, and the change should go out later today. 

Cheers!

**Comment by Tb-4-4** [comment]
No problem, thank you!
