### ISSUE TITLE
Social Media image dimension presets

### ISSUE THREAD

**Issue by 5AbhishekSaxena** [carbon-app/carbon#1228]
**Is your feature request related to a problem? Please describe.**
Add common social media image dimensions.

It is very common these days that people share code on social media platforms like Twitter, Instagram, etc, and each platform has its own post dimensions to avoid auto-cropping. 

This feature would be really helpful and help the users to download the image using the defined dimensions instead of doing basic editing on GIMP/Photoshop to update the canvas size for different social media platforms.

**Describe the solution you'd like**
A dimensions tab for the canvas with some preset for social media, so users can manually enter the dimensions or use the preset.

**Describe alternatives you've considered**
Manual canvas size update to make the image fit for social media platforms using photo editing tools like GIMP.

**Additional context**
None

**Comment by mfix22** [comment]
Hey @5AbhishekSaxena, we actually do support square images, as shown here: https://github.com/carbon-app/carbon/issues/1147#issuecomment-748376703

For other ratio, please drag the edge of the window to set the size you desire. Thanks!
