### ISSUE TITLE
Unable to render code snippet on Medium

### ISSUE THREAD

**Issue by samhita-alla** [carbon-app/carbon#1230]
**Describe the bug**
I'm unable to render one specific code snippet on medium. It works when the function name is not "coalesce"

**To Reproduce**

https://carbon.now.sh/?bg=rgba%28171%2C184%2C195%2C0%29&t=blackboard&wt=sharp&l=python&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=0px&ph=0px&ln=false&fl=0&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=%2540task%28limits%253DResources%28mem%253D%2522600Mi%2522%29%29%250Adef%2520coalesce%28%250A%2520%2520%2520%2520augmented_list%253A%2520typing.List%255Btyping.List%255BFlyteFile%255D%255D%252C%250A%29%2520-%253E%2520typing.List%255BFlyteFile%255D%253A%250A%2520%2520%2520%2520return%2520list%28itertools.chain.from_iterable%28augmented_list%29%29: try rendering this on medium.

**Expected behavior**
Rendering should work.

**Screenshots**
<img width="1098" alt="Screenshot 2021-07-15 at 6 58 01 PM" src="https://user-images.githubusercontent.com/27777173/125796902-2cc2221c-b52c-42a9-bdbb-a6cd6851ddea.png">

**Info (please complete the following information):**

- OS: macOS
- Browser: Firefox
- Carbon URL: https://carbon.now.sh/?bg=rgba%28171%2C184%2C195%2C0%29&t=blackboard&wt=sharp&l=python&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=0px&ph=0px&ln=false&fl=0&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=%2540task%28limits%253DResources%28mem%253D%2522600Mi%2522%29%29%250Adef%2520coalesce%28%250A%2520%2520%2520%2520augmented_list%253A%2520typing.List%255Btyping.List%255BFlyteFile%255D%255D%252C%250A%29%2520-%253E%2520typing.List%255BFlyteFile%255D%253A%250A%2520%2520%2520%2520return%2520list%28itertools.chain.from_iterable%28augmented_list%29%29

**Comment by mfix22** [comment]
Wow! This is a crazy bug, @samhita-alla. This looks like it is a limitation of the Medium embed platform. Fixing this bug requires a change to Medium, so could you please send this to Medium support?

Thanks for posting.
