### ISSUE TITLE
https://carbon.now.sh/ - license for exported images

### ISSUE THREAD

**Issue by illia-romanenko** [carbon-app/carbon#1231]
Hi 👋,

first of all thanks for working on this project and providing an easy way to create beautiful code snippets!

I wanted to check what limitations (if any) for using exported images from https://carbon.now.sh/

I looked at terms:

> Provided that you are eligible to use the Site, you are granted a limited license to access and use the Site and to download or print a copy of any portion of the Content to which you have properly gained access solely **for your personal, non-commercial use**. We reserve all rights not expressly granted to you in and to the Site, the Content and the Marks.

Does this mean that exported images can't be used in commercial projects (private GitHub projects, internal documentation, etc...)? If so, are any guidelines available for use in commercial projects?

Thanks in advance,
Illia

**Comment by mfix22** [comment]
Sorry if the terms are unclear. You have full creative control with the images you generate using Carbon.

**Comment by mfix22** [comment]
Really appreciate this thoughtful question! 🙏

**Comment by lastmjs** [comment]
Wondering the same thing, happy to have found this answer!
