### ISSUE TITLE
Coloring Does Not Support Regular Expression Operation?

### ISSUE THREAD

**Issue by Williams-Ren** [carbon-app/carbon#1232]
It seems that it does not support coloring the regular expression in any language? Here is my code in python:

```python
import re

re.match(r'[\s\S]+\([0-9]{1,2}\.?[0-9]{0,2}-?[0-9]{0,2}\.?[0-9]{0,2}\)[\s\S]*Effective:[\s\S]*', str)
```

And here is how it looks:

![image](https://user-images.githubusercontent.com/45218090/127190252-f1cb9a58-14f1-4c77-8618-2ef2b8bad909.png)

Here is what it supposed to look like in Pycharm theme Material NightowlL:

![image](https://user-images.githubusercontent.com/45218090/127190492-6c15c840-5485-4047-a221-e601b66912b1.png)

I tried with other langugage or theme in Carbon but none of them work.

Is it possible for Carbon to support coloring regular expression in the future?

**Comment by mfix22** [comment]
Hey @Williams-Ren — the coloring for each these is up to the specific Codemirror theme authors. Please take it up with the maintainers of those packages, of push a PR with a fix for this yourself. Thanks! 🙂
