### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by FrenchMajesty** [carbon-app/carbon#1233]
**Describe the bug**
The "Editor" settings that I select do not persist. If I close Carbon and re-open, the customized options are gone and I would have to re-select them again.

**To Reproduce**

1. Go to Settings
2. Click on Editor
3. Toggle "Line Number" to on
4. Export a random image screenshot (which has line numbers)
5. Close/Reopen Carbon
6. Line numbers not showing

**Expected behavior**
The app should be remember a user's preferences so they aren't forced to re-select them every time. This could also carry over to language used, theme, etc... 

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: macOS
- Browser [e.g. Chrome, Safari, Firefox]: Chrome

**Comment by mfix22** [comment]
Hey @FrenchMajesty — i was not able to reproduce the issue using the steps you shared. This is currently working as expected. If you could share a video of the issue being reproduced, I'll look again. Thanks.
