### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by CandyKIng1991** [carbon-app/carbon#1247]
please see this blog, i think i cannot  understand the office how  to use  in IDEA?

https://www.cnblogs.com/liuyangfirst/p/15166673.html

**Comment by mfix22** [comment]
Hi, I'm not sure what that blog post is asking you to do, sorry.

**Comment by CandyKIng1991** [comment]
There are no screenshots and articles on the official website on how to use the software.
When installing in China, programmers found that clicking can not open the image generation page.
Write articles to support this plug-in.

**Comment by CandyKIng1991** [comment]
When you first install, you can't find where to operate the software anyway.
Neither the official website nor here of idea describes how to find the operation location when combining idea.
Personally, I think this is a good plug-in. I hope more people can use it, so I wrote a blog.
