### ISSUE TITLE
PNGs aren't exporting correctly on FireFox

### ISSUE THREAD

**Issue by Soft-Bred** [carbon-app/carbon#1256]
**Describe the bug**
Image export doesn't treat plank spaces well. 

Edit: On FireFox, the Carbon site shows the text in correct monospace spacing, while in chrome & Brave it is shown in normal spacing and not in a monospace spacing.

Edit 2: On brave they export just fine, seems to be a firefox problem

**To Reproduce**
Steps to reproduce the behaviour:

1. Paste the following into carbon snippet:
```
// [USER CHROME]

:root {

 // ╔════════════════════════════╦══════════════════════════════[─]═[□]═[×]═╗
 // ║ Primary Colours - Root     ║ That Special Pop Of Colour               ║
 // ╚════════════════════════════╩══════════════════════════════════════════╝

 // Changes the colour of URL/Hypertext in popouts.
     --lwt-popup-brighttext-url-color: #C5B3FD !important;
        
 // Changes the colour of the address bar outline when seleced.
     --focus-outline-color: #C5B3FD !important;

}
```
2. Export as png
3. Open png and see it is not as seen on site.

**Expected behaviour**
The image looks like what is represented on site.

**Screenshots**
What should happen (taken with screenshot tool):
![What Should Happen](https://user-images.githubusercontent.com/60551230/133918162-f25b5756-5b84-4fc2-ba71-4a3016f9d8c7.png)

What is exported:
![carbon](https://user-images.githubusercontent.com/60551230/133918180-b03d9a56-4120-4231-aea6-8f145b999192.png)

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: Windows
- Browser [e.g. Chrome, Safari, Firefox]: Firefox
- Carbon URL [e.g. carbon.now.sh?bg=pink]: https://carbon.now.sh/uenbd3BQuwRbKWf0luJB

<details>
  <summary>Code snippet</summary>
  <pre>
  
  </pre>
</details>

**Comment by Knorrke** [comment]
I'm not one of the maintainers, so will have to wait if the PR does get merged 😅 But for now you can change the font in the settings -> Editor -> Font to Fira Code. That one worked best for me
![grafik](https://user-images.githubusercontent.com/11499926/137589064-8d6c2d6f-60f3-4529-b361-1bb4ac87f5b0.png)
