### ISSUE TITLE
Unable to turn off line wrapping using https://carbon.now.sh/

### ISSUE THREAD

**Issue by oconnelltoby** [carbon-app/carbon#1260]
**Is your feature request related to a problem? Please describe.**
I am using medium to try and present code snippets related to articles I am writing and it is very hard to understand code that is excessively wrapped on mobile screens.

This is related to https://github.com/carbon-app/carbon/issues/1259

**Describe the solution you'd like**
I would like to be able to turn line-wrapping off entirely and side-scroll to view code.

**Describe alternatives you've considered**
Currently I am using github gists which have this feature built in

**Additional context**
<img src="https://user-images.githubusercontent.com/17937840/134825871-a5285528-71e8-4073-a26c-e99d66091de8.jpeg" width="360" height="780">

**Comment by mfix22** [comment]
@oconnelltoby please record the issues you are facing in #1259
