### ISSUE TITLE
Support for BASIC programming language.

### ISSUE THREAD

**Issue by adityamwagh** [carbon-app/carbon#1263]
**Is your feature request related to a problem? Please describe.**
My professor asked us to do the Mechatronics programming assignments in the BASIC programming language. (Don’t ask me why, I guess he’s living in the 90s lol). I want to present it well, so that’s why I need this option to beautifully portray my BASIC Code.

**Describe the solution you'd like**
An option to select the BASIC Programming Language in the drop down.

**Describe alternatives you've considered**
None of them have support for BASIC.  Snippet Shot, etc.

**Comment by mfix22** [comment]
Try the VB.net language mode 🙂
