### ISSUE TITLE
Theme is not recognized as an option when setting query parameters.

### ISSUE THREAD

**Issue by adam-arold** [carbon-app/carbon#1268]
I'm trying to call Carbon with this URL:

```
https://carbon.now.sh/?&ln=false&code=println%28%22hello%22%29&bg=rgba%28171%2C+184%2C+195%2C+1%29&fl=1&pv=56px&fm=Inconsolata&wa=true&wc=true&l=auto&fs=14px&ds=true&dsblur=68px&dsyoff=20px&t=Monokai&wm=false&ph=56px&lh=133%25&wt=none&
```

This should use the `Monokai` theme, but what I see is the `Seti` theme.

If I try to set it manually it works, but the GET parameter doesn't.

I tried this form Chrome, Edge and Firefox.

**Comment by mfix22** [comment]
https://carbon.now.sh/?t=monokai 👍
