### ISSUE TITLE
Allow transparent backgrounds (behind editor)

### ISSUE THREAD

**Issue by SiddharthShyniben** [carbon-app/carbon#1271]
**Is your feature request related to a problem? Please describe.**
Having a transparent background will really help when integrating the photo in another bigger photo.

**Describe the solution you'd like**
Allow setting the background color to be transparent

**Describe alternatives you've considered**
Using photo editors to manually change it

**Additional context**
By background I mean the colored background behind the editor

**Comment by Isaiah-Hamilton** [comment]
@SiddharthShyniben Well, all you have to do is just go to the background color sector and change the Alpha value to 0. just like in the image below. Now your background color will be transparent. 
<img width="1280" alt="Screen Shot 2021-10-29 at 4 29 40 PM" src="https://user-images.githubusercontent.com/70828596/139498273-8a0e7d97-38f0-4e14-ac84-8045453d773a.png">

**Comment by SiddharthShyniben** [comment]
Ok nice! thanks
