### ISSUE TITLE
Width parameter is ignored when calling Carbon with query parameters.

### ISSUE THREAD

**Issue by adam-arold** [carbon-app/carbon#1272]
I'm trying to call Carbon with this URL:

I'm trying to call this url: `https://carbon.now.sh/` with a `width` parameter, but it doesn't recognize it for some reason. I looked at the source code and I can see that it doesn't look at `width` at all. What's the reason for this limitation?

**Comment by mfix22** [comment]
Thanks for the idea @adam-arold. Just added this as an option: you will be able to use the `width` param after our next release.

**Comment by adam-arold** [comment]
This is great, thanks!
