### ISSUE TITLE
Remainder and next character ignored if no spaces are set in javascript

### ISSUE THREAD

**Issue by Rumyra** [carbon-app/carbon#1275]
**Describe the bug**

I just 'carboned' this code: `let theta = (i%360)*angleSize;` and the result was `let theta = (i60)*angleSize;` the `%` was stripped as was the following character

**To Reproduce**

1. Go to '…'
2. Click on '…'
3. See error

**Expected behavior**

I would expect this not to be stripped - I mean I'm happy for you to come back and say 'put a space in it' but I wasn't expecting that.

If there is a fix, let me know - I'm happy to help 👍 

**Screenshots**

My text editor:

<img width="325" alt="Screenshot 2021-10-22 at 20 56 06" src="https://user-images.githubusercontent.com/302715/138515381-2ff91acb-6b46-44ee-98a7-567ca630402a.png">

Carbon:

<img width="309" alt="Screenshot 2021-10-22 at 20 56 40" src="https://user-images.githubusercontent.com/302715/138515415-7e96bf95-ab9c-4486-9883-5dac2c25fc69.png">

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: macOS Big Sur
- Browser [e.g. Chrome, Safari, Firefox]: Chrome
- Carbon URL [e.g. carbon.now.sh?bg=pink]: https://carbon.now.sh/?bg=rgba%28216%2C211%2C226%2C1%29&t=one-dark&wt=bw&l=javascript&ds=true&dsyoff=18px&dsblur=45px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Space+Mono&fs=15px&lh=133%25&si=false&es=2x&wm=false&code=function%2520createSpiralCoords%28x%252C%2520y%252C%2520itemCount%2520%253D%252060%252C%2520radiusInc%2520%253D%252010%252C%2520angleSize%2520%253D%252010%29%2520%257B%250A%250A%2520%2520let%2520coords%2520%253D%2520new%2520Map%28%29%253B%250A%250A%2520%2520for%2520%28let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520itemCount%253B%2520i%252B%252B%29%2520%257B%250A%250A%2520%2520%2520%2520%252F%252F%2520set%2520angle%250A%2520%2520%2520%2520let%2520theta%2520%253D%2520%28i60%29*angleSize%253B%250A%2520%2520%2520%2520%252F%252F%2520convert%2520to%2520radians%250A%2520%2520%2520%2520theta%2520%253D%2520theta*%28Math.PI%252F180%29%253B%250A%250A%2520%2520%2520%2520%252F%252F%2520get%2520radius%250A%2520%2520%2520%2520const%2520r%2520%253D%2520i*radiusInc%253B%250A%250A%2520%2520%2520%2520const%2520cx%2520%253D%2520%28r%2520*%2520Math.cos%28theta%29%29%2520%252B%2520x%253B%250A%2520%2520%2520%2520const%2520cy%2520%253D%2520%28r%2520*%2520Math.sin%28theta%29%29%2520%252B%2520y%253B%250A%250A%2520%2520%2520%2520coords.set%28i%252C%2520%257Bx%253A%2520cx%252C%2520y%253A%2520cy%252C%2520angle%253A%2520theta%252C%2520radius%253A%2520r%257D%29%250A%2520%2520%257D%250A%2520%2520return%2520coords%253B%250A%250A%257D%253B

This was the whole function I sent to carbon from Sublime Text

<details>
  <summary>Code snippet</summary>
  <pre>
function createSpiralCoords(x, y, itemCount = 60, radiusInc = 10, angleSize = 10) {

	let coords = new Map();

	for (let i = 0; i < itemCount; i++) {

		// set angle
		let theta = (i%360)*angleSize;
		// convert to radians
		theta = theta*(Math.PI/180);

		// get radius
		const r = i*radiusInc;

		const cx = (r * Math.cos(theta)) + x;
		const cy = (r * Math.sin(theta)) + y;
		
		coords.set(i, {x: cx, y: cy, angle: theta, radius: r})
	}
	return coords;

};
  </pre>
</details>

**Comment by mfix22** [comment]
Hey @Rumyra,
I am a little confused by the issue 🙂 I just went to the link above, added a `%` in the spot you said it was missing, and then clicked export and got this image: 
![carbon](https://user-images.githubusercontent.com/8397708/140675887-8a061d96-8539-45ce-901b-c9f985054ea1.png)

Here is a link to the source: https://carbon.now.sh/?bg=rgba%28216%2C211%2C226%2C1%29&t=one-dark&wt=bw&l=javascript&ds=true&dsyoff=18px&dsblur=45px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Space+Mono&fs=15px&lh=133%25&si=false&es=2x&wm=false&code=function%2520createSpiralCoords%28x%252C%2520y%252C%2520itemCount%2520%253D%252060%252C%2520radiusInc%2520%253D%252010%252C%2520angleSize%2520%253D%252010%29%2520%257B%250A%250A%2520%2520let%2520coords%2520%253D%2520new%2520Map%28%29%253B%250A%250A%2520%2520for%2520%28let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520itemCount%253B%2520i%252B%252B%29%2520%257B%250A%250A%2520%2520%2520%2520%252F%252F%2520set%2520angle%250A%2520%2520%2520%2520let%2520theta%2520%253D%2520%28i%252560%29*angleSize%253B%250A%2520%2520%2520%2520%252F%252F%2520convert%2520to%2520radians%250A%2520%2520%2520%2520theta%2520%253D%2520theta*%28Math.PI%252F180%29%253B%250A%250A%2520%2520%2520%2520%252F%252F%2520get%2520radius%250A%2520%2520%2520%2520const%2520r%2520%253D%2520i*radiusInc%253B%250A%250A%2520%2520%2520%2520const%2520cx%2520%253D%2520%28r%2520*%2520Math.cos%28theta%29%29%2520%252B%2520x%253B%250A%2520%2520%2520%2520const%2520cy%2520%253D%2520%28r%2520*%2520Math.sin%28theta%29%29%2520%252B%2520y%253B%250A%250A%2520%2520%2520%2520coords.set%28i%252C%2520%257Bx%253A%2520cx%252C%2520y%253A%2520cy%252C%2520angle%253A%2520theta%252C%2520radius%253A%2520r%257D%29%250A%2520%2520%257D%250A%2520%2520return%2520coords%253B%250A%250A%257D%253B

**Comment by Rumyra** [comment]
So something is stripping that `%` from Sublime to the browser - any ideas what?
