### ISSUE TITLE
Cascadia Code

### ISSUE THREAD

**Issue by jnm2** [carbon-app/carbon#1276]
There's a new open-source font that is now the default in Windows Terminal and Visual Studio: https://github.com/microsoft/cascadia-code

Would you be open to adding Cascadia Code and Cascadia Mono (the non-ligature version which I prefer) to the font list?

I'd be happy to try to figure out how to contribute the change.

**Comment by mfix22** [comment]
@jnm2 typically aren't accepting new fonts to Carbon anymore, but this seems like a notable exceptions. 

I would be willing to accept a PR that adds this font. Are there any other fonts on Carbon you think this could replace? What was the previous default for Windows?

**Comment by jnm2** [comment]
> Are there any other fonts on Carbon you think this could replace? What was the previous default for Windows?

I don't know the answer to the first question. The previous default in both Windows consoles and Visual Studio and VS Code was Consolas. Before that, it was Courier New in Visual Studio and (I think) a raster font called Terminal in Windows consoles.

**Comment by jnm2** [comment]
PR is up: https://github.com/carbon-app/carbon/pull/1278

**Comment by jnm2** [comment]
This change is now live at https://carbon.now.sh! https://github.com/carbon-app/carbon/releases/tag/4.9.0
