### ISSUE TITLE
Support CMake language

### ISSUE THREAD

**Issue by joaquin-herrero** [carbon-app/carbon#1281]
CMake is widely used on C++ projects.

It would be great to have Carbon supporting CMake language.

Here it is the syntax definition if it can help:
[CMake syntax](https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#syntax)

Thanks

**Comment by mfix22** [comment]
You can use the C++ or C modes: https://carbon.now.sh/?l=c-like
