### ISSUE TITLE
why not change an icon

### ISSUE THREAD

**Issue by oo-long** [carbon-app/carbon#1283]
**Describe the change**
A clear and concise description of your proposal.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]:
- Browser [e.g. Chrome, Safari, Firefox]:

<details>
  <summary>Code snippet</summary>
  <pre>
  
  </pre>
</details>

**Comment by mfix22** [comment]
Not sure!
