### ISSUE TITLE
Highlight {roxygen2} comments in R code

### ISSUE THREAD

**Issue by wurli** [carbon-app/carbon#1284]
When writing R code it would be great to have {roxygen2} comments highlighted similarly to how it's done in RStudio. This isn't part of R's official syntax, but as most R users, and particularly package developers, now use roxygen and RStudio, I think it would make sense to include it in Carbon. Here's an example (using the theme Cobalt):

![highlighting-rstudio](https://user-images.githubusercontent.com/17475731/142903565-d926c5db-c324-4b87-9b25-d92745ae750f.png)

![highlighting-cobalt](https://user-images.githubusercontent.com/17475731/142903583-cdb3a952-9956-402c-971f-4beb557698a3.png)

Thanks for the hard work on Carbon, it's a lovely tool!

**Comment by mfix22** [comment]
Hey @wurli this change would have to be made in the Codemirror R mode package. 

Please open an issue there, and consider fixing the issue upstream 🙂
