### ISSUE TITLE
Allow hiding window decorations

### ISSUE THREAD

**Issue by f1reflyyyylmao** [carbon-app/carbon#1288]
**Is your feature request related to a problem? Please describe.**
It'd be nice if the site would provide the means to remove the window decorations. It's not hard to select and remove the html node, but I'd rather not do it every time.

**Describe the solution you'd like**
A fourth option alongside the others where I can choose "none"

**Comment by rkoleci** [comment]
Can you assign this to me ?

**Comment by mfix22** [comment]
This can be done in the Settings menu:

<img width="971" alt="Screen Shot 2021-12-12 at 2 12 10 PM" src="https://user-images.githubusercontent.com/8397708/145731604-f0550e92-a726-48df-bf98-118aa708a7e4.png">

https://carbon.now.sh/?wc=false
