### ISSUE TITLE
Code highlight doesn't support PHP Attributes

### ISSUE THREAD

**Issue by brzuchal** [carbon-app/carbon#1289]
**Describe the bug**
Code highlight doesn't support PHP Attributes

**To Reproduce**

1. Go to [example](https://carbon.now.sh/?bg=rgba%28248%2C231%2C28%2C1%29&t=blackboard&wt=none&l=text%2Fx-php&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=true&fl=1&fm=Fira+Code&fs=14px&lh=152%25&si=false&es=2x&wm=false&code=%253C%253Fphp%250A%2523%255BFoo%255D%250Aclass%2520Bar%2520%257B%250A%2520%2520%2523%255B%250A%2520%2520%2509Baz%28id%253A%2520123%29%250A%2520%2520%255D%250A%2520%2520public%2520function%2520baz%28%29%2520%257B%257D%250A%257D)
2. See the highlight of the first attribute is dimmed like a comment while it's no longer comment in PHP, the second attribute on method is multi-line and here the closing parens are a different colour than the opening and the attribute body is different than on the first attribute on top of the class.

**Expected behavior**

**Screenshots**
[](https://carbon.now.sh/8d82e6bc-7c71-4cd6-abb1-4225b24493e5)

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]:
- Browser [e.g. Chrome, Safari, Firefox]:
- Carbon URL [e.g. carbon.now.sh?bg=pink]: https://carbon.now.sh/?bg=rgba%28248%2C231%2C28%2C1%29&t=blackboard&wt=none&l=text%2Fx-php&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=true&fl=1&fm=Fira+Code&fs=14px&lh=152%25&si=false&es=2x&wm=false&code=%253C%253Fphp%250A%2523%255BFoo%255D%250Aclass%2520Bar%2520%257B%250A%2520%2520%2523%255B%250A%2520%2520%2509Baz%28id%253A%2520123%29%250A%2520%2520%255D%250A%2520%2520public%2520function%2520baz%28%29%2520%257B%257D%250A%257D

<details>
  <summary>Code snippet</summary>

```php
<?php
#[Foo]
class Bar {
  #[
  	Baz(id: 123)
  ]
  public function baz() {}
}
```

</details>

**Comment by mfix22** [comment]
@brzuchal please submit this issue upstream to the Codemirror PHP mode.
