### ISSUE TITLE
Text overlap issue while generating image from block (inconsistent wrapping)

### ISSUE THREAD

**Issue by BRO3886** [carbon-app/carbon#1291]
**Describe the bug**
When I copy the image to clipboard, the line-break for wrapping is different, so, while it looks fine on the website, the image comes out weird

**To Reproduce**
1. Copy the following code:
```bash
$ go build -gcflags="-m -l" -o main
# allocations
./main.go:11:2: moved to heap: x
./main.go:7:13: ... argument does not escape
./main.go:7:17: *n / 2 escapes to heap

$ cat -b main.go 
     1	package main

     2	import "fmt"

     3	func main() {
     4		n := answer()
     5		fmt.Println(*n / 2)
     6	}

     7	func answer() *int {
     8		x := 42
     9		return &x
    10	}
```
2. Paste on the website (Carbon)
3. Click copy to clipboard > as image

**Expected behavior**
Both the copied image and the editor output should look same, but they don't. The image has some text overlapping

**Screenshots**
![image](https://user-images.githubusercontent.com/39856034/145532458-6e0956da-ac69-4d57-b997-c28c1006b9e5.png)
"Argument does not escape" is in one line

![image](https://user-images.githubusercontent.com/39856034/145532524-646d3261-1fad-44cb-8d6a-1d1d4fc31030.png)
"Argument does not escape" gets wrapped and overlaps with next line

**Info (please complete the following information):**

- OS: Linux
- Browser: Edge-latest
- [Carbon URL](https://carbon.now.sh/rz3iRYCZKo1krN7Pk2x3)

<details>
  <summary>Code snippet</summary>
  <pre>
$ go build -gcflags="-m -l" -o main
# allocations
./main.go:11:2: moved to heap: x
./main.go:7:13: ... argument does not escape
./main.go:7:17: *n / 2 escapes to heap

$ cat -b main.go 
     1	package main

     2	import "fmt"

     3	func main() {
     4		n := answer()
     5		fmt.Println(*n / 2)
     6	}

     7	func answer() *int {
     8		x := 42
     9		return &x
    10	}
  </pre>
</details>

**Comment by mfix22** [comment]
I'm sure this is an operating system specific issue. There are often weird issues in Linux, especially when using edge browsers

I will leave this open for other people to consider a fix, but this is not something the core team will fix ourselves. 

Thanks for posting.
