### ISSUE TITLE
Upgrade escape-goat to latest

### ISSUE THREAD

**Issue by mfix22** [carbon-app/carbon#1295]

**Comment by mannyluvstacos** [comment]
Hi @mfix22!

I opened PR #1304 and it requires some additional review from someone for a first-time contributor to the project.

Additionally, I was running into an issue with one of the integration tests related to taking a screenshot and would love your guidance when you have a moment!

If there are any additional steps I need to adhere to, I'd be more than happy to do so!

I'm looking forward to contributing to additional "good first issues" as I am new to this project and want to help out!

**Comment by mfix22** [comment]
@mannyluvstacos go ahead and take this issue. I think you just need to upgrade and fix the imports correctly. If you run into unrelated CI issues, you can ignore them.

**Comment by MannyPamintuanAtCare** [comment]
> @mannyluvstacos go ahead and take this issue. I think you just need to upgrade and fix the imports correctly. If you run into unrelated CI issues, you can ignore them.

Hey there, @mfix22 !
Sounds good! I'll take this issue 👍🏽

**Comment by mfix22** [comment]
@mannyluvstacos's PR already fixed this issue, @MannyPamintuanAtCare. Thanks for offering! Thanks @mannyluvstacos for submitting the fix.

**Comment by mfix22** [comment]
@MannyPamintuanAtCare if you are interested in another issue, all of these are still available: https://github.com/carbon-app/carbon/labels/good%20first%20issue
