### ISSUE TITLE
Upgrade ESLint to version 8

### ISSUE THREAD

**Issue by mfix22** [carbon-app/carbon#1297]
https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0

**Comment by github4maninder** [comment]
Hi, I checked the package.json, should I just update the 

    "eslint": "^7.32.0",                                -- to "^8.0.0"
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-react": "^7.27.1",
    "eslint-plugin-react-hooks": "^4.3.0",

should I just update this file or  anyother files or lines in package.json
