### ISSUE TITLE
Upgrade next-pwa to latest

### ISSUE THREAD

**Issue by mfix22** [carbon-app/carbon#1298]
https://github.com/shadowwalker/next-pwa/blob/master/CHANGELOG.md

- [ ] Confirm that the Lighthouse audit still returns a perfect score for the PWA test

**Comment by alceil** [comment]
I would like to take up this issue. Can you brief me about the issue a Lil bit and point me out to resources to get started! @mfix22

**Comment by alceil** [comment]
I have raised a pr. Please have a look @mfix22
