### ISSUE TITLE
Add additional title/notes/copyright message

### ISSUE THREAD

**Issue by maifeeulasad** [carbon-app/carbon#1303]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add some title as a window title maybe or copyright message or some other message at the bottom. Like:
##### Title:
![asdasd2](https://user-images.githubusercontent.com/29339330/146548723-3c71409b-9076-4d81-8721-bb0805de2113.png)
##### Copyright or additional message:
![asdasd1](https://user-images.githubusercontent.com/29339330/146548710-05d655fe-016d-4987-affc-7a2e2e1a3d71.png)

**Describe alternatives you've considered**
Editing, lol.

**Additional context**
Maybe I can develop this feature.

**Comment by mfix22** [comment]
Please use an addition image editors to add copyright information. If you want to add the Carbon copyright/watermark, you can do so in the settings men

<img width="955" alt="Screen Shot 2022-01-24 at 7 57 58 PM" src="https://user-images.githubusercontent.com/8397708/150908315-abfa2027-b005-4c3f-92c7-5c23052e1274.png">
