### ISSUE TITLE
Support Tile and description area, where different styling and font can be applied

### ISSUE THREAD

**Issue by marafiq** [carbon-app/carbon#1312]
**Is your feature request related to a problem? Please describe.**
Title & Description support in different styling than the code itself. So when folks click on the picture, they have the full context of the code. 

**Describe the solution you'd like**
Support a Title & Description area limited to x characters; the user should set font & color. 

**Describe alternatives you've considered**
Alternative would be to upload the background along with your text on it.

**Additional context**
Description area; the user can position on the left or right side of the code, but this is a wishlist.

**Comment by mfix22** [comment]
Hey @marafiq, not sure exactly what you mean by this idea, but it sounds like some complicated editing. For more complex editing, please export your image into editing software, like Figma, and make tweaks from there. We need to balance power with ease of use 🙂
