### ISSUE TITLE
Support 3rd party highlightjs packages

### ISSUE THREAD

**Issue by mbtools** [carbon-app/carbon#1314]
**Is your feature request related to a problem? Please describe.**
The list of languages is limited to the core languages supported by hightlight.js. However, there are many 3rd party packages for other languages available (see https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md).

**Describe the solution you'd like**
Add 3rd party packages to carbon (related https://github.com/carbon-app/carbon/issues/1299).

**Describe alternatives you've considered**
Provide an option to easily do it in a fork.

**Comment by mfix22** [comment]
@mbtools how would you suggest adding Highlight.js modes?

**Comment by mbtools** [comment]
The integration is described in https://github.com/highlightjs/highlight.js/blob/main/extra/3RD_PARTY_QUICK_START.md

If I understand it right, you clone the 3rd party language repos you would like into the `extra` folder of your highlightjs. And then run the `build.js` that's included in highlightjs (Sorry, I'm not a build expert).

**Comment by mfix22** [comment]
@mbtools oh! Are you suggesting this for people that are cloning Carbon? We already have a custom modes folder, and there is a custom highlight.js loader hook that users can extend.

**Comment by mbtools** [comment]
thanks. i will give this a try when i find the time
