### ISSUE TITLE
Use Next.js recommended lint config

### ISSUE THREAD

**Issue by mfix22** [carbon-app/carbon#1321]
See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config

- [x] Ensure `yarn lint` still passes
- [x] Ensure `plugin:jsx-a11y/recommended` still works
- [x] Ensure `import` ESlint plugin still works
- [x] Ensure config is simpler with the Next.js lint

**Comment by CheRayLiu** [comment]
Hi @mfix22 could I get assigned to this?

**Comment by mfix22** [comment]
> Hi @mfix22 could I get assigned to this?

@CheRayLiu anyone can submit PRs to fix any issue, with no assignment necessary. I will accept the first contribution that appropriately/best solves the issue.

**Comment by mfix22** [comment]
Looks like #1322 already starts the solution for this issue, but is not entirely complete yet.
