### ISSUE TITLE
Unable to access code snippets

### ISSUE THREAD

**Issue by KrishnB** [carbon-app/carbon#1327]
**Describe the change**
For the past couple of days, I'm unable to access code snippets on the carbon site.

Error: Application error: a client-side exception has occurred (see the browser console for more information).

**Screenshots**
![Screenshot 2022-02-02 at 11 48 53 AM](https://user-images.githubusercontent.com/17737220/152103735-edcccd1c-c3b2-4386-b04f-d7152f5e9c4f.png)

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: MacOs
- Browser [e.g. Chrome, Safari, Firefox]: Brave, Chrome

Logs:
[carbon.now.sh-1643782748347.log](https://github.com/carbon-app/carbon/files/7984046/carbon.now.sh-1643782748347.log)

**Comment by mfix22** [comment]
@KrishnB please post steps for reproducing this error. Which page did you see this on? If you could link to a reproduction, that would be great.

**Comment by mfix22** [comment]
We have reached Firebase platform limits (with zero warning or notice) and are trying to get our access restored. We appreciate your patience and understanding.

**Comment by mfix22** [comment]
I believe this issue has been resolved. Please bear with us if other complications come up. 

If you notice similar issues, please open a new issue. 

Thanks for your understanding!
