### ISSUE TITLE
Source code containing <script> tag cannot be copy/paste to medium.com

### ISSUE THREAD

**Issue by hszhai** [carbon-app/carbon#1330]
**Describe the bug**
When the source code contains <script> tag, as used for JavaScript, after it copy/paste to medium.com, the code will not formulate the proper display.

The following image is an exmpale.
![image](https://user-images.githubusercontent.com/1051068/152662692-4d691353-bfe5-463e-9a86-0dd997e97d4d.png)

The same code, after deleting the line containing <script> will work properly.

**To Reproduce**
1. Use the following source code:
<template>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="bg-gradient-to-r from-blue-300 to-amber-400">
        <div class="text-center text-5xl font-bold text-white p-20">
            Hello World
        </div>
        <div id="hello-world-from-vite"></div>
    </body>
</html>
</template>
2. click the icon for [Copy to Clipboard], then [medium.com], you should see "copied".
3. Goto medium.com, click on "Write" on the right corner, then paste the code. The code will not turn into graphic display as it should be doing.

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: MacOS
- Browser [e.g. Chrome, Safari, Firefox]: Chrome, Safari
- Carbon URL [e.g. carbon.now.sh?bg=pink]:
-https://carbon.now.sh/?bg=rgba%2528171%252C+184%252C+195%252C+1%2529&t=seti&wt=sharp&l=vue&width=680&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=0px&ph=0px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%2525&si=false&es=1x&wm=false&code=%25253Ctemplate%25253E%25250A%25253Chtml%252520lang%25253D%252522en%252522%25253E%25250A%252520%252520%252520%252520%25253Chead%25253E%25250A%252520%252520%252520%252520%252520%252520%252520%252520%25253Cmeta%252520charset%25253D%252522utf-8%252522%25253E%25250A%252520%252520%252520%252520%252520%252520%252520%252520%25253Cscript%252520src%25253D%252522https%25253A%25252F%25252Fcdn.tailwindcss.com%252522%25253E%25253C%25252Fscript%25253E%25250A%252520%252520%252520%252520%25253C%25252Fhead%25253E%25250A%252520%252520%252520%252520%25253Cbody%252520class%25253D%252522bg-gradient-to-r%252520from-blue-300%252520to-amber-400%252522%25253E%25250A%252520%252520%252520%252520%252520%252520%252520%252520%25253Cdiv%252520class%25253D%252522text-center%252520text-5xl%252520font-bold%252520text-white%252520p-20%252522%25253E%25250A%252520%252520%252520%252520%252520%252520%252520%252520%252520%252520%252520%252520Hello%252520World%25250A%252520%252520%252520%252520%252520%252520%252520%252520%25253C%25252Fdiv%25253E%25250A%252520%252520%252520%252520%252520%252520%252520%252520%25253Cdiv%252520id%25253D%252522hello-world-from-vite%252522%25253E%25253C%25252Fdiv%25253E%25250A%252520%252520%252520%252520%25253C%25252Fbody%25253E%25250A%25253C%25252Fhtml%25253E%25250A%25253C%25252Ftemplate%25253E%25250A

<details>
  <summary>Code snippet</summary>
  <pre>
  
  </pre>
</details>

**Comment by mfix22** [comment]
Unfortunately this is a limitation of Medium embeds. Please contact Medium support if you would like this feature supported.
