### ISSUE TITLE
Missing "Snippets" Action Menu

### ISSUE THREAD

**Issue by el-ang** [carbon-app/carbon#1335]
**Describe the bug**
Missing "Snippets" Action Menu, but the page is still accesible by changing URL.

**To Reproduce**
How I got the bug:

1. So that time I was able to open snippet with the "Snippets" action menu.
2. I clicked the "Account" action menu.
3. In the "Account" page I accidently press the "Sign Out" button in the page navigation.
4. I tried to sign in again.
5. I open the action menu (The Button at the top right page with GitHub Username and Profile Picture inside).
6. I don't see the "Snippets" action menu anymore.
7. I tried to sign out and in again, not working.
8. I tried to write my snippet without signed in and then sign in, not working.
9. I tried to clear my browser's caches, still it didn't work.

**Expected behavior**
A button or a link to all of my code snippets in "Carbon" web app.

**Screenshots**
![image](https://user-images.githubusercontent.com/64268522/153028858-823a1ae8-0eae-40f2-9b94-ced033460c7e.png)

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: Windows 10
- Browser [e.g. Chrome, Safari, Firefox]: Google Chrome Version 98.0.4758.82 (Official Build) (64-bit)
- Carbon URL [e.g. carbon.now.sh?bg=pink]: https://carbon.now.sh/

<details>
  <summary>Code snippet</summary>
  <pre>
  Every Code Snippets
  </pre>
</details>

**Comment by mfix22** [comment]
It's back up: https://carbon.now.sh/snippets 👍
