### ISSUE TITLE
Question: Do I have to pay for embeds?

### ISSUE THREAD

**Issue by Potherca** [carbon-app/carbon#1336]
In [my blog post on Medium](https://blog.devgenius.io/the-search-for-the-holy-grail-of-code-blocks-on-medium-502071931cac) I speak favorably of Carbon. 

However, one of my readers pointed out to me that embedding Carbon snippets does not seem to work unless one has a paid account. 

This seems to be reflected on the Account page:

![image](https://user-images.githubusercontent.com/195757/153160921-86bb2fa9-d6bf-41dd-9984-908eaac0b5d0.png)

However, I've never had any issues with embedding snippets from my free account. I also noticed that the git commit for the "Carbon Diamond is not quite ready yet." message is 3 years old.

So now I am confused... Is a paid account now required for embedding snippets?

**Comment by mfix22** [comment]
Thanks for the question. That feature is now included in free tiers. Feel free to submit a PR to fix this 🙂
