### ISSUE TITLE
Idea: Animated differences in code snippets

### ISSUE THREAD

**Issue by kolibril13** [carbon-app/carbon#1346]
**Describe the change**
My idea is to generate animations that visualize differences of two code snippets on a website similar to [carbon.now.sh](https://carbon.now.sh/).
**Videoexample**

https://user-images.githubusercontent.com/44469195/157110469-842f52ad-6ee9-43d0-969d-272c1bf01d85.mp4

This video was created with a video editor, but my intention is to create it automatically.

**Info:**
The code diff logic could be calculated with a javascript package [jsdiff](https://github.com/kpdecker/jsdiff), the animation can be made with CSS [keyframes](https://www.w3schools.com/css/css3_animations.asp) and the video mp4 download could be created with [Remotion](https://www.remotion.dev/). Code styling could be made with the already existing tools of carbon.

I know this would be a *huge* project,  but I still want to mention this idea, as this might be a very useful for many people.

**Additional Content**
This is how the non-animated diff of the above video looks like:
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/44469195/157114336-4dd9c492-5eda-4c98-9f8d-30cd99d1708e.png">

**Comment by mfix22** [comment]
Hey @kolibril13, this is a super fantastic idea, and I think you should build it, but it is outside of Carbon's current scope, so I am going to close this issue. We do have a similar issue (#547), which I am keeping open. That issue accomplishes something similar to what you are proposing here. 

Thanks for sharing 🙂
