### ISSUE TITLE
Exported image cut off - Safari Technology Preview

### ISSUE THREAD

**Issue by terrymorse58** [carbon-app/carbon#1351]
**Describe the bug**

When using the Safari Technology Preview browser (Release 141 (Safari 15.4, WebKit 17614.1.3.8)), the Export command produces an image that is shifted to the left by about half the image size, leaving the left half of the image off.

**To Reproduce**

1. Open [carbon.now.sh](https://carbon.now.sh) in Safari Technology Preview browser
2. Click on 'Export'
3. See the image in Downloads folder

**Expected behavior**
Expected to see an image that isn't shifted and cropped.

**Screenshots**

Expected image:

![carbon](https://user-images.githubusercontent.com/42072275/159563811-3b5ab5a2-5bbd-46a0-8e19-de11abde5ce6.png)

Incorrect image:

![carbon-bug](https://user-images.githubusercontent.com/42072275/159563686-a61c222d-5bd1-4a24-b05a-4020db16544f.png)

**Info:**

- OS: macOS Monterey 12.12.1
- Browser: Safari Technology Preview release 141
- Carbon URL: [carbon.now](https://carbon.now.sh)

**Comment by cperezabo** [comment]
It happens in the standard Safari 15.4 as well

**Comment by mfix22** [comment]
@terrymorse58  @cperezabo I just tried it out on basic Safari, and it is working for me. Please share a link to a Carbon snippet that reproduces this bug.

**Comment by pan93412** [comment]
> @terrymorse58 @cperezabo I just tried it out on basic Safari, and it is working for me. Please share a link to a Carbon snippet that reproduces this bug.

I can reproduce it:

https://user-images.githubusercontent.com/28441561/161749499-e54d4190-7160-49ab-978a-fb9422a00843.mov

**Comment by pan93412** [comment]
It works properly when outputting in 1x size. Besides, outputting in 4x made all the canvas white.

<img width="441" alt="截圖 2022-04-05 下午8 03 28" src="https://user-images.githubusercontent.com/28441561/161749680-bf5a200f-6f52-4af3-b943-76d43b147bbb.png">

**Comment by mfix22** [comment]
@hatsu38 I think this came from one of your recent PRs. Do you have time to take a quick look? Otherwise I think I will have to revert :/

**Comment by mfix22** [comment]
@erikr @pan93412 @terrymorse58 @cperezabo this seems to be a regression in Safari somehow. Would love some help finding a bug fix here, if any of you have the time.

**Comment by baruchadi** [comment]
👋 Hey there! 
I have a quick patch for this issue here: https://github.com/carbon-app/carbon/pull/1405

It's my first time contributing to Carbon, so if a repo owner can take a quick look I'd appreciate it (changed 2 lines of code) 🙏 

Cheers!
