### ISSUE TITLE
Add the filename to the image editor (like a tab)

### ISSUE THREAD

**Issue by r-martins** [carbon-app/carbon#1355]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Some coding examples involves multiple files. Having the ability to specify the filename, like an editor's tab, would be very useful.
Here's an example (circled in blue).
![Cursor_and_Magento_Snippet__config_php_vs_env_php_-_mart_ricardo_gmail_com_-_Gmail](https://user-images.githubusercontent.com/191149/160052563-3c924714-ff38-458e-a1b5-64865b24f891.jpg)

**Describe alternatives you've considered**
None. I don't know which tool was used to generate this image.

**Comment by mfix22** [comment]
You can add a title by typing in the input at the top of the editor:

<img width="939" alt="image" src="https://user-images.githubusercontent.com/8397708/161398275-3f997780-6504-4d8c-aa07-9b2c98acd9fd.png">
