### ISSUE TITLE
Cannot change the editor theme after applying color palette from background image

### ISSUE THREAD

**Issue by satvikDesktop** [carbon-app/carbon#1361]
**Describe the bug**
If you click the option of "generate color palette" after you select a background image and then change back to solid color you cannot change the theme of the editor .

**To Reproduce**

1. Change the background image 
2. Click on "Generate Color Palette"
3. Change the theme of the text editor 

**Expected behavior**
The theme of the editor should change

**Info (please complete the following information):**

- OS -> Windows
- Browser -> Chrome
- Carbon - URL -> [url](https://carbon.now.sh/?bg=rgba%2848%2C63%2C77%2C1%29&t=shades-of-purple&wt=none&l=auto&width=680&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Fira+Code&fs=14px&lh=152%25&si=false&es=2x&wm=false&code=const%2520pluckDeep%2520%253D%2520key%2520%253D%253E%2520obj%2520%253D%253E%2520key.split%28%27.%27%29.reduce%28%28accum%252C%2520key%29%2520%253D%253E%2520accum%255Bkey%255D%252C%2520obj%29%250A%250Aconst%2520compose%2520%253D%2520%28...fns%29%2520%253D%253E%2520res%2520%253D%253E%2520fns.reduce%28%28accum%252C%2520next%29%2520%253D%253E%2520next%28accum%29%252C%2520res%29%250A%250Aconst%2520unfold%2520%253D%2520%28f%252C%2520seed%29%2520%253D%253E%2520%257B%250A%2520%2520const%2520go%2520%253D%2520%28f%252C%2520seed%252C%2520acc%29%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520const%2520res%2520%253D%2520f%28seed%29%250A%2520%2520%2520%2520return%2520res%2520%253F%2520go%28f%252C%2520res%255B1%255D%252C%2520acc.concat%28%255Bres%255B0%255D%255D%29%29%2520%253A%2520acc%250A%2520%2520%257D%250A%2520%2520return%2520go%28f%252C%2520seed%252C%2520%255B%255D%29%250A%257D%250A%250A%250A%252F%252F%2520Photo%2520by%2520Martin%2520Jernberg%2520on%2520Unsplash)

https://user-images.githubusercontent.com/83361432/162028939-81420f2c-f220-43ea-8888-41a5365c4ca8.mp4

Note :

-  I  cannot change the theme even after removing the background image 
- There are slight changes in the theme , some of the keywords change color when the theme is changed but for the most part the theme remains the same (as per the color palette generated by bg img)

**Comment by shikhar13012001** [comment]
Can I work on this issue? @satvikDesktop @mfix22

**Comment by mfix22** [comment]
@shikhar13012001 please do! 🙏

**Comment by mfix22** [comment]
@satvikDesktop thank you for posting such a great bug reproduction video! We should be able to fix this shortly 👍

**Comment by mfix22** [comment]
Sorry @shikhar13012001, I guess I beat you to it here (#1377). In the future, you don't need permission to work on open issues! Feel free to work on anything that is open.

**Comment by mfix22** [comment]
@shikhar13012001 would love your help with #1351, if you have the time.
