### ISSUE TITLE
Add side-card to input some text information

### ISSUE THREAD

**Issue by afucher** [carbon-app/carbon#1364]
**Is your feature request related to a problem? Please describe.**
There is a template that people are using to share knowledge, is a short text description with the code, side by side. I created a discussion (https://github.com/carbon-app/carbon/discussions/1362).

**Describe the solution you'd like**
Be able to enable or disable a side-card, where I can edit a title, a body and possible a footer with some social media icon
Also I think that create a new section on the config will be the best option, so in the future we can enable the user to select the color of the side-card, font-family, font-size, etc..

**Describe alternatives you've considered**
I know that some people, including me, use carbon to generate the code snippet and then use some image editor to make the side card text.

**Additional context**
This is one image that I created manually in a image editor:
![](https://user-images.githubusercontent.com/3756185/162578130-9c0f65d8-810d-4b9d-add2-374d1d4b7743.png)
I already made a fork and started to implement the feature, because I want to use it, even if it is just locally. 

https://user-images.githubusercontent.com/3756185/162636976-436242d8-9446-4018-b4f0-622851df54c6.mov

**Comment by roziscoding** [comment]
This would absolutely fantastic!

**Comment by afucher** [comment]
Hey, I decided to implement this feature as a browser extension: **kovacs**
A version is available for Chrome (and Edge): https://chrome.google.com/webstore/detail/kovacs-altered-carbon/cbbiifcionibkklghefkcineekginbla
Here is the github repo: https://github.com/afucher/kovacs
