### ISSUE TITLE
Add a new button: Save

### ISSUE THREAD

**Issue by chrimaho** [carbon-app/carbon#1366]
**Is your feature request related to a problem? Please describe.**
Once I have added my code to the https://carbon.now.sh/ interface, my snippet will be saved. That's good! However, once I change some of the config (for example, change the language or change the styling), it then does not automatically save. That's bad.

**Describe the solution you'd like**
Down the bottom of the snippet, next to the [![](https://img.shields.io/badge/--delete?label=Delete&style=social)](#) and [![](https://img.shields.io/badge/--duplicate?label=Duplicate&style=social)](#) buttons, I'd like to see another button: [![](https://img.shields.io/badge/--save?label=Save&style=social)](#).

**Describe alternatives you've considered**
Relying on the auto-save functionality is not always very reliable.

**Additional context**
This new Save button will be a welcomed addition.

**Comment by mfix22** [comment]
Working on this feature!
