### ISSUE TITLE
Encode snippets into URLs: One great feature for Twitter (and not only Twitter)

### ISSUE THREAD

**Issue by OnkelTem** [carbon-app/carbon#1369]
Currently when you create a snippet, you can only copy the **image**, but you cannot share the code itself. So people cannot extend the code or even copy it.

Yet there is a clear and elegant way to solve this problem without implementing a snippets storage!

All you have to do, is to encode the current snippet and its display options into a GET LINK, and provide a new snippets VIEW page which is displayed when users open that GET LINK.

Also, to support media embedding, you need to provide its robot with a screenshot. That's exactly the screenshot which your users are copying and sharing.

Add here the fact that Twitter provides if not infinite, but at least very large free storage for links, and voilà, we've got a free code storage (in the Twitter database).

If it looks too Twitter-specific - it's actually not. With that you just provide people with their source code, so that they could bookmark it.

What are your thoughts, folks?

You can also check out the following Twitter thread where I'm experimenting with TypeScript Playground (which works exactly this way):
https://twitter.com/onkeltem/status/1520355668984832000

**Comment by mfix22** [comment]
<img width="945" alt="Screen Shot 2022-05-14 at 11 54 03 AM" src="https://user-images.githubusercontent.com/8397708/168444811-730fb504-a5ce-4c52-9471-c3db23cbd119.png">

You can do this using this menu:

**Comment by OnkelTem** [comment]
Sorry, what do you mean in that menu?
It doesn't work for me.

**Comment by mfix22** [comment]
@OnkelTem sorry, I misunderstood your original message. We have 2 features that support your use case, if I understand correctly.
1. You can embed any snippet on a website using carbon.now.sh/embed. These snippets include a copy-button, which when clicked copy the code. 
2. You can save the snippet to your Carbon profile. You can then share these links on Twitter, which will unfurl the image, and point back to the original source (I believe how you suggested above)

> P.S. Excuse me, why are you closing it without waiting for a feedback?
This is how I am able to maintain this project, solo, for free.

**Comment by mfix22** [comment]
Carbon encodes the state as query params by default. We don't use base64 encoding since we want the params themselves to be legible: https://carbon.now.sh/?bg=rgba%28171%2C+184%2C+195%2C+1%29&t=seti&wt=none&l=auto&width=680&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=Test%21

**Comment by OnkelTem** [comment]
How do you recieve this URL?
