### ISSUE TITLE
Selection is captured

### ISSUE THREAD

**Issue by alirezaopmc** [carbon-app/carbon#1370]
Hi this is my first time openning an issue in an open-source project. Fix me if I am wrong.

**Describe the bug**
Selected text is captured in the image copy.

**To Reproduce**

1. Fill the text field with some text
2. Select a part of the text
3. Copy the image and see it

You can use bellow code and select the second line.
```java
  public Vector2(Vector2 other) {
      this.x = other.x;
      this.y = other.y;
  }
```

**Expected behavior**
Maybe it's too selfish but personallly I don't want to have the selected text in the output image. However it can be useful somehow. It can be mentioned in https://carbon.now.sh/about if it's a feature.

**Screenshots**
![image](https://user-images.githubusercontent.com/35873101/168106550-8715e465-4559-4c02-8405-475a0ff091a3.png)

**Info**

- OS: Windows 11
- Browser: Chrome latest

**Comment by mfix22** [comment]
This is intentional! If you don't wan the selection text to show up in the image, just undo the selection 🙂
