### ISSUE TITLE
An unexpected error has occurred. Please file an issue here.

### ISSUE THREAD

**Issue by OnkelTem** [carbon-app/carbon#1376]
**Describe the bug**
Cannot save a snippet — an error appears:

```
An unexpected error has occurred. Please file an issue here.
```

**To Reproduce**

1. Go to https://carbon.now.sh/LQKm5ukrOFt9VcyyXVFC
2. Click the "Save" button.

**Expected behavior**
Either new link should be generated instead or the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/114060/168465140-ad68d7a4-11d1-4607-b3ed-3863076c9813.png)

**Info (please complete the following information):**

- OS  [e.g. macOS, Linux, Windows, iOS]: Linux Kubuntu 20.04
- Browser [e.g. Chrome, Safari, Firefox]: Google Chrome 100
- Carbon URL [e.g. carbon.now.sh?bg=pink]: https://carbon.now.sh/LQKm5ukrOFt9VcyyXVFC

**Comment by mfix22** [comment]
Thank you for filing this @OnkelTem—have the fix ready and is deploying right now. Sorry for the inconvenience.
