### ISSUE TITLE
Window title not added to URL

### ISSUE THREAD

**Issue by cammarin** [carbon-app/carbon#1380]
**Describe the bug**

When you edit the window title, the URL is not updated. So, refreshing the page or copying and pasting the URL, the title is blank.

This also impacts the copy function for iframe and plain URL.

**To Reproduce**
1. Go to https://carbon.now.sh
2. Edit window title
3. Refresh the page
4. Title is blank again

**Expected behavior**

Editing the window title should update the URL.

**Screenshots**

blank title
<img width="2128" alt="untitled" src="https://user-images.githubusercontent.com/936220/170503759-ecc6c258-ce72-42bd-8139-618f60714dd7.png">

`index.js`
<img width="2128" alt="indexjs" src="https://user-images.githubusercontent.com/936220/170503786-1a971c7c-6e24-4178-b608-cf2341b37511.png">

**Info (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Carbon URL: https://carbon.now.sh/?bg=rgba%2874%2C74%2C74%2C1%29&t=seti&wt=none&l=auto&width=680&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false

**Comment by mfix22** [comment]
@cammarin this is actually intentional, since it is a feature we don't want to encourage strong use of: https://github.com/carbon-app/carbon/commit/3187b6777a1425f8ff63647ecea67b6f43cf2442

Could you explain more about your use case? I'll consider adding it back as a valid option.
