### ISSUE TITLE
How to configuring development environment?

### ISSUE THREAD

**Issue by OnkelTem** [carbon-app/carbon#1386]
Hi all!

I need help with configuring Carbon development env. 
Since I didn't find any docs or gudelines for new contributors I had to search the source code to discover how to get firebase connection working. But I did it finally and now I can log in. But now the `Save` button doesn't work.
When I click it I get an error: 

```
POST http://localhost:6001/api/snippets 404 (Not Found)
```

Any ideas what's wrong?
I run the app as: `$ npm run dev`

Thanks in advance!

**Comment by mfix22** [comment]
Hey @OnkelTem, the snippet API is not currently public. Sorry about the inconvenience here.

**Comment by OnkelTem** [comment]
Then how do I develop anything?
