### ISSUE TITLE
Solidity no longer highlighted

### ISSUE THREAD

**Issue by paulrberg** [carbon-app/carbon#1388]
**Describe the bug**
I've been pasting Solidity code snippets into Carbon for a long time, and I always saw them highlighted correctly. But now that is no longer the case.

**To Reproduce**

1. Go to [carbon.now.sh](https://carbon.now.sh/).
2. Paste any Solidity code (see example below).
3. Click "Solidity" from the language dropdown.
4. See no highlighted code.

**Expected behavior**
The Solidity code should be highlighted [just like it used to be previously](https://twitter.com/PaulRBerg/status/1510584043028500492).

**Screenshots**
Here's a screenshot:

<img width="1728" alt="Screen Shot 2022-06-12 at 5 56 36 PM" src="https://user-images.githubusercontent.com/8782666/173239159-75ae1a5f-1782-4722-9869-cd94f64e107e.png">

**Info (please complete the following information):**

I tested this on both Chrome and Safari.

- macOS@12.4
- Chrome Version 102.0.5005.115
- Safari Version 15.5 (17613.2.7.1.8)

**Comment by mfix22** [comment]
@alincode any idea why this would be? I had to temporarily inline the `codemirror-solidity` mode in order to fix this issue.

**Comment by paulrberg** [comment]
Thanks for the quick fix!

**Comment by paulrberg** [comment]
Unfortunately it looks like this still doesn't work.

<img width="920" alt="Screen Shot 2022-06-19 at 2 37 03 PM" src="https://user-images.githubusercontent.com/8782666/174478941-af55ecc5-4f78-4731-9f7c-0376d4726381.png">
