### ISSUE TITLE
Submitted a new Pull Request that added a Border Radius setting in Window menu

### ISSUE THREAD

**Issue by 27shutterclicks** [carbon-app/carbon#1413]
@mfix22 I contributed new feature for adjusting the window border radius using a slider from Settings > Window: #1412 

--------------------------

![carbonapp_corner_radius](https://user-images.githubusercontent.com/114191180/195396247-bd2db86f-b862-4c80-a86e-5eac05bc70a0.jpg)

--------------------------
Not sure how often you guys review pull requests, so I thought I'd mention it here with a screenshot. 

Cheers!

**Comment by mfix22** [comment]
@27shutterclicks I get notifications for new pull requests, and I will review them as soon as I can.

Please don't submit extra issues to point to the pull request. 🙂 

Cheers!
