### ISSUE TITLE
Using generated pictures for commercial uses

### ISSUE THREAD

**Issue by dmoka** [carbon-app/carbon#1416]
**Describe the change**
Hey Carbon team! It is not an issue, but rather a question I could not find the answer to.

I would like to use your tool Carbon (accessed via https://carbon.now.sh/) to generate images and use them in a product I would like to sell. So it will be commercial use.

I would like to ask if this is allowed to do, legally. I already checked the terms but could not find any specific info.

Could you pleas help me in this matter?

Thank you and keep up with the good work!

**Comment by dmoka** [comment]
I found a [related issue](https://github.com/carbon-app/carbon/issues/1231)

It says `You have full creative control with the images you generate using Carbon`. 

Does that mean I can use it for commercial purposes? If so, then we can close this issue.

Thank you!

**Comment by mfix22** [comment]
Please send your question with full detail of use to carbon.now.sh@gmail.com and we will get back to you there. Thanks!
