### ISSUE TITLE
adding label to code image

### ISSUE THREAD

**Issue by willi84** [carbon-app/carbon#1462]
It would be awesome if I am capable to print some label on my image corner (.e.g. top right) to show e.g. in which terminal or environment my code is

current state:
![image](https://user-images.githubusercontent.com/6207308/231166124-67728889-cb26-4ce1-90fa-c8167326e3d9.png)

idea:

![image](https://user-images.githubusercontent.com/6207308/231166400-91b7b862-9cf8-41da-9792-6156ec82d0ea.png)

alternativly
- also for code

![image](https://user-images.githubusercontent.com/6207308/231166762-1d4901e1-7923-4375-b3fe-c61e8be337e0.png)

- also own watermark if needed (company or brand logo) to see the origin
![image](https://user-images.githubusercontent.com/6207308/231168389-51444e09-e030-499c-9a42-6a032edc5e06.png)

**Comment by geeky-sambhav** [comment]
I would like to contribute on this issue

**Comment by mfix22** [comment]
You can add the title label at the top of the editor: 
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/b9e44f32-a32c-460b-ba32-cf807ae7b244" />

**Comment by Cornelius-Figgle** [comment]
I would like to be able to do this without having a title bar. My use case is for indicating which file a code snippet (often only a handful of lines) is from and thus a title bar with buttons looks bulky and out of place. Would it be possible to implement something similar to @willi84's second suggestion? 

![Image](https://github.com/user-attachments/assets/2a8077e0-9b3d-4b58-8830-6f6da60a5223)

Vs

![Image](https://github.com/user-attachments/assets/16df74fa-f31e-4aec-8c14-2a3ef45bd55d)
