### ISSUE TITLE
Carbon app is not running locally

### ISSUE THREAD

**Issue by p3n7a90n** [carbon-app/carbon#1483]
**Title**
I am getting the below error while running carbon latest released version(4.9.10) locally.

**Screenshots**
![image](https://github.com/carbon-app/carbon/assets/21966348/835e1865-3491-4584-a813-3ca21d59704b)
![image](https://github.com/carbon-app/carbon/assets/21966348/d4ac8e37-37cd-4327-bb0b-77c42b009044)

There seems to be some problem with the codemirror.

I tried few suggestions based on the error  but none of them worked
Any suggestions on how can I resolve this.

**Comment by kevin262516** [comment]
> To install it properly, you can do this:
> 
> ```shell
> $ asdf global nodejs latest
> $ rm -rf node_modules/
> $ yarn install
> ```
> 
> Before running Carbon, you will need to remove some languages (`Nix` and `Stan`) from `lib/constants.js` file:
> 
> ```diff
> ...
>   {
>     name: 'Nim',
>     mode: 'nim',
>     custom: true,
>     highlight: true,
>   },
> - {
> -   name: 'Nix',
> -   mode: 'nix',
> -   highlight: true,
> - },
>   {
>     name: 'Objective C',
>     mode: 'clike',
>     mime: 'text/x-objectivec',
>     short: 'objectivec',
>     highlight: true,
>   },
> ...
>   {
>     name: 'SQL',
>     mode: 'sql',
>     highlight: true,
>   },
> - {
> -   name: 'Stan',
> -   mode: 'stan',
> -   highlight: true,
> - },
>   {
>     name: 'Stylus',
>     mode: 'stylus',
>     mime: 'stylus',
>     highlight: true,
>   },
> ...
> ```
> 
> Now you can run it by calling the next binary from your node_modules directory:
> 
> ```shell
> $ ./node_modules/.bin/next dev
> ```

I modified the configuration according to the suggestions, but I still get the error

- System: `window 10`
- Node: `v18.12.0`

![image](https://github.com/carbon-app/carbon/assets/8156882/1d2ece82-e710-4cd7-bc54-1f751075cd05)


![image](https://github.com/carbon-app/carbon/assets/8156882/05bcd616-b717-46be-a5ca-84c80f132dd3)

**Comment by mrchipset** [comment]
```
./node_modules/.pnpm/codemirror@5.65.5/node_modules/codemirror/mode/rpm/changes/index.html
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| 
| <title>CodeMirror: RPM changes mode</title>
```

I also still get this issue.

The environment is:

node v20.17.0
Win10 x64 Professional 22H2
