### ISSUE TITLE
Diff command support

### ISSUE THREAD

**Issue by noraj** [carbon-app/carbon#1490]
Currently, the diff format supported is the unified variation cf. https://en.wikipedia.org/wiki/Diff#Unified_format

But the normal output is not supported:

![image](https://user-images.githubusercontent.com/16578570/216089821-20e4ab98-662b-4e4e-bfb6-9c82c594a7c3.png)

![image](https://user-images.githubusercontent.com/16578570/216089889-2a9cd6e7-afe4-40a5-861e-f2e64c633cdf.png)

I suggest renaming the current diff to `Diff (unified)` and to add support for the normal diff format under the name `Diff (normal)`.

**Comment by mfix22** [comment]
@noraj I would accept a PR that adds this.
