### ISSUE TITLE
Preview does not match export

### ISSUE THREAD

**Issue by Pyrolistical** [carbon-app/carbon#1499]
**Describe the bug**
Extra new line on exported image not present in preview

**To Reproduce**

1. Look at [preview](https://carbon.now.sh/?bg=rgba%28171%2C+184%2C+195%2C+1%29&t=seti&wt=none&l=javascript&width=680&ds=false&dsyoff=20px&dsblur=68px&wc=false&wa=true&pv=0px&ph=0px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=for%2520%28let%2520ist%2520%253D%25200%253B%2520...%29%2520%257B%250A%2520%2520for%2520%28let%2520ind%2520%253D%25200%253B%2520...%29%2520%257B%250A%2520%2520%2520%2520for%2520%28let%2520ith%2520%253D%25200%253B%2520...%29%2520%257B%250A%2520%2520%2520%2520%2520%2520...%250A%2520%2520%2520%2520%257D%2520%2520%250A%2520%2520%257D%2520%2520%250A%257D)

Preview:
![Screenshot 2023-12-18 at 12 34 35](https://github.com/carbon-app/carbon/assets/463642/62cf3e98-3e07-4972-b0c4-efd6e67b7085)

Actual exported image:
![carbon](https://github.com/carbon-app/carbon/assets/463642/6333c8ff-8749-4c76-83c9-a7107816c2f5)

**Expected behavior**
Preview to match exported image

**Info (please complete the following information):**

- OS MacOS
- Browser Chrome 119

**Comment by SeanDylanGoff** [comment]
Minimal reproduction: https://carbon.now.sh/?bg=rgba%28171%2C+184%2C+195%2C+1%29&t=seti&wt=none&l=text%2Fx-java&width=750&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=18px&ph=14px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=new%2520Rental%28%29%253B

Env: Chrome on OSX, Version 120.0.6099.216 (Official Build) (arm64)
Not reproducible in Safari.

**Comment by LouisVenhoff** [comment]
Meanwhile this bug is fixed ;)
