### ISSUE TITLE
Deploy Pipeline error

### ISSUE THREAD

**Issue by danielhe4rt** [carbon-app/carbon#1516]
![image](https://github.com/carbon-app/carbon/assets/6912596/ccf75d77-694c-497a-917e-46b792b71a6b)

Hey @mfix22!

Just saw that @carbon_app have some issue on the deploy pipeline and the addition that I did isn't in production yet. 

There's anything that I can do to help with? CQL is something really important to my content creation and I would appreciate having it on the official CarbonApp!

Commit: https://github.com/carbon-app/carbon/commit/7be35f5cd12ed921b0dc5101496db6703c328f21

Cheers and thanks for the amazing project <3

**Comment by mfix22** [comment]
@danielhe4rt see https://github.com/carbon-app/carbon/issues/1545 — hope to get a new deploy out soon. Thanks for the kind words.
