### ISSUE TITLE
Add an option to highlight one or more lines

### ISSUE THREAD

**Issue by egvijayanand** [carbon-app/carbon#1544]
**Is your feature request related to a problem? Please describe.**

No, it's not an issue but rather a feature request.

When sharing a code snippet, we sometimes need to highlight one or more lines to draw attention to them.

**Describe the solution you'd like**

If possible, line highlighting in the snippet

**Describe alternatives you've considered**

Screenshot from the IDE with a focus on that particular line. Lacks that premium look and feel.

**Additional context**

Some online code editors achieve this by getting the line numbers and then modifying the CSS accordingly.

**Comment by mfix22** [comment]
You can click on the line numbers to highlight lines!
