### ISSUE TITLE
Side-by-side code panes 

### ISSUE THREAD

**Issue by nlhuykhang** [carbon-app/carbon#337]
This would be very useful when creating images for code review, comparison.

**Comment by mfix22** [comment]
Hey @nlhuykhang thanks for the suggestion. As of right now, we want to keep a single pane for the screenshots, because users can just create two screenshots and place them next to each other to create the same effect.

**Comment by nlhuykhang** [comment]
Yeah, that's what I did. Thanks for the work 🙂

**Comment by mfix22** [comment]
Thanks 😄

**Comment by kievsash** [comment]
+1 for splitview
Possible usecase: https://twitter.com/thekiba_io/status/1136908291366408192?s=20

**Comment by mfix22** [comment]
Reopening for consideration — not a confirmation that we will support this.
