### ISSUE TITLE
[New feature proposal] Save history to indexdb/local storage 

### ISSUE THREAD

**Issue by alvaropinot** [carbon-app/carbon#362]
IMO persisting the previous text for the created images will be a nice feature to add, so a user can easily recreate them with different styles. 

As now the url is allowing to fully reconstruct the state it might be easy just to persist this to something like local storage and add a combo/history component to the UI that allows the user to pick previously created carbon's :)

Maybe name spacing those urls by user may allow something similar to user "accounts".

Any thoughts?

**Comment by mittalyashu** [comment]
@alvaropinot, as mentioned by @yeskunall in [this comment](https://github.com/dawnlabs/carbon/issues/260#issuecomment-368281891), there can be storage issues.

**Comment by mfix22** [comment]
@alvaropinot with the `4.0.0` release, we [have introduced user profiles](https://github.com/carbon-app/carbon/issues/754), where you can save your snippets to the cloud. This should cover your use case, and you won't run into any storage issues.
 
<img width="969" alt="Screenshot 2019-08-14 09 51 17" src="https://user-images.githubusercontent.com/8397708/63040141-acbe8c80-be79-11e9-90e6-41cdb1480764.png">
