### ISSUE TITLE
New default code snippet

### ISSUE THREAD

**Issue by mfix22** [carbon-app/carbon#447]
Hey Carbon users,
We want a new default code snippet (or maybe a few) and need your help. 

What should we make it? 🙂Comment below with suggestions.

**Comment by mittalyashu** [comment]
What do you mean by default code snippet?

**Comment by mittalyashu** [comment]
I got one.

```js
var iAmAwesome = true;

if iAmAwesome {
   open(carbonNow)
} else {
  open(localScreenshotTool)
}
```

**Comment by mfix22** [comment]
```jsx
// Built with Carbon
<Dropper
  onDrop={files => this.setState({ files })}
  filter={file => file.size < 10000 && file.type === 'image/png')}
>
  {({ isOver, canDrop, files }) => (
    <Overlay
      title={`Drop your files here to import ${isOver ? '✋' : '✊'}`}
    >
      <Upload files={files.map(file => file.content)} />
    </Overlay>
  )}
</Dropper>
```

**Comment by mfix22** [comment]
@MONIKA-KUMAR-JETHANI feel free to make suggestions in the comments of this issue! 🙂

**Comment by sdabhi23** [comment]
Should the same snippet be used for all languages or should the snippet change when the language is changed from the menu? 🤔

**Comment by mfix22** [comment]
I think it would overcomplicate things to switch the code when the language changes since we would have to keep track of if the user has typed anything before switching. I would love to replace the current one with a fresh JavaScript/React one, since that is mostly what Carbon was build with 🙂

**Comment by v-fernandez** [comment]
How about something like:

```javascript
const ThemeContext = createContext({ theme: "light", toggleTheme: () => {} })

const ThemeProvider = props => {
  const [theme, setTheme] = useState("light")
  const toggleTheme = () => setTheme(theme === "light" ? "dark" : "light")

  return (
    <ThemeContext.Provider value={{ theme, toggleTheme }}>
      {props.children}
    </ThemeContext.Provider>
  )
}
```

**Comment by mfix22** [comment]
@v-fernandez I like this^ ! I think we should include something like this in our next array of default snippets
