### ISSUE TITLE
Impossible to do anything meaningful from a phone/tablet

### ISSUE THREAD

**Issue by kirilloid** [carbon-app/carbon#506]
### Expected Behavior
Pressing white space inserts whitespace character

### Actual Behavior
Prsssing space inserts nothing and instead scrolls the page.

<details>
  <summary>Browser: </summary>
  Safari mobile 12
</details>

On top of that I can neither work with selection nor even hold and press “delete” button. And yes, I have seen rich text editors with syntax highlighting working well from the phone.

**Comment by mfix22** [comment]
Closing this in favor of #941 in order to give it a signal boost!
