### ISSUE TITLE
Feature suggestion: Colorize certain parts of plain text

### ISSUE THREAD

**Issue by chrispetrou** [carbon-app/carbon#548]
Hi! It would be nice for _plain-text syntax_ to be able to colorize certain words with custom colors by selecting them. I think this would be useful when trying to show the output of a script which uses custom colors.

**Comment by peagha** [comment]
I was looking for a way to use Carbon for colored terminal output, this feature would probably allow that 💖

**Comment by mfix22** [comment]
This feature was released with 4.0.0 🙌:
![Kapture 2019-08-14 at 9 48 16](https://user-images.githubusercontent.com/8397708/63039716-bc89a100-be78-11e9-936d-98e33723264a.gif)

**Comment by chrispetrou** [comment]
@mfix22 Awesome job! Thank you!!!
