### ISSUE TITLE
Export to imgur

### ISSUE THREAD

**Issue by mittalyashu** [carbon-app/carbon#688]
## Introduction

All the export feature are awesome 👍🏻, but when we click on `open` it redirects to blob page and `Copy Embed` gives the iframe for HTML pages.

![image](https://user-images.githubusercontent.com/29014463/53700214-0d9b6080-3e16-11e9-8c30-a11d32eed735.png)

This feature request is the combination of both the features, where users can just paste the image url to the webpage.

## Development process

There can a button which says `Export to imgur`, based on the user selected settings carbon will generate the image, export to imgur and return back the image url which will be copied the clipboard.

## Why Imgur?

[Imgur](https://imgur.com) is most popular place to upload unlimited images for free and **yes, for FREE.** 😂

### Reference

> Send the code & it returns a dynamic image.

[@deadcoder0904](https://github.com/dawnlabs/carbon/issues/210#issue-294718316)

**Comment by JosephWeaver** [comment]
+1

**Comment by mfix22** [comment]
Please just "👍" in the reactions, _not_ the comments, to vote for. Since this is an integration request, typically we would move it to #358, but I'm going leave it here for now.
