### ISSUE TITLE
Feature request: resume from image

### ISSUE THREAD

**Issue by filipbech** [carbon-app/carbon#750]
It would be super cool if you could somehow "resume" from an image - like you can import a code-file. 
Lots of times, I have to type out the code again an hour later when I find out I made a mistake when I made the image. 

A possible way to do it, was to inline the actual code in an exif-comment, and then read that as an import as well... for svg's you could just inline it in a comment

**Comment by mfix22** [comment]
@filipbech we experimented with this back in the day here: https://github.com/dawnlabs/carbon/issues/408

but it was concluded there was no way to write the exif data to the image _in_ the browser. Are you familiar with how to do that?

**Comment by filipbech** [comment]
Googleing around a little i found a couple of js-packages that seems to do just that.. 
https://github.com/exif-js/exif-js 
https://github.com/hMatoba/piexifjs

Would you want me to take a first crack at implementing it?

**Comment by mfix22** [comment]
Interesting! Never found https://github.com/hMatoba/piexifjs before. Sure you can take a stab at it. I am not sure how it will effect download times and such, so not 100% sure we want to support it by default yet. 

If adding this would help something like a11y (reading the code from the image) then I would be more keen on supporting it by default.

**Comment by filipbech** [comment]
Yeah, it should probably be a lazy loaded preference-based feature... don’t know about accessibility this way... but let’s explore that also

**Comment by mfix22** [comment]
Hey @filipbech I don't see any progress here, and I'm not sure we want to support this, especially since now we have saved snippet support. Sorry if you have been working on this in the background /:

**Comment by filipbech** [comment]
Ok.

**Comment by mfix22** [comment]
@filipbech if you  want to implement this go for it! 🙂 The Carbon core team is just not going to create it ourselves.
