### ISSUE TITLE
Snippets in Medium.com mobile app are hardly viewable

### ISSUE THREAD

**Issue by kievsash** [carbon-app/carbon#753]
I published an article with carbon code snippets: https://itnext.io/promises-vs-observables-for-angularjs-to-angular-migration-1161afacef7e
And have view issues from medium.com mobile app for Android.
I cannot scroll them horizontally, so only part of the code is visible.
So replaced them with exported PNG files with links to snippets

### Expected Behavior
I can somehow scroll code in the snippet.

### Actual Behavior
I cannot scroll them horizontally, so only part of the code is visible.
Screenshot: https://drive.google.com/open?id=1-1-jw1-36DgFFezg-0jjerEIZ9KcgZSl
<details>
  <summary>Browser: </summary>
  
</details>

**Comment by mfix22** [comment]
@kievsash thanks for bringing this to our attention! Can you post a snippet so I can recreate this easier? I'd like to fix this quickly 🙂

**Comment by kievsash** [comment]
Ok, here is a snippet:
https://carbon.now.sh/?bg=rgba(171%252C%2520184%252C%2520195%252C%25201)&t=paraiso-dark&wt=none&l=javascript&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=false&pv=56px&ph=56px&ln=false&fm=Hack&fs=14px&lh=133%2525&si=false&es=2x&wm=false

And I created medium draft: https://medium.com/@alexanderposhtaruk/test-carbon-now-sh-77ef20d507db

Try to open it with medium android app on your mobile device

**Comment by kievsash** [comment]
Still an issue

**Comment by austinwilcox** [comment]
Any updates on this?

**Comment by e-dong** [comment]
This is still an issue

**Comment by mfix22** [comment]
Going to track this in #1259
