### ISSUE TITLE
Add user profiles to save collections of snippets 

### ISSUE THREAD

**Issue by kievsash** [carbon-app/carbon#754]
### Expected Behavior
I want to login via facebook/email and have possibility to see my saved snippets and sort them oin collections (Since I use carbon for articles - so each article has a collection of snippets)
### Actual Behavior
I can only save link to specific snippet myself to some notes app.

**Comment by mfix22** [comment]
@kievsash this feature was just release with version 4.0.0!! You can click "Sign Up" to try it out:

<img width="969" alt="Screenshot 2019-08-14 09 51 17" src="https://user-images.githubusercontent.com/8397708/63039865-138f7600-be79-11e9-9ef1-293fad03f93c.png">

**Comment by kievsash** [comment]
Nice! Thank you for great work!
