### ISSUE TITLE
Caret is nearly impossible to see on some dark themes

### ISSUE THREAD

**Issue by gricey432** [carbon-app/carbon#775]
**Describe the bug**
When using some dark code themes, the cursor stays black and can be hard to see.

On other themes it becomes thicker and matches the colour of my `->` in python (e.g. see One Dark below)

Seen on:
- 3024 Night
- Blackboard
- Base 16 (Dark)
- Cobalt
- Duotone
- Hopscotch
- Lucario
- Material
- Monokai
- Panda
- Paraiso
- Shades of Purple
- Solarized (Dark)
- Tomorrow Night
- Twilight
- Verminal
- VSCode
- Zenburn

**To Reproduce**
1. Pick one of the above dark themes
1. Try find your cursor

**Expected behavior**
Cursor should be inverted to the background colour

**Screenshots**
Monokai:
![Screenshot_20190530_102500](https://user-images.githubusercontent.com/1611345/58599816-315f2d00-82c5-11e9-9151-56ccf63134d5.png)

One Dark:
![Screenshot_20190530_102954](https://user-images.githubusercontent.com/1611345/58599998-e98cd580-82c5-11e9-8daf-d85d9c78751b.png)

**Info (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Comment by mfix22** [comment]
https://github.com/dawnlabs/carbon/releases/tag/3.9.29

**Comment by gricey432** [comment]
Possibly the fastest ticket resolution I've ever seen. Looks great, thanks!

**Comment by mfix22** [comment]
@gricey432 🙏I appreciate you!

**Comment by Mcat12** [comment]
I'm running into this issue even after the fix.
Browser: Firefox 82.0.2
Platform: Fedora 32

**Comment by mfix22** [comment]
@Mcat12 which theme? I am not seeing this issue.

**Comment by Mcat12** [comment]
VS Code with Rust and JetBrains Mono. Here's an example:
https://carbon.now.sh/?bg=rgba%28171%2C+184%2C+195%2C+1%29&t=vscode&wt=none&l=rust&ds=true&dsyoff=20px&dsblur=68px&wc=false&wa=true&pv=0px&ph=0px&ln=false&fl=1&fm=JetBrains+Mono&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=fn%2520main%28%29%2520%257B%250A%2520%2520%2520%2520println%21%28%2522Hello%252C%2520world%21%2522%29%253B%250A%257D

**Comment by Xiaorui-Huang** [comment]
it seems that custom themes may still have this problem,
I created my on gruvbox theme for python and the cursor is hardly visible on a black background.

![image](https://user-images.githubusercontent.com/42769475/152666368-a7b71d3f-ac89-47c5-af5d-e857bc00f51e.png)

for reference, this is the theme
<img src="https://user-images.githubusercontent.com/42769475/152666402-5dc475da-d33f-499e-843e-38108b78271f.png" width="200">

**Custom theme reference**
Background: 151718
Variable: EBDBB2
Definition: 8EC07C
Operator: 8EC07C
Number: D3869B
Comment: 928374
Text: FABD2F
Attribute: 0F6FBE
Keyword: 0F6FBE
Property: 83A598
String: B8BB26
Meta: FABD2F
