### ISSUE TITLE
Feature request: To be able to change font-weight of particular text

### ISSUE THREAD

**Issue by RIP21** [carbon-app/carbon#806]
Hi there.
I'm using carbon a lot for presentations and sometimes I just want to make some sort of progression from one piece of code to another.
And sometimes I want to emphasize a little more attention to one piece or another by using different font-weight.
Right now it's possible to select some piece of text to kinda highlight it (looks awful tho and impossible to do multiple selections. Like from 4-9 line and from 12-14 in the same picture. It would be nice to change this boldness using Cmd/Ctrl + B or whatever.

Anyway thanks for your work guys! :)

**Comment by mfix22** [comment]
This is a great idea! Super similar to #548. I think this is something we should support.

**Comment by mfix22** [comment]
Happy to say that this feature was just released with version 4.0.0:

![Kapture 2019-08-14 at 9 48 16](https://user-images.githubusercontent.com/8397708/63039933-34f06200-be79-11e9-9303-7da262a3e2b1.gif)


Try it out and let me know what you think! 🙏

**Comment by Relequestual** [comment]
This is cool, but it doesn't look like it goes into the URL, which is required to be able to use it with `carbon-now-cli` it seems.

Still, awesom work. Thanks!

Should I put in a new feature request for adding a "remove formatting changes" for a selection to revert to syntax highlighted?

Use case is having only selected lines the correct colours and having other lines greyed out.

**Comment by RIP21** [comment]
Amazing stuff. Thanks a lot :)

**Comment by sugatoray** [comment]
It will be nice to be able to highlight a line (instead of/in addition to changing the font color).

cc: @mfix22
