### ISSUE TITLE
Error on background image of preset

### ISSUE THREAD

**Issue by GuiDevloper** [carbon-app/carbon#832]
First of all, i thank you all for this work of design in code :smiley:

**Describe the bug**
Changing a stored preset containing background image gives an unexpected error.

**To Reproduce**

1. In a fresh new, use a background image
2. Save as preset
3. Change any setting, then save as new preset
3. See error

**Expected behavior**
Saves two presets with same background image.

**Info:**

- OS: Windows
- Browser: Latest Chrome

**Comment by mfix22** [comment]
@GuiDevloper thanks for the kind words 😍 

For the background images, are you using Unsplash or uploading your own? If you are uploading your own, can you add an image to this thread that you are using to produce the error? 

In my testing so far, I have not been able to reproduce the issue:
<img width="80%" alt="Screenshot 2019-07-29 10 27 14" src="https://user-images.githubusercontent.com/8397708/62068927-0709ed00-b1ec-11e9-9a6c-7049678420a7.png">

**Comment by GuiDevloper** [comment]
@mfix22 wow, just discovered the full customizability of themes.

Just remembering that the preset was in settings, not themes.

I'am using Unsplash and while writing did take a new look at the errors on console:
![carbon_bug](https://user-images.githubusercontent.com/31557312/62117718-cdd88800-b292-11e9-82e3-935b64f0e933.jpg)
and after a search, received a light:

The backgroundImage url/meta stored in localStorage is creppy huge :fearful:
making the `localStorage.CARBON_PRESETS` become 3000k chars in one save
being a issue to another save that exceeds the limit (default 5000k).

Really hope this helps the team!

**Comment by mfix22** [comment]
Thanks for sharing @GuiDevloper! This was exactly what I expected. Unfortunately,  we can't really get around the `localStorage` limits and still support `backgroundImage`s in presets.

Would you rather save the presets without `backgroundImage`? 

Please also note that we are coming up with a better way to store "presets" soon that doesn't rely on `localStorage`.

**Comment by GuiDevloper** [comment]
Sorry for still continue this discussion, @mfix22.
Thinking targeting the size of save, whatever the storage:
Database, `localStorage` with limit extended or downloading a plain-text file.

Depending on current future plan, would be cool think in using another approach beyond Base64, like store a [image url](https://images.unsplash.com/29/night-square.jpg?ixlib=rb-1.2.1&auto=format&fit=crop&w=1359&q=80) or a way to use directly the path of local image file.

Just ideas, already it's great to have plans like that to evolve the app! :)
