### ISSUE TITLE
Every letter shows up twice

### ISSUE THREAD

**Issue by LeeMingX** [carbon-app/carbon#839]
### Detail
There are something wrong when I typed code on the carbon website.

The type of my keyboard is Apple keyboard adapts to iPad Pro. I don’t know what caused this problem, my facility or browser or the application.

### Expected Behavior
As like as common using

### Actual Behavior
It’s shows up twice while I typing every letter.

<details>
  <summary>Browser: </summary>
  
  Chrome 76.0+ on the iPad Pro
</details>

<details>
  <summary>Code Snippet (If Applicable)</summary>
  
  It’s not about code itself.
</details>

**Comment by mfix22** [comment]
@LeeMingX are you able to share a screen capture so I can better understand your issue?

**Comment by mfix22** [comment]
@LeeMingX I am assuming this is a OS issue, not related to Carbon. Let me know if that is not the case.
