### ISSUE TITLE
Custom line-number range

### ISSUE THREAD

**Issue by WeaverOfTheWeb** [carbon-app/carbon#842]
An enhancement I'd love to see in the future is the ability to set where the line-numbering starts. Sometimes I'll take a snippet from a larger file and would like the numbering to start where that snippet was taken from or a custom one to be set.

Thanks for all your work on Carbon, it's a great tool!

**Comment by mfix22** [comment]
Hey @WeaverOfTheWeb great idea! This would be super easy to add: https://codemirror.net/doc/manual.html#option_firstLineNumber

If you want, feel free to take a stab at it, otherwise I will get to this feature eventually 👍
