### ISSUE TITLE
Load selected lines from query params

### ISSUE THREAD

**Issue by mfix22** [carbon-app/carbon#843]
See https://github.com/carbon-app/carbon/issues/824#issuecomment-513694282 for context

- [x] Should use existing state/routing system

**Comment by nemesv** [comment]
I'm open to any suggestion how the solution in #878 could be improved.

There is one "change" compared to the previous behavior:

When the user uses the selected lines query params (or just manually highlight some lines) and turns off the line numbers in the editor then the selection is still visible. 
Previously the selection was kept but was not visible when the line numbers where turned off.
