### ISSUE TITLE
PNG export doesn't work on Safari

### ISSUE THREAD

**Issue by vol24pl** [carbon-app/carbon#851]
**Describe the bug**
PNG export doesn't work on Safari

**To Reproduce**
1. Open Carbon from Safari on macOS
2. Create a snippet
3. Export it to PNG

**Expected behavior**
png is downloaded

**Actual Result**
nothing happens

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: macOS 10.14.6 (18G87)
- Browser [e.g. chrome, safari]: Safari Version 12.1.2 (14607.3.9)

**Comment by mfix22** [comment]
Another CORS issue. I'll have the fix pushed up shortly. 

Sorry about this!

**Comment by mfix22** [comment]
Issue should be fixed! Apologies for the inconvenience.
