### ISSUE TITLE
Add Ethereum address to FUNDING.yml

### ISSUE THREAD

**Issue by lastmjs** [carbon-app/carbon#853]
I'd like to see an Ethereum address added to the `custom` property of the `FUNDING.yml` file for GitHub Sponsors. This would allow a canonical address to send funds to. For example, I'm building a project that allows developers to setup one recurring donation that is split between all of their dependencies with an Ethereum address: https://sustainus.io

**Comment by mfix22** [comment]
@lastmjs feel free to create a PR that adds `0x6e013395109d1b7Bd941D9E5F6BAE3ee624E63EE` to the `FUNDING.yml`
