### ISSUE TITLE
Iframe export is not working

### ISSUE THREAD

**Issue by esimov** [carbon-app/carbon#856]
Trying to embed the exported code as iframe into my website always shows the placeholder code and not the exported one. This is what the exported iframe looks like:

```
<iframe
  src="https://carbon.now.sh/embed"
  style="transform:scale(0.7); width:1024px; height:473px; border:0; overflow:hidden;"
  sandbox="allow-scripts allow-same-origin">
</iframe>
```
You can see the code section is missing. BTW this has worked until now.

**Expected behavior**

The resulted iframe should contain the actual code and not the placeholder code.

**Comment by mfix22** [comment]
@esimov you need to include the `?code=<your code>` query param in the URL of the iFrame. Can you either paste me the code you are trying to use, or a link me to the regular Carbon URL?

**Comment by esimov** [comment]
This is an example I have tried to used on my blog which is worked fine until now, but now is not working anymore:

```
<iframe
  src="https://carbon.now.sh/embed/?bg=rgba(255%2C255%2C255%2C0)&t=seti&wt=none&l=text%2Fx-go&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fm=Hack&fs=14px&lh=133%25&si=false&es=1x&wm=false&code=%252F%252F%2520Pigo%2520struct%2520defines%2520the%2520basic%2520binary%2520tree%2520components.%250Atype%2520Pigo%2520struct%2520%257B%250A%2520%2520%2520%2520%2520%2520treeDepth%2520%2520%2520%2520%2520uint32%250A%2520%2520%2520%2520%2520%2520treeNum%2520%2520%2520%2520%2520%2520%2520uint32%250A%2520%2520%2520%2520%2520%2520treeCodes%2520%2520%2520%2520%2520%255B%255Dint8%250A%2520%2520%2520%2520%2520%2520treePred%2520%2520%2520%2520%2520%2520%255B%255Dfloat32%250A%2520%2520%2520%2520%2520%2520treeThreshold%2520%255B%255Dfloat32%250A%257D"
  style="width:1024px; height:330px; border:0; overflow:hidden;"
  sandbox="allow-scripts allow-same-origin">
</iframe>
```

Now is producing the default placeholder output.

**Comment by mfix22** [comment]
I will push a fix for this issue, but you need to remove the trailing slash from `/embed/`

https://carbon.now.sh/embed?bg=rgba(255%2C255%2C255%2C0)&t=seti&wt=none&l=text%2Fx-go&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fm=Hack&fs=14px&lh=133%25&si=false&es=1x&wm=false&code=%252F%252F%2520Pigo%2520struct%2520defines%2520the%2520basic%2520binary%2520tree%2520components.%250Atype%2520Pigo%2520struct%2520%257B%250A%2520%2520%2520%2520%2520%2520treeDepth%2520%2520%2520%2520%2520uint32%250A%2520%2520%2520%2520%2520%2520treeNum%2520%2520%2520%2520%2520%2520%2520uint32%250A%2520%2520%2520%2520%2520%2520treeCodes%2520%2520%2520%2520%2520%255B%255Dint8%250A%2520%2520%2520%2520%2520%2520treePred%2520%2520%2520%2520%2520%2520%255B%255Dfloat32%250A%2520%2520%2520%2520%2520%2520treeThreshold%2520%255B%255Dfloat32%250A%257D

**Comment by esimov** [comment]
Thanks!
