### ISSUE TITLE
Invalid URL in iframe when using export -> copy embed -> Iirame option

### ISSUE THREAD

**Issue by kryz81** [carbon-app/carbon#864]
**Describe the bug**
The iframe "src" property contains invalid URL. No "/" after .../embed and before the snippet id

**To Reproduce**

1. Go to carbon.now.sh
2. Write a snippet
3. Select: export -> copy embed -> iframe option
4. Paste the copied code to your editor

**Current behavior (example url)**

<iframe
  src="https://carbon.now.sh/embedUuqelEqH2dDHNJ5qrbrO"
  style="transform:scale(0.7); width:1024px; height:473px; border:0; overflow:hidden;"
  sandbox="allow-scripts allow-same-origin">
</iframe>
 
**Expected behavior**

<iframe
  src="https://carbon.now.sh/embed/UuqelEqH2dDHNJ5qrbrO"
  style="transform:scale(0.7); width:1024px; height:473px; border:0; overflow:hidden;"
  sandbox="allow-scripts allow-same-origin">
</iframe>

**Info (please complete the following information):**
- macOS
- Chrome

**Comment by mfix22** [comment]
Thank you @kryz81 🙏

**Comment by mfix22** [comment]
`npm` is experiencing issues at the moment, and thus our deployment platform is unable to deploy this change. I will get it to production as soon as possible. Thanks!
