### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by haelbichalex** [carbon-app/carbon#865]
**Describe the bug**
An unexpected error has occurred.

**To Reproduce**

1. Go to 'https://carbon.now.sh/'
2. Click on 'Profile Picture' --> 'Snippets'
3. See error

**Expected behavior**
See Snippets.

**Screenshots**
![image](https://user-images.githubusercontent.com/15052352/64979599-54cfd700-d8b8-11e9-88e2-20ffc728f6fd.png)

**Info (please complete the following information):**

- OS: macOS
- Browser: chrome

<details>
  <summary>Code Snippet (If Applicable)</summary>
  <pre>
  
  </pre>
</details>

**Comment by mfix22** [comment]
Sorry about this issue, and I really appreciate you pointing this out — some sort of issue from a minor update in one of our dependencies. This commit 834812adebe2b5b167298464009ee5f0ede61161 fixed the issue.
