### ISSUE TITLE
Display whitespace

### ISSUE THREAD

**Issue by Relequestual** [carbon-app/carbon#877]
I was making some temporary screenshots from my editor while out of wifi range and discovered a starling difference. My editor shows white space, including vertical lines.

Generally you might think that's not super useful, but it is VERY useful when dealing with JSON, and writing say a JSON Schema.

It would be great if such an option could be added.

<3

**Comment by mfix22** [comment]
Hey @Relequestual can you post an example link to a Carbon snippet that demonstrates your issue? That way I can reproduce it and hopefully fix it. 

It would be nice to include screenshots as well that depict the difference you are noticing and want resolved. 

Thanks!

**Comment by baktiaditya** [comment]
hi @mfix22 can i try working this for my hacktoberfest?

**Comment by baktiaditya** [comment]
hi @mfix22 please kindly check #879 🙇 hopefully my PR solve this issue
