### ISSUE TITLE
Add manual config for image width

### ISSUE THREAD

**Issue by mearns** [carbon-app/carbon#880]
I'd like to be able to specify a fixed width for the image. This is particularly important when creating a series of image for an article; aesthetically, I'd like them to all be the same width.

### Expected Behavior

When auto-adjust width is not enabled, I expect a settings control to change the width of the image.

### Actual Behavior

There is no option to manually control the width of the image, only to make it auto-adjust or an unspecified fixed width.

**Comment by mearns** [comment]
Related to #1

**Comment by mfix22** [comment]
@all-contributors add @mearns for ideas

**Comment by mfix22** [comment]
@all-contributors add @mearns for ideas
