### ISSUE TITLE
Uncaught request in promise

### ISSUE THREAD

**Issue by joshuaiz** [carbon-app/carbon#884]
**Describe the bug**
Getting the following error when trying to embed an iframe generated by the web app:

Uncaught (in promise) no-response: no-response :: [{"url":"https://carbon.now.sh/embed/?bg=rgba(171%2C184%2C195%2C0)&t=material&wt=none&l=text%2Fx-php&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=0px&ph=0px&ln=false&fl=1&fm=Source%20Code%20Pro&fs=15.5px&lh=133%25&si=false&es=2x&wm=false&code..."}]
    at a.makeRequest (https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-strategies.prod.js:1:2145)

**To Reproduce**

1. Go to 'https://carbon.now.sh/'
2. Create embed of code with settings
3. See error

**Expected behavior**

Iframe embed should work properly.

**Screenshots**
<img width="1434" alt="Screen Shot 2019-10-09 at 2 33 08 PM" src="https://user-images.githubusercontent.com/1096738/66513917-c22eec00-eaa1-11e9-9c23-b120a1ad1b0c.png">

**Info (please complete the following information):**

- macOS Mojave 10.14.16
- Chrome Version 77.0.3865.90 (Official Build) (64-bit)

<details>
  <summary>Code Snippet (If Applicable)</summary>
  <pre>
  <iframe
  src="https://carbon.now.sh/embed/?bg=rgba(171%2C184%2C195%2C0)&t=material&wt=none&l=text%2Fx-php&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=0px&ph=0px&ln=false&fl=1&fm=Source%20Code%20Pro&fs=15.5px&lh=133%25&si=false&es=2x&wm=false&code=%253C%253Fphp%250A%252F*%250APlugin%2520Name%253A%2520Staff%2520CPT%250APlugin%2520URI%253A%2520https%253A%252F%252Fsb.local%252F%250ADescription%253A%2520Another%2520studio.bio%2520plugin%250AVersion%253A%25200.1.0%250AAuthor%253A%2520Joshua%2520Michaels%2520for%2520studio.bio%250AAuthor%2520URI%253A%2520https%253A%252F%252Fsb.local%250ALicense%253A%2520WTFPL%250A*%252F%250A%250A%252F%252F%2520Register%2520Custom%2520Post%2520Type%250Afunction%2520sb_staff_cpt()%2520%257B%250A%250A%2520%2520%2520%2520%2524labels%2520%253D%2520array(%250A%2520%2520%2520%2520%2520%2520%2520%2520'name'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520_x(%2520'Staff'%252C%2520'Post%2520Type%2520General%2520Name'%252C%2520'platetheme'%2520)%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'singular_name'%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520_x(%2520'Staff'%252C%2520'Post%2520Type%2520Singular%2520Name'%252C%2520'platetheme'%2520)%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'menu_name'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520__(%2520'Staff'%252C%2520'platetheme'%2520)%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'name_admin_bar'%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520__(%2520'Staff'%252C%2520'platetheme'%2520)%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520%252F%252F%2520...rest%2520of%2520labels%250A%2520%2520%2520%2520)%253B%250A%2520%2520%2520%2520%2524rewrite%2520%253D%2520array(%250A%2520%2520%2520%2520%2520%2520%2520%2520'slug'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520'staff'%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'with_front'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520true%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'pages'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520true%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'feeds'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520true%252C%250A%2520%2520%2520%2520)%253B%250A%2520%2520%2520%2520%2524args%2520%253D%2520array(%250A%2520%2520%2520%2520%2520%2520%2520%2520'label'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520__(%2520'Staff'%252C%2520'platetheme'%2520)%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'description'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520__(%2520'Staff%2520Custom%2520Post%2520Type'%252C%2520'platetheme'%2520)%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'labels'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520%2524labels%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'supports'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520array(%2520'title'%252C%2520'editor'%252C%2520'thumbnail'%252C%2520'revisions'%252C%2520'page-attributes'%2520)%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'taxonomies'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520array(%2520'category'%252C%2520'post_tag'%2520)%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'hierarchical'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520false%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'public'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520true%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'show_ui'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520true%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'show_in_menu'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520true%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'menu_position'%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%25205%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'menu_icon'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520'dashicons-groups'%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'show_in_admin_bar'%2520%2520%2520%2520%2520%253D%253E%2520true%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'show_in_nav_menus'%2520%2520%2520%2520%2520%253D%253E%2520true%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'can_export'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520true%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'has_archive'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520'staff'%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'exclude_from_search'%2520%2520%2520%253D%253E%2520false%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'publicly_queryable'%2520%2520%2520%2520%253D%253E%2520true%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'rewrite'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520%2524rewrite%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'capability_type'%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520'page'%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520'show_in_rest'%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%253D%253E%2520true%252C%250A%2520%2520%2520%2520)%253B%250A%2520%2520%2520%2520register_post_type(%2520'sb_staff'%252C%2520%2524args%2520)%253B%250A%250A%257D%250Aadd_action(%2520'init'%252C%2520'sb_staff_cpt'%252C%25200%2520)%253B%250A%253F%253E"
  style="transform:scale(0.7); width:1024px; height:473px; border:0; overflow:hidden;"
  sandbox="allow-scripts allow-same-origin">
</iframe>
  </pre>
</details>

**Comment by Rmnlly** [comment]
Hey so I was able to reproduce this issue really, I tried to copy a new embed, even embed it in the page by altering the html and it works fine.

Like I'm able to go to export > copy Iframe, then past it into some valid HTML and not get an error in the console. 

It does appear others have been having a similiar issue [here:](https://github.com/nuxt-community/pwa-module/issues/176) however

**Comment by joshuaiz** [comment]
Is there any particular HTML that the iframe needs to be wrapped in?

I copied and pasted directly into a WordPress post editor and was getting the error.

A few days ago I was able to copy and paste the iframe code without issue so it is something in the latest version I think.

**Comment by nemesv** [comment]
I also had a look into this and the issue has something to do with the length of the source code (or actually the length of the URL)

I've created a fiddle with your original and a truncated example: https://jsfiddle.net/7mt3nxz6/ where the truncated example works fine, and your original iframe src reuqest returns "failed" in Chrome

![image](https://user-images.githubusercontent.com/251330/66596104-917fad00-eb9c-11e9-930e-e49564926931.png)

If I use the same URL in Postman it is working fine. Next I tried to check the HTTP requests using Fiddler but to my surprise when Fiddler was running both request were 200 OK in Chrome...

My guess is that issue has something to do with Chrome interacting with the hosting provider zeit

**Comment by joshuaiz** [comment]
Ok it looks like longer code snippets cause this. When I shorten them I don't have the issue. So, it looks like 1000 characters is not quite the limit but something less.

I guess this is resolved for now.

**Comment by mfix22** [comment]
@joshuaiz there is a URL limit in all browsers (they vary browser to browser) that we try and defend against, but we can't really do anything about. 

Sorry about the inconvenience, and thank you to everyone that helped debug this! 🙏
