### ISSUE TITLE
URI components not being decoded from URL export

### ISSUE THREAD

**Issue by jpegsarebad** [carbon-app/carbon#889]
**Describe the bug**
When using the 'copy URL' export method, the URL that is copied displays spaces and other URI-encoded symbols without decoding them. A space character, for example, is shown as `%20`.

**To Reproduce**

1. Go to [carbon, with text typed.](https://carbon.now.sh/?bg=rgba(171%25252C%252520184%25252C%252520195%25252C%2525201)&t=nord&wt=none&l=text&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%252525&si=false&es=2x&wm=false&code=const%2520pluckDeep%2520%253D%2520key%2520%253D%253E%2520obj%2520%253D%253E%2520key.split(%27.%27).reduce((accum%252C%2520key)%2520%253D%253E%2520accum%255Bkey%255D%252C%2520obj)%250A%250Aconst%2520compose%2520%253D%2520(...fns)%2520%253D%253E%2520res%2520%253D%253E%2520fns.reduce((accum%252C%2520next)%2520%253D%253E%2520next(accum)%252C%2520res)%250A%250Aconst%2520unfold%2520%253D%2520(f%252C%2520seed)%2520%253D%253E%2520%257B%250A%2520%2520const%2520go%2520%253D%2520(f%252C%2520seed%252C%2520acc)%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520const%2520res%2520%253D%2520f(seed)%250A%2520%2520%2520%2520return%2520res%2520%253F%2520go(f%252C%2520res%255B1%255D%252C%2520acc.concat(%255Bres%255B0%255D%255D))%2520%253A%2520acc%250A%2520%2520%257D%250A%2520%2520return%2520go(f%252C%2520seed%252C%2520%255B%255D)%250A%257D)
2. Select the 'URL' option under 'Export'
3. Paste the link into your browser, and see the many URI components that have not been decoded.

**Expected behavior**
The text exported bu the 'copy URL' option should be the same as the text initially entered.

**Screenshots**
![Initial text](https://user-images.githubusercontent.com/41037937/66964536-f0ce3900-f044-11e9-8777-2f81609cc235.png)
![Text shown from URL](https://user-images.githubusercontent.com/41037937/66964539-f3309300-f044-11e9-9fa3-06ced9a34a9d.png)

**Info:**

- OS: Arch Linux
- Browser: Firefox

**Comment by mfix22** [comment]
Hey @jpegsarebad thanks for sharing this. This is actually workin as intended, for pasting the URL to places like Medium. Medium decoded the URL, so this copy button makes it easier for the user to get the pre-encoded URL for pasting. 

If you would like the regular URL instead, you can just copy if from the browser location input.

👍

**Comment by jpegsarebad** [comment]
Thanks for the help!

**Comment by dncrews** [comment]
I spent 20 minutes writing this same bug report. This was especially problematic using the PWA, since you have to dig into the menus to get to the original URL. What would it take to get an "Encoded URL" vs "URL" option?

**Comment by mfix22** [comment]
@dncrews you are right — this is a communication problem, and we should fix this. 

I'm going to open a new issue so we can improve the copy URL menu
