### ISSUE TITLE
Cannot export png on safari mac os

### ISSUE THREAD

**Issue by kkew3** [carbon-app/carbon#890]
It happens again (#851). Thanks!

<details>
  <summary>Browser: </summary>
  
  Safari Version 13.0.1 (14608.2.11.1.11)
</details>

<details>
  <summary>Operating System: </summary>
  macOS Majove 10.14.6
</details>

<details>
  <summary>Code Snippet (If Applicable)</summary>
  
</details>

**Comment by mfix22** [comment]
@kkew3 I am having trouble reproducing this error. Can you post a link or code snippet that you can produce it on?

**Comment by kkew3** [comment]
This was the snippet I encountered issue yesterday, but somehow I can't reproduce it today. So I'm closing it now. Thanks.

```python
import sys
import itertools
import numpy as np
keys = sys.argv[1].split(',')
index = 'filename'
assert index not in keys
print(','.join([index] + keys))
for filename in filter(None, map(str.rstrip, sys.stdin)):
    with np.load(filename) as data:
        print(','.join(map(str, itertools.chain(
            [filename], (data[k] for k in keys)))))
```
