### ISSUE TITLE
Styling palette annoyance

### ISSUE THREAD

**Issue by arturhun** [carbon-app/carbon#899]
The styling palette (Bold, Underline, Italic, color) that appears on double click, is soooo annoying!
I need to make an extra click every now and then in order to make it go away and reveal my code.
Neither will it disappear on `esc`
Please add a setting to turn it off completely.

**Comment by mfix22** [comment]
@arturhun thanks so much for bringing this up! I will definitely look into supporting this.

**Comment by mfix22** [comment]
@arturhun do you want it completely out of the way, or would it be fine if we pop it up out of the way, like this maybe: 

<img width="973" alt="Screenshot 2019-10-25 12 47 05" src="https://user-images.githubusercontent.com/8397708/67599798-a70cdf00-f725-11e9-9d9a-2fdcd6cdf770.png">

**Comment by arturhun** [comment]
@mfix22 While I don't believe I should decide upon it just by myself :) if you ask me then my vote would be to add an icon button, next to the cog icon, perhaps - it would comply with the convention the WYSIWYG text editors have set.

**Comment by mfix22** [comment]
@arturhun don't worry, I agree with you on this one 🙂
