### ISSUE TITLE
A lot of external API calls to the Stripe payment gateway

### ISSUE THREAD

**Issue by esimov** [carbon-app/carbon#904]
**Describe the bug**
In case there are multiple code snippets included, the full page load take a lot of time. Inspecting the network tab in the web developer tool I found that there are a lot of external Stripe API calls. Why they are needed? Calling an external payment API is not very assuring and also blocks the webpage loading. Could they be eliminated? Are they needed?

**Screenshots**
![image](https://user-images.githubusercontent.com/883386/68119182-b3a1ec00-ff0a-11e9-827b-d0c7f04c96e1.png)

**Comment by mfix22** [comment]
Closed with d18695807517382f1f51603a61e2042aa8e5cbe0
