### ISSUE TITLE
Export URL Not Decoded Properly

### ISSUE THREAD

**Issue by Kogam22** [carbon-app/carbon#905]
**Describe the bug**
Exporting the Image as URL copies a link to the clipboard. But does that link actually work ? Nope. Actually the URI is not getting decoded properly. Idk if its `decodeURIComponent` or `decodeURI` but yeah, that's the problem(most probably) 😅 

Link here : [Link](https://carbon.now.sh/?bg=rgba(171%252C%2520184%252C%2520195%252C%25201)&t=seti&wt=none&l=auto&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%2525&si=false&es=2x&wm=false&code=const%252520pluckDeep%252520%25253D%252520key%252520%25253D%25253E%252520obj%252520%25253D%25253E%252520key.split(%2527.%2527).reduce((accum%25252C%252520key)%252520%25253D%25253E%252520accum%25255Bkey%25255D%25252C%252520obj)%25250A%25250Aconst%252520compose%252520%25253D%252520(...fns)%252520%25253D%25253E%252520res%252520%25253D%25253E%252520fns.reduce((accum%25252C%252520next)%252520%25253D%25253E%252520next(accum)%25252C%252520res)%25250A%25250Aconst%252520unfold%252520%25253D%252520(f%25252C%252520seed)%252520%25253D%25253E%252520%25257B%25250A%252520%252520const%252520go%252520%25253D%252520(f%25252C%252520seed%25252C%252520acc)%252520%25253D%25253E%252520%25257B%25250A%252520%252520%252520%252520const%252520res%252520%25253D%252520f(seed)%25250A%252520%252520%252520%252520return%252520res%252520%25253F%252520go(f%25252C%252520res%25255B1%25255D%25252C%252520acc.concat(%25255Bres%25255B0%25255D%25255D))%252520%25253A%252520acc%25250A%252520%252520%25257D%25250A%252520%252520return%252520go(f%25252C%252520seed%25252C%252520%25255B%25255D)%25250A%25257D%25250Aa)

**To Reproduce**

1. Go to the carbon website.
2. Click on add a few extra lines at the end of the template.
3. Click Export -> URL and Open the URL in new tab.

**Expected behavior**
Code should be displayed properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/22547069/68145617-38692600-ff5c-11e9-82aa-873488957c83.png)
**Info (please complete the following information):**

- OS : Windows
- Browser [e.g. chrome, safari]: Firefox(Latest Stable)

**Comment by mfix22** [comment]
See this comment: https://github.com/carbon-app/carbon/issues/889#issuecomment-542936104

**Comment by Kogam22** [comment]
> See this comment: [#889 (comment)](https://github.com/carbon-app/carbon/issues/889#issuecomment-542936104)

But ... I guess it would be better to just notify the user how to copy the link for just sharing. Thanks anyways.

**Comment by mfix22** [comment]
Definitely! I will look into how we can best convey this.
