### ISSUE TITLE
Wordpress plugin

### ISSUE THREAD

**Issue by nebrass** [carbon-app/carbon#908]
Hello Guys,

First of all, thank you for creating and maintaining this great tool !

I have a **feature request**: can you provide us a **Wordpress plugin** to **share source code** inside blogs post.

Thank you !

**Comment by mfix22** [comment]
@nebrass this is a great idea! This is not something the Carbon core team is going to create or support, but if someone from the community creates it, we would be happy to add it to our Community section on our README

**Comment by mfix22** [comment]
Closing since our team isn't going to create this — happy to add it to our README is someone creates this!
