### ISSUE TITLE
Feature Request: Support for Command Line images

### ISSUE THREAD

**Issue by KaustubhDamania** [carbon-app/carbon#911]
### Expected Behavior

Similar to code images, there can be a feature for generating an image of command line.<br>

![carbon](https://user-images.githubusercontent.com/33577657/69982868-72c5e300-155b-11ea-8085-de18cf382f73.png)

Maybe something like the pic above, keeping the window as it is and changing color of some text. For e.g. The text "kaustubhdamania@kaustubhdamania-X510UNR" could be green like #00ffbe and the current directory text could be a blue color like #0277bd.

### Actual Behavior

<details>
  <summary>Browser: </summary>
  
</details>

<details>
  <summary>Code Snippet (If Applicable)</summary>
  
</details>

**Comment by mfix22** [comment]
@KaustubhDamania you can actually select specific sections of text and apply individual styles to each. 

E.g.
![carbon](https://user-images.githubusercontent.com/8397708/70025229-3a210c00-1551-11ea-967c-5212ebe70c57.png)

To do so:
1. Select text
2. Click palette button (🎨)
3. Select your color, bold, italics, underline

I think this is the best option for your use case while being able to support many variations, not just terminal prompts. 

Does this work for you?

**Comment by KaustubhDamania** [comment]
Okay, I did not know that specific text could also be styled :sweat_smile: <br>
Yeah, this works for me, although I'd still suggest to add an extra option for Terminal in syntax highlight drop-down because it'll be easier and faster to highlight required text that way.

**Comment by mfix22** [comment]
Awesome! 

Also, there are a couple terminal languages available, `Bash` and `PowerShell`, just ICYMI 🙂
