### ISSUE TITLE
existing iframe export urls need an extra embed parameter to see only code

### ISSUE THREAD

**Issue by kbondanza** [carbon-app/carbon#914]
**Describe the bug**

existing iframe export urls need an extra embed parameter to see only code.

It looks like the iframe export url structure changed today, when I exported code via the iframe option this afternoon around 2pm eastern, I got the first url, added it to a presentation, then went back to the presentation around 6pm and the entire carbon.now.sh page shows in the presentation instead of the code snippet I was trying to embed. I realized adding an extra `embed` to the url, seems to fix this. 

Is this change intended?

I believe this changed occurred in either 4.3.11 or 4.3.12.

**To Reproduce**

Go to:
https://carbon.now.sh/embed/?bg=rgba(255%2C255%2C255%2C0)&t=night-owl&wt=none&l=javascript&ds=false&dsyoff=20px&dsblur=68px&wc=false&wa=true&pv=32px&ph=10px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=4x&wm=false&code=function%2520firstPromise()%2520%257B%250A%2520%2520return%2520new%2520Promise(resolve%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520setTimeout(resolve%252C%25201000%252C%2520%27%25F0%259F%2598%25BA%27)%250A%2520%2520%257D)%250A%257D%250A%250Afunction%2520secondPromise(element)%2520%257B%250A%2520%2520return%2520new%2520Promise(resolve%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520setTimeout(resolve%252C%2520500%252C%2520%27%25F0%259F%2590%25B6%27)%250A%2520%2520%257D)%250A%257D%250A%250Afunction%2520thirdPromise(element)%2520%257B%250A%2520%2520return%2520new%2520Promise(resolve%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520setTimeout(resolve%252C%2520800%252C%2520%27%25F0%259F%2590%25A2%27)%250A%2520%2520%257D)%250A%257D%250A%250Aconst%2520animals%2520%253D%2520Promise.all(%255B%250A%2520%2520firstPromise()%252C%250A%2520%2520secondPromise()%252C%250A%2520%2520thirdPromise()%250A%255D).then(function(value)%2520%257B%250A%2520%2520return%2520value%250A%257D)%250A

Compare to:
https://carbon.now.sh/embed/embed/?bg=rgba(255%2C255%2C255%2C0)&t=night-owl&wt=none&l=javascript&ds=false&dsyoff=20px&dsblur=68px&wc=false&wa=true&pv=32px&ph=10px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=4x&wm=false&code=function%2520firstPromise()%2520%257B%250A%2520%2520return%2520new%2520Promise(resolve%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520setTimeout(resolve%252C%25201000%252C%2520%27%25F0%259F%2598%25BA%27)%250A%2520%2520%257D)%250A%257D%250A%250Afunction%2520secondPromise(element)%2520%257B%250A%2520%2520return%2520new%2520Promise(resolve%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520setTimeout(resolve%252C%2520500%252C%2520%27%25F0%259F%2590%25B6%27)%250A%2520%2520%257D)%250A%257D%250A%250Afunction%2520thirdPromise(element)%2520%257B%250A%2520%2520return%2520new%2520Promise(resolve%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520setTimeout(resolve%252C%2520800%252C%2520%27%25F0%259F%2590%25A2%27)%250A%2520%2520%257D)%250A%257D%250A%250Aconst%2520animals%2520%253D%2520Promise.all(%255B%250A%2520%2520firstPromise()%252C%250A%2520%2520secondPromise()%252C%250A%2520%2520thirdPromise()%250A%255D).then(function(value)%2520%257B%250A%2520%2520return%2520value%250A%257D)%250A

**Screenshots**

`https://carbon.now.sh/embed/?` url structure 
<img width="1313" alt="Screen Shot 2019-12-08 at 7 11 56 PM" src="https://user-images.githubusercontent.com/8070092/70399031-dc783e00-19ee-11ea-957a-1dd396bd1779.png">

`https://carbon.now.sh/embed/embed/?` url structure
<img width="897" alt="Screen Shot 2019-12-08 at 7 11 36 PM" src="https://user-images.githubusercontent.com/8070092/70399030-dc783e00-19ee-11ea-8265-6cae46ae3b13.png">

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: macOS
- Browser [e.g. chrome, safari]: Chrome

**Comment by mfix22** [comment]
The correct address is https://carbon.now.sh/embed?bg=rgba(255%2C255%2C255%2C0)&t=night-owl&wt=none&l=javascript&ds=false&dsyoff=20px&dsblur=68px&wc=false&wa=true&pv=32px&ph=10px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=4x&wm=false&code=function%2520firstPromise()%2520%257B%250A%2520%2520return%2520new%2520Promise(resolve%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520setTimeout(resolve%252C%25201000%252C%2520%27%25F0%259F%2598%25BA%27)%250A%2520%2520%257D)%250A%257D%250A%250Afunction%2520secondPromise(element)%2520%257B%250A%2520%2520return%2520new%2520Promise(resolve%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520setTimeout(resolve%252C%2520500%252C%2520%27%25F0%259F%2590%25B6%27)%250A%2520%2520%257D)%250A%257D%250A%250Afunction%2520thirdPromise(element)%2520%257B%250A%2520%2520return%2520new%2520Promise(resolve%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520setTimeout(resolve%252C%2520800%252C%2520%27%25F0%259F%2590%25A2%27)%250A%2520%2520%257D)%250A%257D%250A%250Aconst%2520animals%2520%253D%2520Promise.all(%255B%250A%2520%2520firstPromise()%252C%250A%2520%2520secondPromise()%252C%250A%2520%2520thirdPromise()%250A%255D).then(function(value)%2520%257B%250A%2520%2520return%2520value%250A%257D)%250A

I will update the code to remove the trailing slash ASAP, but in the meantime you can delete it locally as a work around
