### ISSUE TITLE
iframe exports are not supported for saved snippets

### ISSUE THREAD

**Issue by kbondanza** [carbon-app/carbon#915]
**Describe the bug**
New iframe export urls are broken

I'm trying to export this snippet to an iframe, https://carbon.now.sh/R1akLq42QmwZxET5KwoV, however the src generated below doesn't display my snippet.

Generated code
```
<iframe
  src="https://carbon.now.sh/embed/R1akLq42QmwZxET5KwoV"
  style="transform:scale(0.7); width:1024px; height:473px; border:0; overflow:hidden;"
  sandbox="allow-scripts allow-same-origin">
</iframe> 
```

**To Reproduce**

1. Go to https://carbon.now.sh/R1akLq42QmwZxET5KwoV
2. Click on copy embed iframe
3. then go to: https://carbon.now.sh/embed/R1akLq42QmwZxET5KwoV and see that the snippets do not match, the snippet displayed is the carbon demo snippet

**Expected behavior**

See my snippet in the embedded iframe instead of the carbon demo snippet

**Screenshots**

My snippet code:
<img width="1097" alt="Screen Shot 2019-12-08 at 7 24 27 PM" src="https://user-images.githubusercontent.com/8070092/70399273-87d5c280-19f0-11ea-934a-74b7f01c6616.png">

What I get in the embedded iframe:
<img width="1118" alt="Screen Shot 2019-12-08 at 7 24 56 PM" src="https://user-images.githubusercontent.com/8070092/70399274-87d5c280-19f0-11ea-96e2-4591c8584abd.png">

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: macOS
- Browser [e.g. chrome, safari]: Chrome

**Comment by mfix22** [comment]
We currently only support iFrame exports for GitHub gists, not Carbon snippets. I will mark this feature as an enhancement to be considered.
