### ISSUE TITLE
Allow defining custom keywords in settings

### ISSUE THREAD

**Issue by dzikoysk** [carbon-app/carbon#920]
It could be great to be able to add some new keywords in settings. It might be useful in using predefined syntaxes for unsupported languages

**Comment by mfix22** [comment]
@dzikoysk we allow you to highlight specific pieces of text manually — would this work for your use case? Or do you want all of these keywords to match the same color? 

Thanks for posting this idea 🙂

**Comment by dzikoysk** [comment]
Umm... I think it's half-way solution. It allows you to fix/improve some details of the snippet, but it does not really allows you to support a new language/custom syntax. 

For instance, there is some presets with language definitions:

![obraz](https://user-images.githubusercontent.com/4235722/71723984-e6932e00-2e2e-11ea-8040-360cb0c1a1fe.png)

It could be transformed into a some kind of text area where we can load presets (matching rules for the given language) and then, if needed, we can just edit these rules.

**Comment by mfix22** [comment]
@dzikoysk I appreciate your suggestion; however, this feature is too complex for Carbon's use case. 
We want it to be dead simple for folks to use, and not have to think too much about the specifics. 

If others suggest this in the future, I will definitely reconsider. Thanks!

**Comment by dzikoysk** [comment]
:<
