### ISSUE TITLE
Enable copy image to clipboard export

### ISSUE THREAD

**Issue by technoknol** [carbon-app/carbon#921]
### Expected Behavior
Copy to clipboard feature would be good, as one can directly send picture instead of filling up disk space. 
### Actual Behavior
Only export option is available.

**Comment by mfix22** [comment]
Notes for me: we could enable this across some browsers easily with: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard

**Comment by technoknol** [comment]
I may send PR for this.

**Comment by mfix22** [comment]
@technoknol go for it! I might update the design of where the feature will go, but that would still be a lot of help 🙂
