### ISSUE TITLE
[export bug] comment renders into next line, painting over next line

### ISSUE THREAD

**Issue by phryneas** [carbon-app/carbon#926]
Hi there,

so I have a screen that renders weirdly:
![carbon](https://user-images.githubusercontent.com/4282439/72011337-e2657700-3259-11ea-9abc-62a61ccad89a.png)

Obviously, the comment shouldn't be rendered into the next line like that.

<details>
  <summary>Browser: </summary>
  Firefox 69.0.1 
</details>

<details>
  <summary>Code Snippet</summary>

[https://carbon.now.sh/DSvQlK1qbxkq9bOgMAih](https://carbon.now.sh/DSvQlK1qbxkq9bOgMAih)

```ts
// calling setTimeout with a inline callback function to provide a parameter
function delay(data) {
  return new Promise(resolve => setTimeout(() => resolve(data), 1000))
};

// calling setTimeout with the target function and the parameter directly
function delay(data) {
  return new Promise(resolve => setTimeout(resolve, 1000, data))
};
```
</details>

If you need anything else, please ping me :)

**Comment by phryneas** [comment]
This might be a duplicate of https://github.com/carbon-app/carbon/issues/743 - if you agree, feel free to close this.

**Comment by mfix22** [comment]
@phryneas which operating system were you using?

**Comment by phryneas** [comment]
Linux - NixOS 19.09 to be specific.

**Comment by mfix22** [comment]
Yeah this is most definitely a duplicate. Thank you for posting though! 🙂
