### ISSUE TITLE
Doesn't work on the ms edge

### ISSUE THREAD

**Issue by Gaojianli** [carbon-app/carbon#928]
**Describe the bug**
While trying to open https://carbon.now.sh/ on the ms edge, the inputbox doesn't show at all. Like following:
![image](https://user-images.githubusercontent.com/19235246/72128170-f40b6380-33ac-11ea-882a-a3b9308daae1.png)
And you will get an error in the console:
![image](https://user-images.githubusercontent.com/19235246/72128187-071e3380-33ad-11ea-89fe-51e21b7047fe.png)
![image](https://user-images.githubusercontent.com/19235246/72128196-0eddd800-33ad-11ea-8520-ff0e525c787b.png)
It seems that [the ms edge doesn't support the spread operator at all](https://www.caniuse.com/#feat=mdn-javascript_operators_spread_spread_in_destructuring
)

**To Reproduce**
Just open https://carbon.now.sh/  on ms edge browser. On my PC, i use Microsoft Edge 44.18362.449.0 and the EdgeHTML is 18.18363

**Expected behavior**
The inputbox show

**Screenshots**
![image](https://user-images.githubusercontent.com/19235246/72128170-f40b6380-33ac-11ea-882a-a3b9308daae1.png)
![image](https://user-images.githubusercontent.com/19235246/72128187-071e3380-33ad-11ea-89fe-51e21b7047fe.png)
![image](https://user-images.githubusercontent.com/19235246/72128196-0eddd800-33ad-11ea-8520-ff0e525c787b.png)
**Info (please complete the following information):**

- OS Windows
- Microsoft Edge 44.18362.449.0

**Comment by mfix22** [comment]
@Timer does Next.js not transpile spread operators?  

@Gaojianli potentially this is an issue with one of our dependencies. Can you tell which dependency this code is coming from? You should be able to tell by searching through the `node_modules`

**Comment by Timer** [comment]
@mfix22 Next.js transpiles spread operators within first-party code.

If one of your `node_modules` deps is shipping with it, it will not be compiled.

**Comment by mfix22** [comment]
This could be the line causing it: https://github.com/graphql/graphiql/blob/master/packages/graphql-language-service-parser/src/onlineParser.ts#L238
