### ISSUE TITLE
Solidity highlighting not working

### ISSUE THREAD

**Issue by fzeoli** [carbon-app/carbon#935]
When choosing Solidity as the language no highlighting seems to happen.

**To Reproduce**
See https://carbon.now.sh/kN5PIVd3SAzGLtrfiyyb

**Expected behavior**
Syntax highlighting.

**Screenshots**
![image](https://user-images.githubusercontent.com/232174/72922955-cae3bf00-3d2c-11ea-969f-1d5e3dc5c7ca.png)

**Info (please complete the following information):**

macOS Catalina 10.15.1, Chrome 78.0.3904.108 (Official Build) (64-bit)

**Comment by mfix22** [comment]
@alincode can you take a brief look?

**Comment by StErMi** [comment]
hi there, Solidity highlighting is still not working. I'm testing from Chome (last stable version) on macOS

**Comment by mfix22** [comment]
> same here :(

Feel free to open a PR to fix the solidity highlighting.

**Comment by Yhozen** [comment]
Still not working
