### ISSUE TITLE
Padding 0px: Image contains black borders (top & bottom) when copying to clipboard

### ISSUE THREAD

**Issue by mkellenbenz** [carbon-app/carbon#944]
![image](https://user-images.githubusercontent.com/8045559/73911013-355e3880-48b1-11ea-82fd-bd913100b6f4.png)

Config:
{ 
   "paddingVertical":"0px",
   "paddingHorizontal":"0px",
   "backgroundImage":null,
   "backgroundImageSelection":null,
   "backgroundMode":"color",
   "backgroundColor":"rgba(250,250,250,1)",
   "dropShadow":false,
   "dropShadowOffsetY":"0px",
   "dropShadowBlurRadius":"0px",
   "theme":"one-light",
   "windowTheme":"sharp",
   "language":"auto",
   "fontFamily":"Hack",
   "fontSize":"15.5px",
   "lineHeight":"137%",
   "windowControls":false,
   "widthAdjustment":true,
   "lineNumbers":false,
   "firstLineNumber":1,
   "exportSize":"2x",
   "watermark":false,
   "squaredImage":false,
   "hiddenCharacters":false,
   "loading":false,
   "icon":"/static/presets/1.png",
   "isVisible":true,
   "highlights":{ 
      "background":"rgba(250,250,250,1)",
      "keyword":"rgba(86,156,214,1)",
      "definition":"rgba(70,201,176,1)",
      "comment":"rgba(96,139,78,1)"
   }
}

### Expected Behavior
When copying the image to clipboard and afterwards pasting it somewhere it contains a black border at the top and bottom. If you're exporting the image as PNG it doesn't contain these.

### Actual Behavior

When copying the image to clipboard the image should not contain any border when padding is 0px.

**Comment by mfix22** [comment]
Thanks for posting this — I cannot recreate this issue. Which browser and operating system are you using?

**Comment by mfix22** [comment]
@mkellenbenz Thanks for posting this — I cannot recreate this issue. Which browser and operating system are you using?

**Comment by mfix22** [comment]
Will reopen if we can reproduce the issue! 👍 

Need to know which browser/operating system was being used though.
