### ISSUE TITLE
Don't repeat photographer copyright credit

### ISSUE THREAD

**Issue by UlisesGascon** [carbon-app/carbon#945]
**Describe the bug**

**To Reproduce**

![bug](https://user-images.githubusercontent.com/5110813/74044826-02f52e00-49cc-11ea-80f8-76f21b3139be.gif)
_Added a gif with explanation_

As you can see the copyright message keeps the previous one too.

<img width="604" alt="Captura de pantalla 2020-02-07 a las 17 06 08" src="https://user-images.githubusercontent.com/5110813/74044905-27e9a100-49cc-11ea-91b6-f0ea714207ba.png">

**Expected behavior**
To keep the last copyright reference only.

**Info (please complete the following information):**

- OS macOS
- Browser chrome and Brave

I can try to find the the bug a send a PR, any suggestion? BTW This is one of the most useful tool ever. You are doing a amazing job ❤️

**Comment by mfix22** [comment]
@UlisesGascon the reason we did it this way is that we don't want to force the photographer credit _format_ on people — we want to allow people to present it how they want, and edit it (especially for other languages that don't use `//` for comments)

I'll leave this open, especially if others agree we should just force the format.

**Comment by UlisesGascon** [comment]
Thanks for the clarification @mfix22! Makes sense to me :-)

**Comment by mfix22** [comment]
@UlisesGascon cool! 🙂 On second thought though, I think we can do better. Opening a PR now…
