### ISSUE TITLE
Add a title to the titlebar

### ISSUE THREAD

**Issue by mattbrailsford** [carbon-app/carbon#952]
I'm working on a presentation using carbon code snippets as screenshots and thought it would be really handy to be able to give the file a title.

![sample](https://user-images.githubusercontent.com/527305/75478243-8683b880-5995-11ea-8260-ee0512fd41a3.png)

**Comment by mfix22** [comment]
This already exists! You just have to click in the center of the title: 

![carbon](https://user-images.githubusercontent.com/8397708/75599378-3837ed80-5a59-11ea-9fc6-72a033b91412.png)

Thanks for posting 👍
