### ISSUE TITLE
Gitpod Automated Setup for contributing is broken.

### ISSUE THREAD

**Issue by nisarhassan12** [carbon-app/carbon#963]
I'll shortly make a Pr with the fix.

![image](https://user-images.githubusercontent.com/46004116/76416071-30af0780-63bc-11ea-93b9-160fee06aafc.png)

**Comment by nisarhassan12** [comment]
It failed due to node version incompatibility:

![image](https://user-images.githubusercontent.com/46004116/76416456-f3974500-63bc-11ea-94ff-d9abcdb9de3e.png)

**Comment by mfix22** [comment]
@anudeepreddy can you take a look at this? I am completely unfamiliar with GitPod, and at the moment it doesn't feel like it is providing much value for the maintenance cost. 

I'd be happy to keep the `gitpod.yml` around, if it works with our existing tooling 👍

**Comment by anudeepreddy** [comment]
Hey @mfix22 , I was going through the recent changes and there is something I found, for which i need clarification from you. I noticed that the node engine in package.json is set to 12.x(this is the major reason why the Gitpod setup is broken), but you are using node 10.x for your CI. Can you please clarify this for me. Is it done on purpose?

One more thing, your contribution guide asks the contributors to use yarn, but the current code fails to run on node version 10.x using yarn (works fine with npm). So please do clarify about choosing node engine as 12.x in package.json and using yarn in contribution guide(The code cannot be run using yarn for node version less than 12.x).
Thanks @nisarhassan12 for bringing this to notice.
@mfix22 It will be helpful for me to fix this setup if you clarify me with the above regard.
Thanks

**Comment by nisarhassan12** [comment]
Thanks! @anudeepreddy :slightly_smiling_face:  FYI I have already fixed it in https://github.com/carbon-app/carbon/pull/965

**Comment by mfix22** [comment]
@anudeepreddy the reason it is set to `12.x` in our package.json is because Now looks at that value to set which environment the web app will be built/deployed to. 

Since this is the version we use in production, it is preferred that users develop using that Node version as well. I can add a point to use the correct Node version to the contributing guide. 

As for fixing this issue, sounds like we just need to update our CI to also use Node version 12 — I will take a look into this, but if someone else gets to it first, I'd be happy to accept a PR for it. 

Thank you @anudeepreddy and @nisarhassan12 🙏

**Comment by mfix22** [comment]
@all-contributors add @anudeepreddy for code

**Comment by mfix22** [comment]
@all-contributors add @anudeepreddy for bug

**Comment by mfix22** [comment]
@all-contributors add @nisarhassan12  for code

**Comment by mfix22** [comment]
@all-contributors add @nisarhassan12 for bug

**Comment by mfix22** [comment]
@nisarhassan12, @anudeepreddy any updates here? Does GitPod support `12.x` now?

**Comment by anudeepreddy** [comment]
Yes, it does support 12.x now. Sorry, I was a bit busy with my classes with this lockdown in effect (COVID-19)

**Comment by nisarhassan12** [comment]
The Gitpod setup works now 
![image](https://user-images.githubusercontent.com/46004116/78742395-59073300-7975-11ea-94cb-1a6ddcdd29d3.png)
