### ISSUE TITLE
Allow exporting in HTML

### ISSUE THREAD

**Issue by ilyaskarim** [carbon-app/carbon#964]
Currently, carbon-app provides export in PNG, SVG, and other formats. It would be great if carbon-app provides exporting the written code in HTML so that users can it in their blog apps.

**Comment by ariannargesi** [comment]
where is description  ?

**Comment by ilyaskarim** [comment]
@ariannargesi description added. Thanks for letting me know 👍

**Comment by mfix22** [comment]
@ilyaskarim would embedding work for your use case? The reason we support embedded iframes is for exactly what you are describing: including the snippet in your own blog

You can copy the Iframe under the copy menu, or else simply go to `carbon.now.sh/embed?<your query string here>`

**Comment by ilyaskarim** [comment]
@mfix22 Hey thanks for the comment. I was able to embed https://jsfiddle.net/8kubocLg/7/. One thing. I cannot copy the content inside. Do you know? Because I want my readers to copy the content as well. Is this a known bug? If the copy is not possible then definitely export HTML will be useful for me. For others as well.

**Comment by mfix22** [comment]
Hey @ilyaskarim I haven't noticed that issue before! One thing you can do is remove the `wc=false` from your query string to enable the copy button, which will let users super easily copy the code. 

I will have to investigate further to enable direct copying — potentially this is a Chrome bug

**Comment by mfix22** [comment]
@ilyaskarim opened up a new issue to track this bug (https://github.com/carbon-app/carbon/issues/972). If we fixed that bug, would iframes work for your use case?

**Comment by ilyaskarim** [comment]
@mfix22 That did the job. Thank you. That will work for me(https://jsfiddle.net/L6xantj0/). But one thing. I am giving you the option to decide. Will you keep this as feature-request? I am pretty sure that users will love this new feature. What do you think? 


- Sharing jsFiddle so that it will help other readers.

No problem if you can't.

**Comment by mfix22** [comment]
@ilyaskarim thank you so much for posting this! This issue actually uncovered 2 bugs in the embedded Carbon editor — both of which have been fixed.

Copying the text directly works again 👍 

To answer your question, we do not want to enable exporting the HTML directly, because then we are unable to fix issue on sites that have embedded the carbon snippet as HTML, which we can do as an iFrame.

**Comment by mfix22** [comment]
@all-contributors add @ilyaskarim for bug
