### ISSUE TITLE
Overlapped code when `Copy to Clipboard > Image`

### ISSUE THREAD

**Issue by deadcoder0904** [carbon-app/carbon#979]
I copied the following code from https://github.com/kitze/conditional-wrap

```js
import React from 'react';
import { render } from 'react-dom';
import { Tooltip } from 'react-tippy';

import ConditionalWrap from 'conditional-wrap';

const Button = ({ tooltip, children }) => (
  <ConditionalWrap
    condition={!!tooltip}
    wrap={children => (
      <Tooltip position="bottom" title={tooltip}>
        {children}
      </Tooltip>
    )}
  >
    <button>{children}</button>
  </ConditionalWrap>
);

const Demo = () => (
  <div>
    <Button> Normal button </Button>
    <Button tooltip="Hi there!"> Button with a tooltip! </Button>
  </div>
);

render(<Demo />, document.getElementById('root'));
```

And it gave this pic → https://twitter.com/deadcoder0904/status/1245953211439165441/

Notice the `Button` at the bottom is overlapped with the `div` while in the editor it looks perfect

**Comment by mfix22** [comment]
@deadcoder0904 which operating system and Browser were you using when you generated this image?

**Comment by deadcoder0904** [comment]
Mac OS Catalina v10.15.2 & Chrome v80.0.3987.149 (Official Build) (64-bit)

**Comment by deadcoder0904** [comment]
This seems to be duplicate of #743

**Comment by mfix22** [comment]
Interesting… not sure it is a duplicate since those issues wouldn’t occur on macOS. I have seen other one-off issues with the Copy image API, and I’m wondering if it is a bug in Chrome.

When you export the image as a PNG, do you see the same overlap?

**Comment by deadcoder0904** [comment]
Yep, it gives the same. Here you go (I did this just now) 👇

![carbon](https://user-images.githubusercontent.com/16436270/78521950-5bd51d00-77e9-11ea-8755-8e2d5a3bd6a2.png)

**Comment by mfix22** [comment]
@deadcoder0904 I couldn't recreate it locally. Looks like it is in fact a duplicate of #743. Feel free to add this reproduction to that issue and close this one, otherwise I can keep this one open for a time too.

**Comment by deadcoder0904** [comment]
I’ll close this one then & add a note there. Since it happened to me twice with the same code 😂

**Comment by mfix22** [comment]
Thanks @deadcoder0904
