### ISSUE TITLE
Suggestion: being able to give a name to a saved snippet

### ISSUE THREAD

**Issue by smknstd** [carbon-app/carbon#985]
When signed in, it would be great to be able to name a snippet. Especially when sharing an url in twitter (https://twitter.com/carbon_app/status/1235069621188751361), the twitter card could have a different title than simply "Carbon Snippet". Same for description.

![Screenshot_2020-04-07 smknstd on Twitter carbon_app there might be an issue with syntax highlighting in php Whatever theme ](https://user-images.githubusercontent.com/2412608/78646159-ec2e6300-78b8-11ea-8ed0-14cc41841924.png)

What do you think ?

**Comment by mfix22** [comment]
This is a great idea, and someone else also shared in it this issue https://github.com/carbon-app/carbon/issues/870#issue-498103778

Do you have suggestions for where the naming should go? I was thinking about adding an input to the bottom toolbar to the far left, opposite the copy/delete buttons. What do you think?

**Comment by smknstd** [comment]
Is it possible to get this screen working locally by bypassing api or something ? I'd love to help.

Concerning UX, ss snippets are created automatically from the home page, name (and description) wouldn't be mandatory, so unset by default. 

> I was thinking about adding an input to the bottom toolbar to the far left, opposite the copy/delete buttons

yes I think bottom bar could work nice. But don't forget you'll need to show validation messages so maybe a modal or something could also works great.

**Comment by mfix22** [comment]
@smknstd I'll look into that for you! I'm going to try and get to this feature next weekend. 

In the meantime, if you want to start by adding a borderless text input of the bottom left of the Snippet Toolbar, that would be really helpful! You won't need the backend to work on that part of this feature 👍
