### ISSUE TITLE
Theme configurations need updating with variable-2 and variable-3 options

### ISSUE THREAD

**Issue by smknstd** [carbon-app/carbon#987]
## Syntax highlighting with php seems broken

Whatever the theme I choose, syntax highlighting for PHP seems broken.

This is what it should show (as seen on [codemirror demo page](https://codemirror.net/mode/php/index.html)). It shows two different colors for variables and methods (blue and black):

![79136572-86a70e80-7db1-11ea-8307-78760c8044a1](https://user-images.githubusercontent.com/2412608/79216916-421d8080-7e4e-11ea-838a-cec9754071f2.png)

But this is what I get with "dracula" theme on carbon. It only shows one color (white) for both variables and methods:

![79136596-90c90d00-7db1-11ea-8fdf-c758f179db19](https://user-images.githubusercontent.com/2412608/79217085-86a91c00-7e4e-11ea-97df-cdb0c6a1065a.png)

This is an extract from theme's css, we should get two different colors:

```
.cm-s-dracula span.cm-variable { color: #50fa7b; }
.cm-s-dracula span.cm-variable-2 { color: white; }
```

but while inspecting I get something different:

![79137460-0c778980-7db3-11ea-8186-1f537e44e015](https://user-images.githubusercontent.com/2412608/79217233-c839c700-7e4e-11ea-9ee9-319e5c6b9fa1.png)

Here is a live example, but I noticed it on most php snippets I saw on twitter: https://carbon.now.sh/1HBRbot05AIFiezO6H2n

**Comment by mfix22** [comment]
Thanks for posting this. Just pushed this PR (https://github.com/carbon-app/carbon/pull/988) that fixes the underlying issue, and the configuration for Dracula, but it does not fix it for other themes. 

It would be _amazing_ if someone went through and set the `variable-2` and `variable-3` configs correctly for the other themes. 

If no one else takes it, I will try and get to it eventually 👍

**Comment by smknstd** [comment]
Good job, it's so much better now !
