### ISSUE TITLE
Suggestion for copy image to clipboard implementation

### ISSUE THREAD

**Issue by fuxingloh** [carbon-app/carbon#991]
Currently, you need to open/replace the current window to copy to clipboard.

I saw an implementation by `whimsical.com`, instead of opening a new tab or replacing the current window. You copy from the modal window directly without context switching. I added the image before for reference. Would be great if this can be implemented for carbon.

![image](https://user-images.githubusercontent.com/4266087/79635704-0d3e6000-81a5-11ea-80f5-0c6864c308dd.png)

**Comment by mfix22** [comment]
Hi @fuxingloh, thanks for the suggestion. Have you seen our new copy image to clipboard button? 
<img width="938" alt="Screenshot 2020-04-18 13 28 56" src="https://user-images.githubusercontent.com/8397708/79670526-9e4b1200-8178-11ea-9248-5511fd7c9396.png">

Clicking this will copy the Carbon image directly to your clipboard, without opening new windows or modals. 

Does that work for you? 🙂
