### ISSUE TITLE
String interpolation isn't highlighted in Kotlin code 

### ISSUE THREAD

**Issue by sandysnunes** [carbon-app/carbon#999]
**Describe the bug**
String interpolation isn't highlighted in Kotlin code 

**Screenshots**
![image](https://user-images.githubusercontent.com/677007/81478577-70dc0c00-91ec-11ea-9d00-ba977329821e.png)

**Info:**

- OS [Linux]:
- Browser [chrome 81]:

**Comment by mfix22** [comment]
@sandysnunes could you please include the code snippet or Carbon link in the issue? It makes it much much easier to debug

**Comment by mfix22** [comment]
Looks like the Kotlin docs does not treat the interpolated part as a separate highlighting. We just follow the Codemirror Kotlin mode. Looking at the Codemirror code would be your best bet to resolve this.
